/**
 * Created with IntelliJ IDEA.
 * User: raml
 * Date: 3/25/13
 */
define(function () {
    "use strict";

    var Dictionary = {
        "widget.itemsToPersonalize": "Visión nocturna",
        "widget.noItemsToPersonalize": "Visión nocturna: no hay elementos que pueda cambiar en esta página",

        "webAgent.ACD.title": "Cambiar opciones de cola",
        "webAgent.ACD.title.learnMore": "Más información",
        "webAgent.ACD.text": "Aceptar chats manualmente, o automáticamente a través de la Distribución automática de chat (ACD).",
        "webAgent.ACD.text.messaging": "Configurar la distribución automática de conversación (ACD).",
        "webAgent.ACD.text.willEffect": "* Los cambios realizados afectarán a todas las habilidades y agentes",
        "webAgent.ACD.text.web.chats": "Chat en vivo",
        "webAgent.ACD.edt.radio.accept": "ACEPTAR",
        "webAgent.ACD.edt.radio.ManualMode": "Modo manual: todos los agentes reciben el chat, pero solo uno pueden hacer clic para aceptarlo.",
        "webAgent.ACD.edt.radio.AutoAcceptMode": "Modo de aceptación automática: acepta los chats automáticamente a su llegada (ACD).",
        "webAgent.ACD.edt.radio.AdvancedMode": "Modo avanzado: aceptación manual con opciones avanzadas (ACD).",
        "webAgent.ACD.edt.radio.AutoAcceptMode.WrapUpTime": "Los chats serán transferidos de vuelta a la cola tras",
        "webAgent.ACD.edt.radio.AutoAcceptMode.seconds": "segundos si no se responden.",
        "webAgent.ACD.edt.radio.AdvancedMode.transferAfter": "Los chats serán transferidos de vuelta a la cola tras",
        "webAgent.ACD.edt.radio.AdvancedMode.seconds": "segundos si no se aceptan.",
        "webAgent.ACD.edt.radio.AdvancedMode.AgentStatus": "El estado del agente se",
        "webAgent.ACD.edt.radio.AdvancedMode.missedAccepting": "si no acepta un chat.",
        "webAgent.ACD.edt.radio.AdvancedMode.WrapUp": "El tiempo de WrapUp es",
        "webAgent.ACD.edt.radio.AdvancedMode.AgentStatus.dropDown.true": "cambiar estado a Ausente",
        "webAgent.ACD.edt.radio.AdvancedMode.AgentStatus.dropDown.false": "no cambiar",
        "webAgent.ACD.edt.radio.ManualMode.toolTip": "El chat entrante avisa simultáneamente a todos los agentes disponibles. El chat se asigna al primer agente que acepte la solicitud (ACD deshabilitado).",
        "webAgent.ACD.edt.radio.AutoAcceptMode.toolTip": "El chat se dirige al agente más disponible y se acepta automáticamente (ACD).",
        "webAgent.ACD.edt.radio.AdvancedMode.toolTip": "El chat se dirige al agente más disponible. El agente debe aceptar el chat manualmente.",
        "webAgent.ACD.edt.radio.messaging.AutoAcceptMode": "Modo de aceptación automática: aceptación automática con opciones avanzadas (ACD).",
        "webAgent.ACD.edt.radio.messaging.AutoAcceptMode.toolTip": "El chat se dirige al agente más disponible y se acepta automáticamente (ACD).",
        "webAgent.ACD.edt.radio.messaging.AdvancedMode": "Modo avanzado: aceptación manual con opciones avanzadas (ACD).",
        "webAgent.ACD.edt.radio.messaging.AdvancedMode.toolTip": "La conversación se dirige al agente más disponible. El agente debe aceptar manualmente la conversación.",
        "webAgent.ACD.text.app.connection": "Mensajería",
        "webAgent.ACD.text.conversations.transferred": "Las conversaciones se transferirán a la cola tras",
        "webAgent.ACD.text.if.not.accepted": "si no se aceptan.",
        "webAgent.ACD.seconds": "segundos",
        "webAgent.ACD.minutes": "minutos",
        "webAgent.ACD.hours": "horas",
        "webAgent.ACD.days": "días",
        "webAgent.ACD.time.error": "Introduzca un valor mayor que 0.",
        "webAgent.ACD.wrapUp.title": "Hora de cierre",
        "webAgent.ACD.wrapUp.error": "Introduzca una hora de cierre.",
        "webAgent.ACD.transfer.to.agent.back.to.queue.before": "Transferir a agente: Conversaciones que no fueron aceptadas por un agente en",
        "webAgent.ACD.transfer.to.agent.back.to.queue.after": "serán devueltas a la cola bajo la habilidad asignada del agente.",
        "webAgent.ACD.transfer.to.agent.back.to.queue.error.label": "Introduzca el valor completo en segundos, minutos, horas o días (entre un mínimo de 1 segundo y un máximo de 100 días).",
        
        "webAgent.clickToDummy.text": "Configuración del Espacio de trabajo del agente",
        "webAgent.clickToVisitorMenu.text": "Configuración de distribución del visitante",
        "webAgent.widget.bubble.title": "Modificar widgets",
        "webAgent.widget.bubble.text": "Añada, elimine y edite widgets en el Espacio de trabajo del agente para aumentar la eficiencia (máximo 5 widgets)<br>Organice todos los widgets para que se adapten a sus procesos de trabajo.",
        "webAgent.widget.bubble.link": "Más información",
        "webAgent.widget.add.bubble.text": "Ha alcanzado el número máximo de widgets.",
        "webAgent.widget.add.button.tooltip": "Añadir nuevo widget.",
        "webAgent.widget.widget.organize.button": "Organizar",
        "webAgent.widget.widget.organize.button.tooltip": "Organizar orden del widget",
        "webAgent.widget.widgetList.load.error": "Carga fallida; inténtelo de nuevo.",
        "webAgent.widget.widgetList.actions.edit": "Modificar",
        "webAgent.widget.widgetList.actions.hide": "Ocultar",
        "webAgent.widget.widgetList.actions.hide.tooltip": "El widget oculto no estará visible para ningún usuario en el Espacio de trabajo del agente.",
        "webAgent.widget.widgetList.actions.pilot": "Gestionar vista",
        "webAgent.widget.widgetList.actions.pilot.tooltip": "El widget en modo coordinador será visible solamente para los usuarios definidos como Coordinadores de agente o Administradores.",
        "webAgent.widget.widgetList.actions.remove": "Eliminar",
        "webAgent.widget.widgetList.actions.addWidget.default.name": "Widget de integración ",
        "webAgent.widget.widgetList.actions.remove.confirmation.title": "Eliminar widget",
        "webAgent.widget.widgetList.actions.remove.confirmation.text": "¿Seguro que desea eliminar este widget?",
        "webAgent.widget.widgetList.actions.unhide.confirmation.title": "Mostrar widget",
        "webAgent.widget.widgetList.actions.unhide.confirmation.text": "Al mostrar el widget estará visible para todos en la cuenta. ¿Seguro que desea mostrar este widget?",
        "webAgent.widget.widgetList.actions.removePilot.confirmation.title": "Eliminar el modo de visualización de coordinador",
        "webAgent.widget.widgetList.actions.removePilot.confirmation.text": "Al desconectar el modo de visualización de coordinador, este widget estará visible para todos en la cuenta. ¿Seguro que desea desconectar el modo de visualización de coordinador?",
        "webAgent.widget.widgetEdit.title": "Widget de integración",
        "webAgent.widget.widgetEdit.name.label": "Nombre del widget:",
        "webAgent.widget.widgetEdit.icon.label": "Etiqueta del widget:",
        "webAgent.widget.widgetEdit.icon.tooltip": "El icono se establece automáticamente en base al nombre del widget y será visible al agente en la barra de widgets.",
        "webAgent.widget.widgetEdit.description.label": "+ Añadir descripción",
        "webAgent.widget.widgetEdit.description.placeholder": "Añadir descripción...",
        "webAgent.widget.widgetEdit.description.tooltip": "La descripción aparecerá en el widget en sí mismo bajo el nombre del widget.",
        "webAgent.widget.widgetEdit.size.label": "Ampliar el tamaño del:",
        "webAgent.widget.widgetEdit.size.tooltip": "Elegir el tamaño de este widget. El tamaño se determina por a cuántos widgets predeterminados se ampliará.",
        "webAgent.widget.widgetEdit.size.1": "Widget único",
        "webAgent.widget.widgetEdit.size.2": "Widget doble",
        "webAgent.widget.widgetEdit.size.3": "Widget triple",
        "webAgent.widget.widgetEdit.size.4": "Widget cuádruple",
        "webAgent.widget.widgetEdit.skill.label": "Habilidades asignadas:",
        "webAgent.widget.widgetEdit.skill.placeholder": "Seleccione habilidades o deje en blanco para asignar todas las habilidades", //// MYWORD_COMPANY_LENGTH_50
        "webAgent.widget.widgetEdit.skill.tooltip": "Este widget se mostrará a las interacciones asignadas a las habilidades seleccionadas.",
        "webAgent.widget.widgetEdit.URL.label": "URL:",
        "webAgent.widget.widgetEdit.URL.tooltip": "Introduzca la URL de la página Web o sistema que desea integrar como widget. Tenga en cuenta que la página debe estar alojada de forma segura (https).",
        "webAgent.widget.widgetEdit.URL.link": "Integración SDK de LivePerson",
        "webAgent.widget.widgetEdit.URL.text": "Crear widget avanzado usando ",
        "webAgent.widget.widgetEdit.URL.preview.label": "URL completa:",
        "webAgent.widget.widgetEdit.URL.preview.tooltip": "La URL completa de la página Web, que se mostrará en el widget (la URL se renderiza en un IFrame).",
        "webAgent.widget.widgetEdit.advancedSettings.label": "Configuración avanzada de SDK de integración con LivePerson",
        "webAgent.widget.widgetEdit.fallback.URL.label": "Si el widget no se cargó, mostrar el siguiente enlace:",
        "webAgent.widget.widgetEdit.fallback.URL.tooltip": "Si el widget no se carga, se mostrará al agente una página de error con este enlace.",
        "webAgent.widget.widgetEdit.fallback.URL.timeout.prefix.label": "Mostrar enlace tras:",
        "webAgent.widget.widgetEdit.fallback.URL.timeout.suffix.label": "segundos.",
        "webAgent.widget.widgetEdit.fallback.URL.timeout.tooltip": "Determinar el número de segundos de espera tras no cargarse el widget, para mostrar el enlace alternativo configurado.",
        "webAgent.widget.widgetEdit.parameters.counter.label": " Parámetros añadidos",
        "webAgent.widget.widgetEdit.button.params": "Añadir parámetros de información de visita",
        "webAgent.widget.widgetEdit.button.params.tooltip": "Transferir información del Espacio de trabajo del agente a su página Web o sistema externo. Mapee los parámetros de la información de visita a los mismos nombres de parámetro en su archivo html.",
        "webAgent.widget.widgetEdit.button.cancel": "Cancelar",
        "webAgent.widget.widgetEdit.button.save": "Guardar",
        "webAgent.widget.widgetEdit.button.pilot": "Modo de visualización de coordinador",
        "webAgent.widget.widgetEdit.button.pilot.tooltip": "Activar el modo de visualización de coordinador hará que widget esté visible solo para los usuarios definidos como Administradores o Coordinadores de agentes.",
        "webAgent.widget.widgetEdit.errors.name.empty": "Introduzca el nombre del widget.",
        "webAgent.widget.widgetEdit.errors.name.not.unique": "El nombre del widget ya existe; introduzca un nombre único.",
        "webAgent.widget.widgetEdit.errors.max.widgets": "Ha alcanzado el número máximo de widgets.",
        "webAgent.widget.widgetEdit.errors.url.empty": "Introducir URL.",
        "webAgent.widget.widgetEdit.errors.url.not.valid": "Introduzca una URL válida.",
        "webAgent.widget.widgetEdit.errors.default.save": "El sistema no ha podido guardar la configuración. Inténtelo de nuevo.",
        "webAgent.widget.widgetEdit.errors.default.fetch": "El sistema no ha podido abrir el widget. Inténtelo de nuevo.",
        "webAgent.widget.widgetEdit.errors.default.delete": "El sistema no ha podido eliminar el widget. Inténtelo de nuevo.",
        "webAgent.widget.widgetEdit.errors.description.limit": "La descripción no puede superar los 1000 caracteres.",
        "webAgent.widget.widgetEdit.paramsEdit.title": "Parámetros de información de visita",
        "webAgent.widget.widgetEdit.paramsEdit.add.label": "Mapee los parámetros de la información de visita a los mismos nombres de parámetro en su archivo html",
        "webAgent.widget.widgetEdit.paramsEdit.warning.tooltip": "Tenga en cuenta que no se recomienda compartir datos sensibles a través de estos parámetros de URL ya que pueden ser guardados en el caché del navegador o en los archivos de registro del servidor web. Para compartir estos tipos de datos sensibles, se recomienda usar el SDK del Widget del área de trabajo del agente.",
        "webAgent.widget.widgetEdit.paramsEdit.userParam.placeholder": "Nombre del parámetro...",
        "webAgent.widget.widgetEdit.paramsEdit.userParam.tooltip": "Introduzca el nombre del parámetro como aparece en su archivo html.",
        "webAgent.widget.widgetEdit.paramsEdit.systemParam.placeholder": "Mapear a...",
        "webAgent.widget.widgetEdit.paramsEdit.systemParam.create.new": "Añadir variable personalizada",
        "webAgent.widget.widgetEdit.paramsEdit.systemParam.tooltip": "Seleccione el parámetro de Información del visitante al que desea mapear su parámetro URL.",
        "webAgent.widget.widgetEdit.paramsEdit.systemParam.identifier.tooltip": "Este parámetro puede usarse para identificar al visitante en su aplicación externa.",
        "webAgent.widget.widgetEdit.paramsEdit.button.add.tooltip": "Añada parámetros adicionales.",
        "webAgent.widget.widgetEdit.paramsEdit.button.delete.tooltip": "Eliminar parámetro.",
        "webAgent.widget.widgetEdit.paramsEdit.errors.name.empty": "Introduzca el nombre del parámetro.",
        "webAgent.widget.widgetEdit.paramsEdit.errors.name.invalid": "Nombre del parámetro no válido. El nombre no puede contener caracteres especiales.",
        "webAgent.widget.widgetEdit.paramsEdit.errors.value.empty": "Seleccione un parámetro de la lista.",
        "webAgent.widget.widgetEdit.paramsEdit.errors.name.taken": "El nombre del parámetro ya existe; introduzca un nombre de parámetro único.",
        "webAgent.widget.widgetEdit.paramsEdit.errors.save": "Tiene errores en la página.",
        "webAgent.widget.widgetEdit.paramsEdit.button.cancel": "Cancelar",
        "webAgent.widget.widgetEdit.paramsEdit.button.save": "Guardar parámetros",
        "webAgent.widget.widgetEdit.paramsEdit.confirmation.text": "Tiene cambios en el parámetro no guardados.<br>¿Qué le gustaría hacer antes de continuar?",
        "webAgent.widget.widgetEdit.paramsEdit.confirmation.button.save": "Añadir parámetro",
        "webAgent.widget.widgetEdit.paramsEdit.confirmation.button.remove": "No añadir parámetro",


        "webAgent.widget.widgetOrganize.button.save": "Listo",
        "webAgent.widget.widgetOrganize.title": "Organizar widgets",
        "webAgent.widget.widgetOrganize.subTitle": "Organizar el orden de los widgets de izquierda a derecha",
        "webAgent.widget.widgetOrganize.errors.default.save": "El sistema no ha podido cambiar el orden de los widgets. Inténtelo de nuevo.",

        "webAgent.widget.widgetOrganize.list.order.actions.movetop.tooltip": "Mover arriba",
        "webAgent.widget.widgetOrganize.list.order.actions.movebottom.tooltip": "Mover botón",
        "webAgent.widget.widgetOrganize.list.order.actions.moveup.tooltip": "Mover hacia arriba",
        "webAgent.widget.widgetOrganize.list.order.actions.movedown.tooltip": "Mover hacia abajo",


        "webAgent.widget.widgetName.ConsumerInfoWidget": "Información del consumidor",
        "webAgent.widget.widgetName.VisitInfoWidget": "Información de la visita",
        "webAgent.widget.widgetName.PageNavigationWidget": "Navegación de página",
        "webAgent.widget.widgetName.ChatHistoryWidget": "Historial de interacciones",
        "webAgent.widget.widgetName.AgentActionsWidgetContainer": "Resumen de la conversación - chat",
        "webAgent.widget.widgetName.PreDefinedWidget": "Contenido predefinido",
        "webAgent.widget.widgetName.AgentSummaryWidget": "Resumen de la conversación - mensajería",
        "webAgent.widget.widgetName.CoBrowseWidget": "CoBrowse",
        "webAgent.widget.widgetName.PCIDataWidget": "Datos PCI",
        "webAgent.widget.widgetName.OperatorAlertsWidget": "Alertas del operador",
        "webAgent.widget.widgetName.AIAssistWidget": "Acciones recomendadas",

        "webAgent.defaultAgentStatus.anchor.title.text": "Estado predeterminado",
        "webAgent.defaultAgentStatus.anchor.description.text": "Establecer estado predeterminado tras el inicio de sesión",
        "webAgent.defaultAgentStatus.anchor.current.text": "Actual:",
        "webAgent.defaultAgentStatus.edit.title.text": "Estado predeterminado",
        "webAgent.defaultAgentStatus.edit.description.text": "Establecer estado predeterminado tras el inicio de sesión",

        "webAgent.agentState.anchor.title.text": "Estado del agente",
        "webAgent.agentState.anchor.description.withAgentReasons.text": "Establecer el estado de inicio de sesión predeterminado y definir los motivos del estado Ausente personalizados.",
        "webAgent.agentState.anchor.description.withoutAgentReasons.text": "Establecer estado de inicio de sesión predeterminado.",
        "webAgent.agentState.anchor.currentDefaultState.text": "Estado predeterminado actual tras iniciar sesión:",
        "webAgent.agentState.anchor.currentAwayReasons.text": "Motivos del estado Ausente personalizados:",
        "webAgent.agentState.anchor.currentAwayReasons.noReasons.text": "No se han definido motivos para el estado Ausente.",
        "webAgent.agentState.edit.defaultState.title.text": "Estado predeterminado",
        "webAgent.agentState.edit.defaultState.description.text": "Establecer estado predeterminado tras el inicio de sesión",
        "webAgent.agentState.edit.awayReasons.title.text": "Estado del agente",
        "webAgent.agentState.edit.awayReasons.description.text": "Establecer los motivos del estado Ausente personalizados",
        "webAgent.agentState.edit.awayReasons.newButton.text": "+ Añadir motivo del estado Ausente personalizado",
        "webAgent.agentState.edit.awayReasons.default.tooltip": "Ausente (predeterminado) es el estado predeterminado del sistema. Se añadirán nuevos estados ausente personalizados además de este estado.",
        "webAgent.agentState.edit.awayReasons.dialog.new.title": "Añadir motivo del estado Ausente personalizado",
        "webAgent.agentState.edit.awayReasons.dialog.edit.title": "Editar motivo del estado Ausente personalizado",
        "webAgent.agentState.edit.awayReasons.dialog.placeholder": "Introducir motivo del estado",
        "webAgent.agentState.edit.awayReasons.delete.confirmation.title": "Eliminar motivo del estado Ausente personalizado",
        "webAgent.agentState.edit.awayReasons.delete.confirmation.text": "¿Seguro que desea eliminar este motivo del estado Ausente personalizado?",
        "webAgent.agentState.edit.awayReasons.maxEntities.tooltip": "Ha alcanzado el número máximo de motivos para el estado Ausente personalizado.",

        "webAgent.cobrowse.anchor.title.text": "CoBrowse",
        "webAgent.cobrowse.anchor.description.text": "Habilitar y configurar CoBrowse",
        "webAgent.cobrowse.anchor.cbEnabled.text": "CoBrowse habilitado",
        "webAgent.cobrowse.anchor.cbDisabled.text": "CoBrowse deshabilitado",
        "webAgent.cobrowse.edit.cbEnabled.label": "CoBrowse habilitado:",
        "webAgent.cobrowse.edit.cbMode.label": "Modo CoBrowse:",
        "webAgent.cobrowse.edit.cbMode.shared.label": "compartido",
        "webAgent.cobrowse.edit.cbMode.viewOnly.label": "solo vista",
        "webAgent.cobrowse.edit.errors.modeValidation": "Debe seleccionar al menos un modo CoBrowse.",
        "webAgent.cobrowse.edit.cbBorderColor.label": "Color del borde:",
        "webAgent.cobrowse.edit.cbHighlightColor.label": "Color de resaltado:",
        "webAgent.cobrowse.edit.cbResize.label": "Combinar con la ventana gráfica del visitante:",
        "webAgent.cobrowse.edit.cbResize.info": "Cambiar el tamaño de la ventana gráfica del visitante para que coincida con la ventana del navegador del visitante. Se recomienda para sitios web interactivos.",
        "webAgent.cobrowse.edit.cbFieldMasking.label": "Ocultación de campo:",
        "webAgent.cobrowse.edit.cbFieldMasking.info": "Contiene selectores CSS para seleccionar campos de formulario en su sitio web que pueden contener datos relevantes a la seguridad, y por tanto no deberían sincronizarse.",
        "webAgent.cobrowse.edit.cbFieldMasking.newItem": "Selector CSS",
        "webAgent.cobrowse.edit.advanced.label": "Configuración avanzada",

        "webAgent.fileSharing.anchor.title.text": "Intercambio de archivos",
        "webAgent.fileSharing.anchor.description.text": "Habilitar el intercambio de archivos para agentes",
        "webAgent.fileSharing.anchor.enabled.text": "Se ha habilitado el intercambio de archivos para agentes",
        "webAgent.fileSharing.anchor.disabled.text": "Se ha deshabilitado el intercambio de archivos para agentes",
        "webAgent.fileSharing.edit.enabled.label": "Se ha habilitado el intercambio de archivos para agentes:",
        "webAgent.fileSharing.edit.legal.label": "Comprendo que al habilitar la función de intercambio de archivos para agentes los agentes podrán compartir cualquier archivo al que tengan acceso en sus ordenadores o red con los consumidores durante una conversación.",

        "webAgent.SLA.title": "Tiempo de respuesta",
        "webAgent.SLA.description": "Configure el tiempo de respuesta para las conversaciones de mensajería.",
        "webAgent.SLA.current.label": "Actual:",
        "webAgent.SLA.default.label": "Predeterminado",
        "webAgent.SLA.urgent.label": "Urgente",
        "webAgent.SLA.first.time.label": "Primera vez",
        "webAgent.SLA.autoClose.label": "Cerrar conversaciones inactivas tras",
        "webAgent.SLA.autoClose.title": "Cerrar automáticamente - para conversaciones inactivas",
        "webAgent.SLA.autoClose.tooltip": "Las conversaciones inactivas se cerrarán automáticamente tras el periodo de tiempo configurado (entre 25 minutos y 90 días). Si la conversación está pendiente de respuesta del agente, o si el tiempo de respuesta ha sido configurado manualmente, no se aplicará el cierre automático.",
        "webAgent.SLA.input.error.label": "Introduzca un valor mayor que 0.",
        "webAgent.SLA.autoClose.error.label": "Introduzca el valor completo en minutos, horas o días (entre un mínimo de 25 minutos y un máximo de 90 días).",

        "webAgent.CSAT.title": "Puntuación CSAT",
        "webAgent.CSAT.description": "Defina si los agentes pueden ver la puntuación CSAT en Mensajería.",
        "webAgent.CSAT.current.label": "Actual:",
        "webAgent.CSAT.visible.label": "Visible",
        "webAgent.CSAT.hidden.label": "Oculta",
        "webAgent.CSAT.edit.comment": "*Los coordinadores de agentes verán la puntuación CSAT como antes.",

        "userManagement.lob.title": "Líneas de negocio",
        "userManagement.lob.description": "Añada la capacidad de segregar su cuenta en múltiples Líneas de negocio.",
        "userManagement.lob.title.learnMore": "Más información",
        "userManagement.lob.current.label": "Actual:",
        "userManagement.lob.enabled.label": "Habilitado",
        "userManagement.lob.disabled.label": "Deshabilitado",
        "userManagement.lob.description.disabled.functionality": "Para desactivar esta función, primero debe eliminar todas las Líneas de negocio configuradas en la zona \"Usuarios\".",

        "userManagement.lpa.title": "Permisos LPA",
        "userManagement.lpa.description": "Habilite y configure los perfiles que se asignarán a los Administradores de LivePerson (LPA) tras el inicio de sesión.",
        "userManagement.lpa.title.learnMore": "Más información",
        "userManagement.lpa.current.label": "Actual:",
        "userManagement.lpa.enabled.label": "Habilitado",
        "userManagement.lpa.edit.enabled.label": "Habilitado:",
        "userManagement.lpa.disabled.label": "Deshabilitado",
        "userManagement.lpa.assign.title": "Asignación de perfil",
        "userManagement.lpa.assign.description": "Asigne uno o más perfiles (uno por función).",
        "userManagement.lpa.assign.placeholder": "Asignar perfil",
        "userManagement.lpa.save.tooltip": "Debe asignarse al menos un perfil antes de guardar.",
        "userManagement.lpa.save.conflict": "No hemos podido guardar esta configuración porque alguien está editándola actualmente."

    };
    return Dictionary;
});
