/**
 * Created with IntelliJ IDEA.
 * User: ahmadao
 * Date: 3/21/13
 * Time: 3:24 PM
 * To change this template use File | Settings | File Templates.
 */
define(function () {
    "use strict";

    var Dictionary = {
        "EngagementsBarLabel": "INTERACCIONES",
        "AHTBarLabel": "DURACIÓN MED DEL INT.",
        "UilizationBarLabel": "CAPACIDAD UTILIZADA",
        "interEngPerHourBarLabel": "INT. POR HORA",
        "CSATBarLabel": "CSAT",
        "MinChatsNumberMessagePart1": "Disponible tras",
        "MinChatsNumberMessagePart2": "interacciones finalizadas",
        "AbandonmentRateBarLabel": "PORCENTAJE DE ABANDONOS",
        "ConnectedEngBarLabel": "CONECTADO",
        "AbandonedEngBarLabel": "ABANDONADO",
        "AvgTimeToAbandonBarLabel": "TIEMPO MED. PARA ABANDONAR",
        "AvgTimeToAnswerBarLabel": "TIEMPO MED. PARA RESPONDER",

        "CM_VisitsBarLabel": "Visitas",
        "CM_EligableBarLabel": "Clientes potenciales",
        "CM_ExposedBarLabel": "Exposiciones",
        "CM_EngagementsBarLabel": "Interacciones",
        "CM_IncrementalRevenueBarLabel": "AUMEN. Ingresos",
        "CM_ConversionLiftBarLabel": "AUMEN. Conversiones",
        "CM_RevenueBarLabel": "Ingresos",
        "CM_ConversionsBarLabel": "Conversiones",
        "CM_GoalReachedBarLabel": "Objetivo alcanzado",
        "CM_DisabledByLobFilter": "Para ver los datos, filtre la lista de campañas para mostrar solo una línea de negocio.",

        "AGENT_LIST_OnlineBarLabel": "EN LÍNEA",
        "AGENT_LIST_BackSoonBarLabel": "VUELVO EN SEGUIDA",
        "AGENT_LIST_AwayBarLabel": "AUSENTE",
        "AGENT_LIST_ConcurrentChatsBarLabel": "CHATS ACTUALES",
        "AGENT_LIST_MaxConcurrentBarLabel": "CAPACIDAD DE CHAT",
        "AGENT_LIST_Unlimited": "Ilimitado",

        "HOT_TOPICS_TotalChatsAnalyzedBarLabel": "TOTAL CHATS ANALIZADOS",
        "HOT_TOPICS_ChatsWithSentimentBarLabel": "CHATS CON TEMAS CANDENTES",
        "HOT_TOPICS_PositiveSentimentBarLabel": "SENTIMIENTO POSITIVO",
        "HOT_TOPICS_NegativeSentimentBarLabel": "SENTIMIENTO NEGATIVO",

        "MY_CONNECTIONS_active.label":  "Abrir",
        "MY_CONNECTIONS_pending.label":  "Pendiente",
        "MY_CONNECTIONS_unassigned.label": "No asignado",
        "MY_CONNECTIONS_inQueue.label": "En cola",
        "MY_CONNECTIONS_actionable.label": "Accionable",
        "MY_CONNECTIONS_overdue.label": "Vencido",
        "MY_CONNECTIONS_soonToOverdue.label": "Vencerá pronto.",
        "MY_CONNECTIONS_CSAT.label": "CSAT",

        "GUEST_SitesVisitsObserved": "VISITAS A SITIOS WEB OBSERVADAS",
        "GUEST_LiveChats": "CHATS EN VIVO",
        "GUEST_Conversions": "AUMENTO DE CONVERSIONES",
        "GUEST_AvgOrderValues": "% AUM. MED. VALOR DE PEDIDO",

        "DB_WidgetAovTitle": "Valor medio de pedido (VMP)",
        "DB_WidgetAovExposedLabel": "Grupo expuesto",
        "DB_WidgetAovControlLabel": "Grupo de control",
        "DB_WidgetCsatTitle": "Satisfacción del cliente",
        "DB_WidgetCsatTitleReviews": "opiniones",
        "DB_WidgetCsatAnswer_5": "Muy poco satisfecho",
        "DB_WidgetCsatAnswer_4": "Poco satisfecho",
        "DB_WidgetCsatAnswer_3": "Ninguno",
        "DB_WidgetCsatAnswer_2": "Satisfecho",
        "DB_WidgetCsatAnswer_1": "Muy satisfecho",

        "DB_WidgetFunnelTitle": "Rendimiento",
        "DB_WidgetFunnelExposedLabel": "Exposiciones",
        "DB_WidgetFunnelEngagedLabel": "Interacciones",
        "DB_WidgetFunnelConversionsLabel": "Conversiones",
        "DB_WidgetFunnelGoalReachedLabel": "Objetivo alcanzado",
        "DB_WidgetConversionRateTitle": "Tasas de conversión",
        "DB_WidgetConversionRateTitle_goalReached": "Tasas de objetivo alcanzado",
        "DB_WidgetInteractiveEngagementsLabel": "Interacciones bilaterales",
        "DB_EngagementsWidgetText": "LOS INTERACCIÓNES ERAN INTERACTIVOS",
        "DB_WidgetStateDistributionLabel": "Tiempo de sesión iniciada",
        "DB_WidgetStateDistributionClockMin": "hr",
        "DB_WidgetStateDistributionClockLabel": "SESIÓN INICIADA",
        "DB_WidgetStateDistributionLegendOnline": "EN LÍNEA",
        "DB_WidgetStateDistributionLegendBI5": "VUELVO EN SEGUIDA",
        "DB_WidgetStateDistributionLegendAway": "AUSENTE",
        "DB_WidgetStateDistributionLegendChatted": "TIEMPO EN CHAT",
        "DB_WidgetStateDistributionTooltipTotal": "Total",
        "DB_WidgetStateDistributionTooltipChatted": "Hablado",
        "DB_WidgetCsatTooltipLabel": "OPINIÓN DEL VISITANTE",

        "DB_WidgetConversionRateLabel_chat": "Chat",
        "DB_WidgetConversionRateLabel_content": "Contenido (vtc)",
        "DB_WidgetConversionRateLabel_clickedThroughContent": "Contenido (ctc)",
        "DB_WidgetConversionRateLabel_controlGroup": "Control",

        "DB_WidgetConversionsPerGoalTitle": "Conversiones incrementales por tipo de objetivo",
        "DB_WidgetConversionsPerGoalTitleNoControlGroup": "Conversiones por tipo de objetivo",

        "DB_WidgetGoalReachedPerGoalTypeTitle": "Objetivo conseguido por tipo de objetivo",
        "DB_WidgetGoalReachedPerGoalTypeNoData" : "No se han definido objetivos",
        "DB_WidgetGoalReachedPerGoalTypeLabel_ConversionGoals": "Objetivos de conversión",
        "DB_WidgetGoalReachedPerGoalTypeLabel_OtherGoals": "Otros objetivos",
        "DB_WidgetGoalReachedPerGoalTypeLabel_ServiceGoals": "Objetivos del servicio",

        "DB_WidgetAvgHandlingTime": "Duración media de la interacción",
        "DB_WidgetAvgHandlingTimeYlabel": "MÍN",
        "DB_WidgetAvgHandlingTimeXlabel": "Actual",
        "DB_WidgetAvgHandlingTimeTooltip": "DURACIÓN MED DEL INT.",

        "DB_WidgetEngagedPerGoalTitle": "Interacción por tipo de objetivo",

        "DB_WidgetEngagedPerGoalEngagementsLabel": "Interacciones",
        "DB_WidgetEngagedPerGoa_Chats": "Chats",
        "DB_WidgetEngagedPerGoa_Content": "Contenido",
        "DB_WidgetEngagedPerGoa_Total": "TOTAL",

        "DB_WidgetAbandonRate": "Porcentaje de abandono",
        "DB_WidgetAbandonRate_tooltip": "Abandonado",

        "DB_AdminManagerTable_Title_skill": "HABILIDAD",
        "DB_AdminManagerTable_Title_abandonedRate": "PORCENTAJE <br>DE ABANDONOS",
        "DB_AdminManagerTable_Title_currentQueueSize": "EN COLA",
        "DB_AdminManagerTable_Title_connected": "CONECTADO",
        "DB_AdminManagerTable_Title_abandoned": "ABANDONADO",
        "DB_AdminManagerTable_Title_avgAbandoned": "TIEMPO MED.<br>PARA ABANDONAR",
        "DB_AdminManagerTable_Title_avgAnswer": "TIEMPO MED.<br>PARA RESPONDER",
        "DB_AdminManagerTable_all": "Todas las habilidades",
        "DB_AdminManagerTable_unassigned": "No asignado",
        "DB_AdminManagerTable_No_data": "No hay interacciones en cola",

        "DB_WidgetGoalReachedAfterEngagementsTitle_chat": "Objetivo alcanzado tras los chats",
        "DB_WidgetGoalReachedAfterEngagementsTitle_content": "Objetivo alcanzado tras clic en contenido",
        "DB_WidgetGoalReachedAfterEngagementsTooltip_label": "Objetivo alcanzado",
        "DB_WidgetConversionsAfterEngagementsTitle_chat": "Conversiones tras chats",
        "DB_WidgetConversionsAfterEngagementsTitle_content": "Conversiones tras clic en contenido",
        "DB_WidgetConversionsAfterEngagementsTooltip_label": "Conversiones",
        "DB_WidgetConversionsAfterEngagementsChannel_sell": "Vender",
        "DB_WidgetConversionsAfterEngagementsChannel_genLeads": "Gen. Clientes pot.",

        "DB_WidgetRevenuesAfterEngagementsTitle_chat": "Ingresos tras chats",
        "DB_WidgetRevenuesAfterEngagementsTitle_content": "Ingresos tras clic en contenido",
        "DB_WidgetRevenuesAfterEngagementsTooltip_label": "Ingresos",
        "DB_WidgetRevenuesAfterEngagementsChannel_label": "Total",

        "DB_WidgetAvgAnswerVsAvgAbandon": "Tiempo medio de espera",
        "DB_WidgetAvgAnswerVsAvgAbandon_answer": "Tiempo en contestar",
        "DB_WidgetAvgAnswerVsAvgAbandon_abandon": "Tiempo en abandonar",

        "DB_WidgetResolvedConversation_title": "Conversaciones cerradas",
        "DB_WidgetResolvedConversation_tooltip_resolvedConversation": "conversaciones cerradas",
        "DB_WidgetResolvedConversation_tooltip_resolvedByConsumer": "cerrada por el consumidor",
        "DB_WidgetResolvedConversation_tooltip_resolvedBySystem": "cerrado automáticamente",
        "DB_WidgetResolvedConversation_tooltip_resolvedByCCP": "cerrado por el agente",
        "DB_WidgetResolvedConversation_tooltip_avgTime": "Promedio de t. para resolver",
        "DB_WidgetResolvedConversation_serie_ccp_name": "AGENTE",
        "DB_WidgetResolvedConversation_serie_consumer_name": "CONSUMIDOR",
        "DB_WidgetResolvedConversation_serie_system_name": "AUTOMÁTICO",

        "DB_WidgetSla_title": "Nivel de servicio",
        "DB_WidgetSla_tooltip_chats": "cantidad en el intervalo de tiempo",
        "DB_WidgetSla_tooltip_percentages": "porcentaje en el intervalo de tiempo",
        "DB_WidgetSla_tooltip_accumulated": "porcentaje acumulado",

        "DB_WidgetQueueSize_title": "Tamaño de la cola",
        "DB_WidgetQueueSize_tooltip": "tamaño de la cola",

        "NotAvailableLabel": "N/A",

        "DB_Timeframe": "Periodo",
        "DB_TimeframeTooltip": "Periodo",
        "DB_Skills": "Habilidades",
        "DB_Skills_Filter_Placeholder": "Introduzca habilidad(es) predefinida(s)",
        "DB_Skills_Filter_max_reached": "Ha superado el número máximo de habilidades permitidas.",
        "DB_Max_Days": "(Máx {} días)",
        "DB_SaveButtonAltText": "Filtrar",
        "DB_CE_LPA_Title": "Atención",
        "DB_CE_LPA_Message": "El chat contiene datos confidenciales. Está prohibido la distribución o uso no autorizados de esta información y puede ser ilegal.",
        "DB_CE_LPA_Continue": "Continuar",
        "DB_ChatExport_obsolete_Title": "Atención",
        "DB_ChatExport_obsolete_Message": "¡Buenas noticias! Estamos haciendo que la exportación de transcripciones se más rápida y fácil. Pruebe nuestra exportación en la zona Historial Web (Visitantes ->Historial Web). Exportar transcripciones desde este panel de control ya no estará disponible desde el 1 de julio. ",
        "DB_ChatExport_obsolete_Continue": "Continuar",
        "DB_ChatExport": "Exportar copias del chat",
        "DB_CE_date_title": "Fecha y hora",
        "DB_CE_AdditionalFilters": "Filtros adicionales",
        "DB_CE_from": "Desde",
        "DB_CE_to": "Hasta",
        "DB_CE_Export": "Exportar",
        "DB_CE_skill": "Habilidad",
        "DB_CE_export": "Exportar como",
        "DB_CE_keyword": "Palabra clave",
        "DB_CE_checkbox_text": "Incluir formularios offline",
        "DB_CE_checkbox_License_text": "He leído y acepto el",
        "DB_CE_checkbox_License_link": "Acuerdo de licencia",
        "DB_CE_License_text": "La información solicitada puede almacenarse en el caché del disco duro local de su equipo. Para asegurar una navegación Web segura, debería eliminar regularmente su caché tras ver sus datos personales, sobre todo si está usando un dispositivo público o compartido.",
        "DB_CE_format_xml": "XML",
        "DB_CE_format_txt": "TXT",
        "DB_CE_format_excel": "EXCEL",
        "DB_CE_all_skills": "Todas las habilidades",

        "DB_filters_data_tooltip": "Selector de periodo de tiempo",
        "DB_filters_mstrLink_tooltip": "Panel de control de facturación",
        "DB_filters_biLink_tooltip": "Paneles de control BI de la campaña",
        "DB_filters_biLink_tooltip_lpa": "Paneles de control BI de la campaña - Solo para LPAs",
        "DB_filters_chatExport_tooltip": "Exportar copias del chat",
        "DB_filters_mstrAdminLink_tooltip": "Paneles BI de Coordinador de agente",
        "DB_filters_mstrAdminLink_tooltip_lpa": "Paneles de control BI del agente- Solo para LPAs",
        "DB_filters_reportBuilderLink_tooltip_lpa": "Creador de informes - Solo para LPA",
        "DB_filters_reportBuilderLink_tooltip": "¡Nuevo! Creador de informes",
        "DB_filters_intentDashboardLink_tooltip": "Panel de control de intención",
        "DB_filters_timeFilter_tooltip": "Filtrar por tiempo",
        "DB_filters_skillsFilter_tooltip": "Filtrar por habilidades",
        "DB_filters_participantsFilter_tooltip": "Filtrar por participante del chat",

        "DB_WidgetConvVsAvrConvTitle": "Conversiones incrementales: Campaña vs. tipo de objetivo",
        "DB_WidgetConvVsAvrConvTitleNoCG": "Tasa de conversión: Campaña vs. tipo de objetivo",
        "DB_WidgetConvVsAvrConvTitle_goalReached": "Objetivo incremental alcanzado: Campaña vs. tipo de objetivo",
        "DB_WidgetConvVsAvrConvTitleNoCG_goalReached": "Tasa de objetivo alcanzado: Campaña vs. tipo de objetivo",

        "DB_WidgetCampaignContributionToGoalsTitle": "Contribución de la campaña a objetivos",
        "DB_WidgetCampaignContributionToGoalsTooltip_myCampaign": "MY CAMPAÑA",
        "DB_WidgetCampaignContributionToGoalsTooltip_label": "Conversiones",
        "DB_WidgetCampaignContributionToGoalsTooltip_label_goalReached": "objetivo alcanzado",
        "DB_WidgetCampaignContributionToGoalsTooltip_multi_label": "OBJETIVOS:",
        "DB_WidgetCampaignContributionToGoals_noData": "Esta campaña no ha contribuido aún<br>a un objetivo.",
        "DB_WidgetCampaignContributionToGoals_NA": "Lo sentimos, no pudimos extraer <br>el mensaje de datos.",


        "DB_WidgetTooltip_engagements": "Número de interacciones bilaterales completadas del número total de interacciones conectadas completadas.",
        "DB_WidgetTooltip_loggedInTime": "Distribución de las diferentes actividades del agente durante el tiempo con sesión iniciada.<br>El anillo interior (naranja) indica el tiempo que el agente chateó.",
        "DB_WidgetTooltip_avg": "Duración media de la interacción de las interacciones completadas calculadas cada 15 minutos.",
        "DB_WidgetTooltip_engagedPerCoal": "Desglose por tipo de objetivo de:<br>Número de chats interactivos,<br>número de clics en contenido y<br>número total de interacciones (clics en contenido + chats interactivos).",
        "DB_WidgetTooltip_funnel_conversions": "Exposiciones vs. Interacciones vs. Conversiones a lo largo del tiempo.",
        "DB_WidgetTooltip_funnel_goalReached": "Exposiciones vs. Interacciones vs. Objetivo alcanzado a lo largo del tiempo.",
        "DB_WidgetTooltip_aov": "El valor medio de la orden generado por los visitantes que estuvieron expuestos a campañas vs. valor medio de la orden generado por el grupo de control.",
        "DB_WidgetTooltip_conversionPerGoal": "Conversiones incrementales por tipo de objetivo generadas por visitas expuestas a interacciones gráficas.",
        "DB_WidgetTooltip_conversionPerGoalNoControlGroup": "Nº de conversiones por tipo de objetivo generadas por visitas expuestas a interacciones gráficas.",
        "DB_WidgetTooltip_incConvVsAvgIncConv": "Conversiones incrementales de la campaña seleccionada vs. media de conversiones incrementales de todas las campañas del mismo tipo de objetivo.",
        "DB_WidgetTooltip_incConvVsAvgIncConvNoControlGroup": "Tasa de conversión por campaña seleccionada vs. tasa de todas las campañas del mismo tipo de objetivo.",
        "DB_WidgetTooltip_incConvVsAvgIncConv_goalReached": "Objetivo incremental de la campaña seleccionada vs. media de objetivos incrementales alcanzados de todas las campañas del mismo tipo de objetivo.",
        "DB_WidgetTooltip_incConvVsAvgIncConvNoControlGroup_goalReached": "Tasa de objetivo alcanzado para campaña seleccionada vs. tasa de objetivos alcanzados de todas las campañas del mismo tipo de objetivo.",
        "DB_WidgetTooltip_csat": "Distribución de respuestas de satisfacción del cliente (CSAT), en base al cuestionario post chat.",
        "DB_WidgetTooltip_csat_messaging": "Distribución de respuestas de satisfacción del cliente (CSAT), en base al cuestionario.",
        "DB_WidgetTooltip_conversionRate": "Tasas de conversión de diferentes canales:<br>Tasa de conversión de chat - Tasa de conversión tras chat interactivo.<br>Tasa de contenido (VTC) - Tasa de conversión tras exposición a contenido.<br>Tasa de contenido (CTC) - Tasa de conversión tras clics de contenido.<br>Tasa de conversión de grupo de control - Tasa de conversión del grupo de control.",
        "DB_WidgetTooltip_conversionRate_goalReached": "Tasas de conversión de diferentes canales:<br>Tasa alcanzada de objetivo de chat - Tasa de objetivo alcanzada tras chat interactivo.<br>Tasa de contenido (VTC) - Tasa alcanzada de objetivo tras exposición a contenido.<br>Tasa de contenido (CTC) - Tasa de objetivo alcanzado tras clics de contenido.<br>Tasa de conversión de grupo de control - Tasa de objetivo alcanzado del grupo de control.",
        "DB_WidgetTooltip_conversionRate_multiCurrencies": "El ingreso está en multi divisa. Para un desglose parcial por divisa, consulte el Seguimiento de objetivos del agente (disponible en el BI del Gestor de agentes). Para el desglose completo, consulte el Creador de informes.",
        "DB_WidgetTooltip_CampaignContributionToGoals": "Número de veces en las que se alcanzaron los diferentes objetivos como resultado de la exposición del visitante a interacciones gráficas (ya fueran interacciones gráficas visualizadas o interacciones gráficas visualizadas y con las que se interactuó) que pertenecían a la campaña.",
        "DB_WidgetTooltip_abandonRate": "Porcentaje de visitantes que abandonaron la cola de todos los visitantes que están en la cola.",
        "DB_WidgetTooltip_avgAnswerAndAbandon": "La línea naranja indica el tiempo medio (hh:mm:ss) desde que los visitantes estaban en la cola hasta que los agentes conectaron con ellos.<br>La línea gris indica el tiempo medio (hh:mm:ss) desde que los visitantes estaban en la cola hasta que la abandonaron.",
        "DB_WidgetTooltip_goalReachedPerGoalType": "Nº de objetivos que fueron conseguidos por visitantes expuestos a campañas, divididos por tipo de objetivo.",
        "DB_WidgetTooltip_conversionsAfterEngagements_chat": "Nº de objetivos de conversión que fueron alcanzados tras chats interactivos.",
        "DB_WidgetTooltip_conversionsAfterEngagements_content": "Nº de objetivos de conversión que fueron alcanzados tras clic en contenido.",
        "DB_WidgetTooltip_goalReachedAfterEngagements_chat": "Nº de objetivos que fueron alcanzados tras chats interactivos.",
        "DB_WidgetTooltip_goalReachedAfterEngagements_content": "Nº de objetivos que fueron alcanzados tras clic en contenido.",
        "DB_WidgetTooltip_revenuesAfterEngagements_chat": "Ingresos generados tras chats interactivos.",
        "DB_WidgetTooltip_revenuesAfterEngagements_content": "Ingresos tras clics en contenido.",
        "DB_WidgetTooltip_resolvedConversations": "El número de conversaciones cerradas (ver columnas), dividido por cómo se cerraron, comparado contra el promedio de tiempo para resolver (consulte la línea). <br>El eje Y se refiere a las columnas. El eje Y derecho se refiere a la línea (hh:mm).",
        "DB_WidgetTooltip_sla": "Este widget muestra el nivel de servicio en tiempo real para el plazo de tiempo seleccionado.<br>Las barras naranjas representan el porcentaje de conversaciones respondidas en los intervalos de tiempo especificados en el eje.<br>El gráfico de líneas representa el porcentaje acumulado y la cantidad de conversaciones respondidas en los intervalos de tiempo.",
        "DB_WidgetTooltip_queueSize": "Tamaño medio de la cola durante el periodo de tiempo especificado.",

        "DB_KpiTooltip_pValue": "Significancia estadística: P = ",
        "DB_KpiTooltip_TotalVisits": "Número de visitantes monitorizados en el sitio Web. La cifra incluye los visitantes recurrentes.",
        "DB_KpiTooltip_NumOfEligibleVisits": "Número de visitas en las que los visitantes son elegibles para recibir al menos una interacción gráfica (invitación, botón o contenido) de esta campaña específica. Esta cifra incluye el grupo de control, si se ha definido.",
        "DB_KpiTooltip_NumOfEligibleVisitsAllCampaigns": "Número de visitas en las que los visitantes son elegibles para recibir al menos una interacción gráfica (invitación, botón o contenido) desde cualquier campaña. Esta cifra incluye el grupo de control, si se ha definido.",
        "DB_KpiTooltip_NumOfEligibleVisitsSpecificCampaign": "Número de visitas en las que los visitantes son elegibles para recibir al menos una interacción gráfica (invitación, botón o contenido) de esta campaña específica. Esta cifra incluye el grupo de control, si se ha definido.",
        "DB_KpiTooltip_NumOfExposedViews": "Número de interacciones gráficas que se muestran a los visitantes. Por ejemplo: botones, invitaciones y contenido.",
        "DB_KpiTooltip_NumOfEngagedVisits": "Número de chats interactivos y clics sobre contenido.",
        "DB_KpiTooltip_IncrementalConversion_accountLevel": "KPI primaria: Nº de objetivos de conversión que se alcanzaron por las visitas expuestas a campañas (que vieron una interacción gráfica o vieron interacciones gráficas e interactuaron).<br>",
        "DB_KpiTooltip_IncrementalConversion_campaignLevel": "KPI primaria: Nº de objetivos de conversión que se alcanzaron por los visitantes expuestos a campañas (que vieron una interacción gráfica o vieron interacciones gráficas e interactuaron).<br>",
        "DB_KpiTooltip_IncrementalConversion_incr_accountLevel": "<br>KPI secundario: <br><u>AUMEN. Conversiones:</u> Representa el número de objetivos de conversión que se generaron como resultado de la exposición a las campañas, y no habrían ocurrido sin exposición.<br>",
        "DB_KpiTooltip_IncrementalConversion_incr_campaignLevel": "<br>KPI secundario: <br><u>AUMEN. Conversiones:</u> Representa el número de objetivos de conversión que se generaron como resultado de la exposición a las campañas, y no habrían ocurrido sin exposición.<br>",
        "DB_KpiTooltip_IncrementalConversion_lift_accountLevel": "<br>Al pasar: <br><u>Aumento de conversiones</u>: Representa el porcentaje de objetivos de conversión que se generaron como resultado de la exposición a las campañas, y no habrían ocurrido sin exposición.",
        "DB_KpiTooltip_IncrementalConversion_lift_campaignLevel": "<br>Al pasar: <br><u>Aumento de conversiones</u>: Representa el porcentaje de objetivos de conversión que se generaron como resultado de la exposición a las campañas, y no habrían ocurrido sin exposición.",
        "DB_KpiTooltip_IncrementalGoalsReached": "KPI primaria: Nº de objetivos de conversión que se alcanzaron por los visitantes expuestos a campañas (que vieron una interacción gráfica o vieron interacciones gráficas e interactuaron).<br>",
        "DB_KpiTooltip_IncrementalGoalsReached_incr": "<br>KPI secundario: <br><u>AUMEN. Objetivo alcanzado:</u> Representa el número de objetivos alcanzados como resultado de la exposición a las campañas, y no habrían ocurrido sin exposición.<br>",
        "DB_KpiTooltip_IncrementalGoalsReached_lift": "<br>Al pasar: <br><u>Aumento de objetivo alcanzado:</u> Representa el porcentaje de objetivos alcanzados como resultado de la exposición a las campañas, y no habrían ocurrido sin exposición.",
        "DB_KpiTooltip_IncrementalRevenue_accountLevel": "KPI primaria: Ingresos generados por las visitas expuestas a campañas (que vieron interacciones gráficas o vieron interacciones gráficas e interactuaron).<br>",
        "DB_KpiTooltip_IncrementalRevenue_campaignLevel": "KPI primaria: Ingresos generados por los visitantes expuestos a la campaña (que vieron interacciones gráficas o vieron interacciones gráficas e interactuaron).<br>",
        "DB_KpiTooltip_IncrementalRevenue_incr_accountLevel": "<br>KPI secundario: <br><u>AUMEN. Ingresos:</u> Representa los ingresos que se generaron como resultado de la exposición a las campañas, y no habrían ocurrido sin exposición.<br>",
        "DB_KpiTooltip_IncrementalRevenue_incr_campaignLevel": "<br>KPI secundario: <br><u>AUMEN. Ingresos:</u> Representa los ingresos que se generaron como resultado de la exposición a las campañas, y no habrían ocurrido sin exposición.<br>",
        "DB_KpiTooltip_IncrementalRevenue_lift_accountLevel": "<br>Al pasar: <br><u>Aumento ingresos</u>: Representa el porcentaje de ingresos que se generaron como resultado de la exposición a las campañas, y no habrían ocurrido sin exposición.",
        "DB_KpiTooltip_IncrementalRevenue_lift_campaignLevel": "<br>Al pasar: <br><u>Aumento ingresos</u>: Representa el porcentaje de ingresos que se generaron como resultado de la exposición a las campañas, y no habrían ocurrido sin exposición.",
        "DB_KpiTooltip_Conversions_accountLevel": "Nº de objetivos de conversión que se alcanzaron por las visitas expuestas a campañas (que vieron una interacción gráfica o vieron interacciones gráficas e interactuaron).",
        "DB_KpiTooltip_Conversions_campaignLevel": "Nº de objetivos de conversión que se alcanzaron por los visitantes expuestos a campañas (que vieron una interacción gráfica o vieron interacciones gráficas e interactuaron).",
        "DB_KpiTooltip_GoalsReached": "Nº de objetivos de conversión que se alcanzaron por los visitantes expuestos a campañas (que vieron una interacción gráfica o vieron interacciones gráficas e interactuaron).",
        "DB_KpiTooltip_Revenue_accountLevel": "Ingresos generados por las visitas expuestas a campañas (que vieron interacciones gráficas o vieron interacciones gráficas e interactuaron).",
        "DB_KpiTooltip_Revenue_campaignLevel": "Ingresos generados por los visitantes expuestos a la campaña (que vieron interacciones gráficas o vieron interacciones gráficas e interactuaron).",
        "DB_KpiTooltip_multiCurrency": "El ingreso está en multi divisa. Para un desglose parcial por divisa, consulte el Seguimiento de objetivos del agente (disponible en el BI del Gestor de agentes). Para el desglose completo, consulte el Creador de informes.",
        "DB_KpiTooltip_TotalInteractiveChats": "Número de interacción interactivos completados. &#13; Una interacción se vuelve bilateral cuando el visitante introduce el texto.",
        "DB_KpiTooltip_AverageEngagementTime": "Promedio de tiempo desde que el visitante se conecta al agente, hasta que se cierra la ventana de la interacción:&#13;(tiempo total simultáneo interactuando) / (número de interacciones bilaterales.",
        "DB_KpiTooltip_Utilization": "Capacidad utilizada del agente, incluidas interacciones simultáneas:&#13;(Tiempo total de interacción simultánea) / (tiempo total con sesión iniciada * Número máximo de chats simultáneos permitidos).",
        "DB_KpiTooltip_interEngPerHour": "Promedio de campañas bilaterales gestionadas durante el tiempo en línea o interactuando:&#13;(Número de interacciones bilaterales) / (tiempo \"en línea\" + tiempo \"ausente\" interactuando + tiempo \"vuelvo en seguida\" interactuando).",
        "DB_KpiTooltip_Csat": "Puntuación de satisfacción del cliente, según el cuestionario post chat:&#13;(Número total de respuestas positivas) / (Número total de respuestas).",
        "DB_KpiTooltip_AbandonmentRate": "Porcentaje de visitantes que abandonaron la cola de todos los visitantes que están en la cola.",
        "DB_KpiTooltip_ConnectedEng": "Número de interacciones donde los visitantes conectaron con agentes.",
        "DB_KpiTooltip_AbandonedEng": "Número de visitantes que abandonaron la cola antes de conectar con los agentes.",
        "DB_KpiTooltip_AvgTimeToAnswer": "Promedio de tiempo desde que los visitantes estaban en la cola hasta que conectaron con agentes.",
        "DB_KpiTooltip_CurrentQueueSize": "Número de chats por habilidades que están esperando actualmente en la cola y no han sido respondidos por un agente.",
        "DB_KpiTooltip_AvgTimeToAbandon": "Promedio de tiempo desde cuando los visitantes estaban en la cola hasta que la abandonaron.",
        "DB_KpiTooltip_GUEST_SitesVisitsObserved": "Número de visitas en todos los sitios Web de cliente de LivePerson (por mes).",
        "DB_KpiTooltip_GUEST_LiveChats" : "Número de chats en todos los sitios Web de cliente de LivePerson (por mes).",
        "DB_KpiTooltip_GUEST_Conversions" : "% de aumento de conversión mensual en todos los sitios Web de cliente de LivePerson.",
        "DB_KpiTooltip_GUEST_AvgOrderValues" : "% de aumento del valor de pedidos mensual en todos los sitios Web de cliente de LivePerson.",
        "DB_KpiTooltip_AGENT_LIST_AgentsOnline": "Agentes en línea",
        "DB_KpiTooltip_AGENT_LIST_AgentsBackSoon": "Agentes que vuelven en seguida",
        "DB_KpiTooltip_AGENT_LIST_AgentsAway": "Agentes ausentes",
        "DB_KpiTooltip_AGENT_LIST_ConcurrentChats": "Número total de chats actuales.",
        "DB_KpiTooltip_AGENT_LIST_MaxChats": "Número total de chats simultáneos máximos que todos los agentes en línea pueden gestionar.",
        "DB_KpiTooltip_HOT_TOPICS_TotalChatsAnalyzed": "Total chats analizados.",
        "DB_KpiTooltip_HOT_TOPICS_ChatsWithSentiment": "Los chats totales que contienen al menos un Tema candente, de todos los chats analizados. Un chat puede contener temas positivos y negativos.",
        "DB_KpiTooltip_HOT_TOPICS_PositiveSentiment": "Porcentaje de chats con sentimiento positivo.",
        "DB_KpiTooltip_HOT_TOPICS_NegativeSentiment": "Porcentaje de chats con sentimiento negativo.",
        "DB_KpiTooltip_MY_CONNECTIONS_active": "Número de conversaciones actuales abiertas.",
        "DB_KpiTooltip_MY_CONNECTIONS_pending": "Número de conversaciones donde la respuesta está pendiente.",
        "DB_KpiTooltip_MY_CONNECTIONS_unassigned": "Número de conversaciones no asignadas, esperando asignación.",
        "DB_KpiTooltip_MY_CONNECTIONS_overdue": "Número de conversaciones pendientes que superaron el tiempo de respuesta objetivo.",
        "DB_KpiTooltip_MY_CONNECTIONS_actionable": "Las conversaciones accionables son aquellas en la cola que están pendientes de una respuesta inmediata del agente.",
        "DB_KpiTooltip_MY_CONNECTIONS_inQueue": "El número de conversaciones en la cola que están esperando una asignación del agente.",
        "DB_KpiTooltip_MY_CONNECTIONS_soonToOverdue": "Número de conexiones pendientes que están a punto de superar su tiempo de respuesta objetivo.",
        "DB_KpiTooltip_MY_CONNECTIONS_CSAT": "Puntuación de Satisfacción del cliente, basado en el cuestionario: (Número total de respuestas positivas)/(Número total de respuestas).",

        // Cross Session additions
        "DB_Tooltip_CrossSession_Conversions": "Incluye conversiones en sesión y entre sesiones.",
        "DB_Tooltip_CrossSession_Revenue": "Incluye ingresos en sesión y entre sesiones.",
        "DB_WidgetTooltip_goalReachedPerGoalType_CrossSession": "<br>Los objetivos de conversión incluyen conversiones en sesión y entre sesiones.",
        "DB_WidgetTooltip_aov_CrossSession": "<br>Incluye AOV en sesión y entre sesiones.",
        "DB_WidgetTooltip_conversionRate_CrossSession": "Tasas de conversión de diferentes canales (incluye conversiones en sesión y entre sesiones):<br>Tasa de conversión de chat - Tasa de conversión tras chat interactivo.<br>Tasa de contenido (VTC) - Tasa de conversión tras exposición a contenido.<br>Tasa de contenido (CTC) - Tasa de conversión tras clics de contenido.<br>Tasa de conversión de grupo de control - Tasa de conversión del grupo de control.",

        "DB_StatusTooltip_Error_first": "No se pudieron actualizar los datos.",
        "DB_StatusTooltip_Error_second": "Este problema se resolverá en unos minutos.",
        "DB_StatusTooltip_Network_Error_first": "No se pudieron actualizar los datos automáticamente.",
        "DB_StatusTooltip_Network_Error_second": "Para actualizar los datos, actualice el navegador.",
        "DB_StatusTooltip_Success_LastUpdate": "Última actualización",
        "DB_StatusTooltip_Success_RefreshRate": "Intervalo de actualización",
        "DB_StatusTooltip_Success_CalcEvery": "Cálculos cada",
        "DB_StatusTooltip_Success_TimeFrame": "Periodo",
        "DB_StatusTooltip_Success_Csat_TimeFrame": "Periodo de tiempo CSAT KPI",
        "DB_StatusTooltip_Success_EngagementHistory": "Los datos de la interacción están disponibles en un plazo de cinco minutes del cierre de la ventana Interacción.",
        "DB_StatusTooltip_Success_AllConnections": "Los datos de la conversación están disponibles casi en tiempo real.",

        "DB_goalTypesName_increase_page_views": "Aumentar visitas a página",
        "DB_goalTypesName_sell_product/service": "Vender producto o servicio",
        "DB_goalTypesName_generate_leads": "Generar clientes potenciales",
        "DB_goalTypesName_other": "Otro",
        "DB_goalTypesName_none": "No asignado",
        "DB_goalTypesName_n/a": "N/A",
        "DB_goalTypesName_service_activity_complete": "Actividad del servicio completa",
        "DB_goalTypesName_interact_with_visitors": "Interactuar con visitantes",

        // Hot Topics Dashboard
        "DB_HotTopics_Title": "Desglose de temas candentes",
        "DB_HotTopics_Description": "Temas de conversación más frecuentes con sentimiento negativo o positivo.",
        "DB_HotTopics_Loading": "Analizando su chat, ¡estaremos con usted enseguida!",
        "DB_HotTopics_HotTopicItem_Mentions": "{0} de {1}",
        "DB_HotTopics_EmptySentiment_Header": "No se encontraron ningún tema {0}",
        "DB_HotTopics_EmptySentiment_Description": "en los chats analizados",
        "DB_HotTopics_EmptySentiment_Positive": "positivo",
        "DB_HotTopics_EmptySentiment_Negative": "negativo",
        "DB_HotTopics_ParticipantsFilter_Title": "Participantes del chat",
        "DB_HotTopics_TopicInfo_Title": "Información del tema:",
        "DB_HotTopics_TopicInfo_NegativeMentions": "Referencias negativas",
        "DB_HotTopics_TopicInfo_PositiveMentions": "Referencias positivas",
        "DB_HotTopics_TopicInfo_SnippetsTitle": "Snippets de la interacción",
        "DB_HotTopics_TopicInfo_ViewAll": "Ver todas las",
        "DB_HotTopics_agent": "Agente",
        "DB_HotTopics_visitor": "Visitante",
        "DB_HotTopics_both": "Ambas",
        "DB_HotTopics_mentions": "menciones",
        "DB_HotTopics_positive": "positivo",
        "DB_HotTopics_negative": "negativo",
        "DB_HotTopics_DashboardHandle_Tooltip": "Para obtener más información, abra el informe Tema candente",

        "SECOND": "segundo",
        "SECONDS": "segundos",
        "MINUTE": "minuto",
        "MINUTES": "minutos",
        "HOUR": "hora",
        "HOURS": "horas",
        "hour_short": "hr",
        "minute_short": "mín",
        "second_short": "seg",
        "AM": "AM",
        "PM": "PM",
        "Current_State": "Estado actual",

        "last": "Último",
        "ago": "hace",
        "total": "Total",

        "mock.dashboard.upgrade": "Actualice para acceder a nuestros paneles de control de Business Intelligence",
        "mock.dashboard.unlock": "Desbloquear más datos",
        "mock.dashboard.engagement": "Sus clientes esperan un alto nivel de servicio. Realice un seguimiento de su rendimiento a través de tendencias de métricas como proporción de respuestas, tiempos de espera y más.",
        "mock.dashboard.agent": "Comprenda el rendimiento de sus agentes: vea las métricas de eficiencia y las medidas de conversión por agente o grupos de agentes.",
        "mock.dashboard.campaign": "Vea exactamente cuántos ingresos incrementales está consiguiendo a partir de su programa de interacción.",
        "mock.dashboard.bi.title": "¡Nuevo! Creador de informes",
        "mock.dashboard.bi.description": "Disfrute de una mejor personalización y análisis de datos con nuestra nueva herramienta de creación de informes",
        "mock.dashboard.bi.continueBtn": "Continuar a BI",
        "mock.dashboard.bi.reportBuilderBtn": "Ir al Creador de informes",

        "intent.dashboard.noaccess.title": "LIVEINTENT",
        "intent.dashboard.noaccess.description.trends": "Profundice en el nivel de la conversación para orientación en tiempo real",
        "intent.dashboard.noaccess.description.msc": "Comprenda el tiempo que sus agentes pasan por intención",
        "intent.dashboard.noaccess.description.intents": "Monitorice las intenciones de sus clientes en tiempo real",
        "intent.dashboard.noaccess.description.main": "¡Aprenda mucho más de sus conversaciones! Póngase en contacto con nosotros para obtener sus paneles de control inteligentes y basados en la intención.",
        "intent.dashboard.noaccess.close": "Más tarde",
        "intent.dashboard.noaccess.contact": "Contacte con nosotros",
        "intent.dashboard.noAccessSubject": "Habilitar el Panel de control de LiveIntent",
        "intent.dashboard.noAccessBody": "Hola, estoy interesado en habilitar el Panel de control de LiveIntent como parte de la Suite de Inteligencia de la Conversación. Gracias"
    };

    return Dictionary;
});
