/**
 * Created with IntelliJ IDEA.
 * User: omerh
 * Date: 3/20/13
 * Time: 5:42 PM
 * To change this template use File | Settings | File Templates.
 */
define(function () {
    "use strict";

    var Dictionary = {
        "language": "es-ES",
        // pay attention that every key should start with the module name and then the key name
        //content  edit
        "content.edit.canned.text.new.title":  "Añadir nueva respuesta predefinida",
        "content.edit.canned.text.new.description":  "Añadir respuestas predefinidas en múltiples idiomas a su biblioteca de contenidos",

        "content.edit.canned.text.edit.title": "Administrar el contenido predefinido",
        "content.edit.canned.text.edit.description":  "Añadir/modificar el contenido predefinido para sus idiomas seleccionados.",

        "content.edit.system.edit.title": "Modificar mensaje automático",
        "content.edit.system.edit.description":  "Añadir los mensajes automáticos traducidos a su biblioteca de contenido.",
        "content.edit.system.edit.name.sentence.before.name":  "El siguiente mensaje automático se enviará al visitante cuando:",

        "content.edit.system.timed.edit.title": "Editar respuesta automática en espera",
        "content.edit.system.timed.edit.description":  "El Mensaje automático se envía en la situación descrita a continuación y tras el tiempo indicado.",
        "content.edit.system.timed.name.sentence.before.name":  "En el caso de",
        "content.edit.system.timed.before.name.sentence":  "El siguiente mensaje automático se enviará al visitante:",
        "content.edit.system.timed.name.sentence.after.name":  ", este mensaje automático se enviará al visitante tras",
        "content.edit.system.timed.name.sentence.after.timer.field":   "segundos:",
        "content.edit.system.timed.name.sentence.after.name1":  "Este mensaje automático se enviará al visitante tras",
        "content.edit.system.timed.name.sentence.after.timer.field1":   "segundos.",

        "content.edit.system.timer.label": "Tiempo del evento:",
        "content.edit.system.timer.before.field":  "El mensaje se enviará tras",
        "content.edit.system.timer.after.field":   "segundos en espera",
        "content.edit.system.event.name.label":   "Evento:",
        "content.edit.system.timer.unit.seconds":   "Segundos",
        "content.edit.system.timer.unit.minutes":   "Minutos",
        "content.edit.system.timer.unit.hours":   "Horas",

        "content.edit.save.and.add.button": "Guardar y añadir otra",
        "content.edit.languageBar.label": "Puede añadir textos traduciros o HTML en los siguientes idiomas:",
        "content.edit.languageBar.label.note": "Nota: HTML es solo compatible con chat.",
        "content.edit.languageBar.label.messaging": "Puede añadir textos traduciros en los siguientes idiomas:",
        "content.edit.skillBar.label": "Una variación de este mensaje está disponible para:",
        "content.edit.languageBar.placeholder": "Para personalizar el mensaje, introduzca su texto aquí. Si no se introduce ningún texto, el consumidor recibirá el texto predeterminado para este idioma.",

        "content.edit.editor.title.label": "Título:",
        "content.edit.editor.text.label" : "Texto:",
        "content.edit.editor.restore.defaults.confirm.button" : "Restaurar el texto a predeterminado",
        "content.edit.editor.restore.defaults.tooltip" : "Revierte todos los textos a los textos originales predeterminados.",
        "content.edit.editor.canned.restore.defaults.confirm.msg" : "Restaurar los valores predeterminados tiene implicaciones para todos los idiomas:<br/><br/>- El contenido predefinido modificado volverá al texto original.<br/>- Se eliminarán todos los textos del nuevo contenido predefinido.",
        "content.edit.editor.system.restore.defaults.confirm.msg" : "Restaurar los valores predeterminados tiene implicaciones para todos los idiomas:<br/><br/>- Todos los mensajes modificados volverán al texto original.<br/>- Se eliminarán todos los idiomas añadidos, y sólo se conservarán los textos traducidos proporcionados por LiveEngage.",


        "content.edit.categories.label" : "Categorías:",
        "content.edit.categories.label.tooltip" : "Seleccione y cree categorías para organizar su contenido predefinido.",
        "content.edit.categories.multiselect.placeholder" : "Añadir categoría",
        "content.edit.categories.multiselect.create" : "Nueva categoría",
        "content.edit.categories.multiselect.create.length.error" : "La longitud de la categoría debe tener entre 1 y 50 caracteres.",

        "content.edit.skills.label" : "Habilidades:",
        "content.edit.skills.label.tooltip" : "Seleccione las habilidades para organizar su Contenido predefinido.",
        "content.edit.skills.multiselect.placeholder" : "Seleccionar habilidad",
        "content.edit.skills.mismatch.tooltip" : "Las habilidades no coinciden con las líneas de negocio asignadas.",

        "content.edit.lobs.label" : "Líneas de negocio:",
        "content.edit.lobs.label.tooltip" : "Seleccione las líneas de negocio para organizar su Contenido predefinido.",
        "content.edit.lobs.multiselect.placeholder" : "Seleccionar líneas de negocio",

        "content.edit.hotkeys.label" : "Combinación de teclas de acceso directo disponibles:",
        "content.edit.hotkeys.label.tooltip" : "Asigne una combinación de teclas de acceso directo, de una letra y un número, para el contenido predefinido.&#13;Las combinaciones de teclas de acceso directo que ya están siendo usadas, no se muestran en la lista.&#13;Seleccione el caracter \"-\" para eliminar la combinación de este elemento de contenido.",
        "content.edit.hotkeys.arrows.tooltip" : "Flecha derecha en el teclado",
        "content.edit.hotkeys.right.arrow.text" : "Tecla de flecha derecha",
        "content.edit.hotkeys.letter.selection.placeholder" : "A-Z",
        "content.edit.hotkeys.number.selection.placeholder" : "0-9",
        "content.edit.errors.hotkeys.taken.msg" : "La combinación de teclas de acceso directo seleccionada ya está en uso.",
        "content.edit.errors.hotkeys.suggestion.msg" :  "Otras combinaciones que puede usar:",
        "content.edit.errors.hotkeys.partial.msg" :  "Las combinaciones de teclas de acceso directo deben ser de una letra y un número.<br/><br/>Asegúrese de definir ambos.",
        "content.edit.errors.missing.deleted.msg" :  "El contenido predefinido seleccionado ya no existe.",
        "content.edit.errors.remove.last.content.msg" :  "Para guardar este contenido predefinido, debe introducir contenido para al menos uno de los idiomas seleccionados.",
        "content.edit.errors.contentMaxCharacters" :  "El contenido predefinido ha superado el límite de {0} caracteres",
        "content.errors.max.number.of.actions" :  "Ha alcanzado el número máximo de acciones permitidas. Póngase en contacto con un representante de LivePerson para obtener ayuda.",
        "content.errors.max.entity.count" :  "Ha alcanzado el número máximo de elementos de Contenido predefinido. Intente eliminar los elementos no usados para añadir nuevos.",

        "content.edit.activation.button.tooltip.enabled": "Contenido habilitado",
        "content.edit.activation.button.tooltip.disabled": "Contenido deshabilitado",

        "content.edit.preview.label" : "Vista previa:",
        "content.edit.preview.label.tooltip" : "Previsualice el contenido en la Ventana de interacciones de muestra, a medida que escribe.",

        "content.edit.save.no-changes.tooltip": "No se han realizado cambios.",
        "content.edit.save.no-timer.tooltip": "El campo Tiempo está vacío.",
        "content.edit.canned.save.empty.tooltip":  "Los campos Título y Texto requieren texto.",
        "content.edit.system.save.empty.tooltip":  "El campo Texto requiere texto.",
        "content.edit.system.save.msgMaxLength.tooltip": "Ha superado el número máximo de caracteres permitidos con los siguientes idiomas: <br/> {0}",
        "content.edit.route.confirmation.msg": "Tiene cambios que no ha guardado.<br/>¿Qué le gustaría hacer antes de continuar?",
        "content.edit.delete.confirmation.title": "Eliminar personalización",
        "content.edit.delete.confirmation.msg": "Está a punto de eliminar la personalización para esta habilidad.<br/>¿Seguro que desea continuar?",
        "content.edit.route.confirmation.save": "Guardar cambios",
        "content.edit.route.confirmation.dont.save": "No guardar",
        "content.edit.canned.no-title.available.label":   "- No definido -",
        "content.edit.canned.no-title.available.tooltip": "El título no ha sido definido para el idioma de interfaz o el idioma de la interacción predeterminado.",

        "content.edit.add.languages.tab.tooltip": "Añadir idioma de la interacción",
        "content.edit.add.skill.tab.tooltip": "Añadir habilidades para las que personalizar este mensaje",
        "content.edit.all.skills.tab.tooltip": "Todas las habilidades (predeterminado)",
        "content.edit.remaining.skills.tab.tooltip": "Habilidades restantes (predeterminadas)",
        "content.edit.restore.default.tooltip": "Revierte a los textos originales predeterminados.",
        "content.edit.delete.tooltip": "Eliminar personalización",
        "content.edit.create.data.error": "No hemos podido crear este elemento. Inténtelo de nuevo más tarde.",
        "content.edit.get.data.error": "No hemos podido editar este elemento. Inténtelo de nuevo más tarde.",
        "content.edit.save.auto.message.error": "No hemos podido guardar este mensaje. Inténtelo de nuevo más tarde.",
        "content.edit.delete.auto.message.error": "No hemos podido eliminar este elemento. Inténtelo de nuevo más tarde.",
        "content.edit.409.error": "Este mensaje ha sido actualizado por otro usuario; por favor, vuelva a abrirlo e inténtelo de nuevo.",

        //content  list
        "content.gallery.title":  "Biblioteca de contenidos",
        "content.gallery.add.new.button":  "Añadir contenido",
        "content.gallery.description":  "En esta página puede añadir o editar cualquier tipo de contenido que tenga en la biblioteca de contenidos.",
        "content.gallery.action.newcontent.item.text": "Añadir texto",
        "content.gallery.action.newcontent.tooltip.text": "Añadir nuevo contenido",
        "content.gallery.action.newcontent.item.video": "Añadir vídeo",
        "content.gallery.action.newcontent.tooltip.video": "Añadir contenido de tipo vídeo",

        "content.gallery.menu.action.manageCategories": "Gestionar categorías",
        "content.gallery.menu.action.manageCategories.tooltip": "Gestionar categorías",
        "content.gallery.menu.action.assignSkills": "Asignar habilidades",
        "content.gallery.menu.action.assignSkills.tooltip": "Asignar habilidades al contenido predefinido seleccionado.",
        "content.gallery.menu.action.export": "Exportar",
        "content.gallery.menu.action.export.tooltip": "Exportar lista de contenido predefinido",
        "content.gallery.menu.action.legacy.export": "Exportar desde la Plataforma Core",
        "content.gallery.menu.action.legacy.export.tooltip": "Exportar lista de contenido predefinido desde Plataforma Core.",
        "content.gallery.menu.action.edit.tooltip":   "Modificar contenido",
        "content.gallery.menu.action.delete.tooltip": "Eliminar contenido",
        "content.gallery.menu.action.import": "Importar",
        "content.gallery.menu.action.import.tooltip": "Importar contenido desde archivo CSV",

        "content.action.export.start": "Exportando contenido predefinido.",
        "content.action.legacy.export.start": "Exportando contenido predefinido desde Plataforma Core.",
        "content.action.export.error": "Error de exportación. Inténtelo de nuevo.",

        "content.gallery.canned.title":        "Biblioteca de contenido predefinido",
        "content.gallery.canned.description":  "Añada y modifique el contenido predefinido para mejorar la eficiencia del agente cuando se correspondan con los visitantes.",
        "content.gallery.canned.kp.text":  "Más información",

        "content.gallery.canned.assignSkills.selected":  "se seleccionaron habilidades",
        "content.gallery.canned.assignSkills.text":  "Asignar habilidades al contenido predefinido seleccionado:",
        "content.gallery.canned.assignSkills.tooltip":  "En los casos en los que el contenido predefinido comparta habilidades comunes, la habilidad o habilidades compartidas aparecerán en el siguiente campo.",
        "content.gallery.canned.assignSkills.multiSelect.placeholder" : "Añadir habilidad",
        "content.gallery.assignSkills.multiSelect.placeholder" : "Habilidades...",
        "content.gallery.canned.assignSkills.error" : "Se ha producido un problema al asignar las habilidades el contenido predefinido seleccionado. Inténtelo de nuevo más tarde.",
        "content.gallery.canned.assignSkills.fetchData.error" : "La acción solicitada ha fallado. Inténtelo de nuevo.",

        "content.gallery.system.title":         "Biblioteca de mensajes automáticos",
        "content.gallery.system.description":   "Modificar los mensajes automáticos generados por el sistema. Estos mensajes mejoran la experiencia del visitante proporcionando información contextual.",
        "content.gallery.system.assignSkills.text":  "Seleccionar habilidades para las que personalizar este mensajeЬ",
        "content.gallery.system.unsave.changes.text":  "Tiene personalizaciones no guardadas de este mensaje. ¿Qué le gustaría hacer antes de continuar?",
        "content.gallery.system.button.disabled":  "El mensaje se ha personalizado para todas las habilidades disponibles en la cuenta.",

        "content.contentTable.type.columnHeader": "Tipo",
        "content.contentTable.status.columnHeader": "Estado",
        "content.contentTable.status.columnHeader.tooltip": "Estado del contenido / mensaje y si está disponible para su uso.",
        "content.contentTable.name.columnHeader": "Nombre",
        "content.contentTable.name.columnHeader.tooltip": "Nombre del contenido/mensaje.",
        "content.contentTable.categories.columnHeader": "Categorías",
        "content.contentTable.categories.columnHeader.tooltip": "Los grupos definidos donde se categorizó el contenido predefinido.",
        "content.contentTable.languages.columnHeader":  "Idiomas",
        "content.contentTable.languages.columnHeader.tooltip":  "El idioma(s) del contenido/mensaje se ha traducido a.",
        "content.contentTable.hotkeys.columnHeader":  "Teclas de acceso directo", //// MYWORD_COMPANY_LENGTH_10
        "content.contentTable.hotkeys.columnHeader.tooltip":  "Accesos directos definidos para introducir contenido predefinido en los chats.",
        "content.contentTable.lobs.columnHeader":  "Líneas de negocio",
        "content.contentTable.lobs.columnHeader.tooltip":  "La línea/s de negocio asociada con el Contenido predefinido",
        "content.contentTable.skills.columnHeader":  "Habilidades",
        "content.contentTable.skills.columnHeader.tooltip":  "La habilidad asociada con el Contenido predefinido. Solo el Contenido predefinido que está asociado con la habilidad de la interacción se mostrará en el Espacio de trabajo del agente.",
        "content.contentTable.variation.skills.columnHeader":  "Variación para habilidad",
        "content.contentTable.variation.skills.columnHeader.tooltip":  "Las habilidades para las cuales se personaliza el mensaje.",


        "content.contentTable.status.enabled": "Activa",
        "content.contentTable.status.disabled": "Inactivos",
        "content.contentTable.status.multiple": "Múltiple",

        "content.table.delete.confirm.title": "Eliminar el contenido predefinido",
        "content.table.delete.confirm.text":  "Está a punto de eliminar este contenido predefinido. Una vez eliminado, no estará disponible para que sus agentes lo utilicen.",
        "content.table.delete.error.title":   "Problema al eliminar el contenido predefinido.",
        "content.table.delete.error.text":    "No se puede eliminar el contenido predefinido.",

        "content.system.tab.chat.title": "Chat en vivo",
        "content.system.tab.messaging.title": "Mensajería",

        "content.system.event.CHAT_DUMPED.name":                        "Interacción desconectado",
        "content.system.event.CHAT_TERMINATED.name":                    "Interacción desconectada por agente",
        "content.system.event.CHAT_WITH.name":                          "El agente acepta la interacción",
        "content.system.event.NO_CHAT_SESSION.name":                    "Interacción de chat no en progreso",
        "content.system.event.MSG_ALL_OPERATORS_UNAVAILABLE.name":      "Agentes de chat no disponibles actualmente",
        "content.system.event.WAITING_CHAT.name":                       "Redirigiendo chat a agente",
        "content.system.event.MSG_ALL_OPERATORS_BUSY.name":             "Esperando a un agente disponible",
        "content.system.event.MSG_SYSTEM_TRANSFER_TO_SKILL.name":       "Interacción puesta en cola por el sistema",
        "content.system.event.MSG_EMAIL_TRANSCRIPT_REQUEST.name":       "Copia de chat solicitada por visitante",
        "content.system.event.MSG_TRANSFER_TO_SKILL.name":              "Interacción transferida a una habilidad diferente",
        "content.system.event.MSG_TRANSFER_AFTER_REP_DISCONNECT.name":  "Interacción transferida debido a desconexión del agente",
        "content.system.event.MSG_WAIT_FOR_TRANSFER.name":              "Interacción transferida a un agente diferente",
        "content.system.event.MSG_STALLER_0.name":                      "Mensaje de espera nº 1",
        "content.system.event.MSG_STALLER_1.name":                      "Mensaje de espera nº 2",
        "content.system.event.MSG_STALLER_2.name":                      "Mensaje de espera nº 3",
        "content.system.event.MSG_YOU_IN_SELECTED_LANGUAGE.name":       "Nombre del visitante (si no se ha facilitado)",
        "content.system.event.MSG_INCORRECT_EMAIL.name":                "Se ha introducido una dirección de correo no válida",
        "content.system.event.MSG_INFO.name":                           "Nombre del sistema (para mensajes automáticos)",
        "content.system.event.MSG_NONRESPONSIVE_FAIR_WARNING.name":     "Aviso justo de no respuesta",
        "content.system.event.MSG_NONRESPONSIVE_FINAL_WARNING.name":    "Aviso final de no respuesta",

        "content.system.edit.event.CHAT_DUMPED.name":                        "Interacción desconectado",
        "content.system.edit.event.CHAT_TERMINATED.name":                    "Interacción desconectada por agente",
        "content.system.edit.event.CHAT_WITH.name":                          "El agente acepta la interacción",
        "content.system.edit.event.NO_CHAT_SESSION.name":                    "Interacción de chat no en progreso",
        "content.system.edit.event.MSG_ALL_OPERATORS_UNAVAILABLE.name":      "Agentes de chat no disponibles actualmente",
        "content.system.edit.event.WAITING_CHAT.name":                       "Redirigiendo chat a agente",
        "content.system.edit.event.MSG_ALL_OPERATORS_BUSY.name":             "Esperando a un agente disponible",
        "content.system.edit.event.MSG_SYSTEM_TRANSFER_TO_SKILL.name":       "Interacción puesta en cola por el sistema",
        "content.system.edit.event.MSG_EMAIL_TRANSCRIPT_REQUEST.name":       "Copia de chat solicitada por visitante",
        "content.system.edit.event.MSG_TRANSFER_TO_SKILL.name":              "Interacción transferida a una habilidad diferente",
        "content.system.edit.event.MSG_TRANSFER_AFTER_REP_DISCONNECT.name":  "Interacción transferida debido a desconexión del agente",
        "content.system.edit.event.MSG_WAIT_FOR_TRANSFER.name":              "Interacción transferido a un agente diferente",
        "content.system.edit.event.MSG_STALLER_0.name":                      "cuando el Agente no responda (mensaje nº 1)",
        "content.system.edit.event.MSG_STALLER_1.name":                      "cuando el Agente no responda (mensaje nº 2)",
        "content.system.edit.event.MSG_STALLER_2.name":                      "cuando el Agente no responda (mensaje nº 3)",
        "content.system.edit.event.MSG_YOU_IN_SELECTED_LANGUAGE.name":       "Nombre del visitante (si no se ha facilitado)",
        "content.system.edit.event.MSG_INCORRECT_EMAIL.name":                "Se ha introducido una dirección de correo no válida",
        "content.system.edit.event.MSG_INFO.name":                           "Nombre del sistema (para mensajes automáticos)",
        "content.system.edit.event.MSG_NONRESPONSIVE_FAIR_WARNING.name":     "En el caso de un chat no reactivo (Aviso razonable)",
        "content.system.edit.event.MSG_NONRESPONSIVE_FINAL_WARNING.name":    "En el caso de un chat no reactivo (Aviso final)",


        "content.errors.system.onhold.range": "Segundos en espera: {0} - {1}",
        "content.errors.canned.msg.empty" :  "El mensaje no puede estar vacío",
        "content.errors.canned.title.empty": "El título no puede estar vacío",
        "content.errors.system.msg.empty" :  "El mensaje no puede estar vacío",

        "content.macros.placeholder":           "Añadir texto dinámico",
        //system messages:
        "content.macros.name":              "Nombre del agente",
        "content.macros.email":             "Dirección de correo del visitante",
        "content.macros.AvgWaitSeconds":    "Promedio tiempo espera (seg)",
        "content.macros.AvgWaitMinutes":    "Promedio tiempo espera (min)",
        "content.macros.QueueLength":       "Longitud de cola",
        "content.macros.PlaceInQ":          "Lugar en la cola",
        "content.macros.name.tooltip":              "El nombre para mostrar del agente como se ha introducido en su perfil de usuario.",
        "content.macros.email.tooltip":             "La dirección de correo electrónico del visitante. Si no hay dirección de correo electrónico, el texto predeterminado será \"Su dirección de correo\".",
        "content.macros.AvgWaitSeconds.tooltip":    "El promedio de tiempo en segundos que un visitante espera en la cola antes de ser conectado con un agente.",
        "content.macros.AvgWaitMinutes.tooltip":    "El promedio de tiempo en minutos que un visitante espera en la cola antes de ser conectado con un agente.",
        "content.macros.QueueLength.tooltip":       "El número actual de chats en la cola.",
        "content.macros.PlaceInQ.tooltip":          "El lugar actual de un visitante en la cola.",
        "content.macros.name.example":              "Kelly",
        "content.macros.email.example":             "John@Consumer.com",
        "content.macros.AvgWaitSeconds.example":    "30",
        "content.macros.AvgWaitMinutes.example":    "0",
        "content.macros.QueueLength.example":       "5",
        "content.macros.PlaceInQ.example":          "3",
        //system messaging
        "content.macros.expectedResponseTime": "Tiempo de respuesta esperado",
        "content.macros.expectedResponseTime.tooltip": "El periodo de tiempo configurado para que un agente responda al mensaje de un consumidor",
        "content.macros.nextWorkingHoursTimestamp": "Sello de tiempo de horas de trabajo",
        "content.macros.nextWorkingHoursTimestamp.tooltip": "El horario de apertura del centro de contacto",
        "content.macros.expectedResponseTimestamp": "Sello de tiempo de respuesta esperada",
        "content.macros.expectedResponseTimestamp.tooltip": "El tiempo configurado para que un agente responda al mensaje de un consumidor",
        "content.macros.consumerName": "Nombre del consumidor",
        "content.macros.consumerName.tooltip": "El nombre del consumidor como se ha pasado en un atributo de interacción",
        "content.macros.agentNickname": "Apodo del agente",
        "content.macros.agentNickname.tooltip": "El nombre para mostrar del agente como se ha introducido en su perfil de usuario.",
        "content.macros.skillName": "Nombre de habilidad",
        "content.macros.skillName.tooltip": "El nombre de la habilidad a la que ha sido transferida la conversación",
        //canned responses:
        "content.macros.skill.name":            "Nombre de habilidad",
        "content.macros.skill.description":     "Descripción de habilidad",
        "content.macros.operator.displayname":  "Nombre del agente",
        "content.macros.operator.nickname":     "Apodo del agente",
        "content.macros.operator.email":        "Correo electrónico del agente",
        "content.macros.skill.name.tooltip":            "El nombre de la habilidad como se ha introducido en el área de Administración de usuario.",
        "content.macros.skill.description.tooltip":     "La descripción de la habilidad como se ha introducido en el área de Administración de usuario.",
        "content.macros.operator.displayname.tooltip":  "El nombre para mostrar del agente como se ha introducido en su perfil de usuario.",
        "content.macros.operator.nickname.tooltip":     "El apodo del agente como se ha introducido en su perfil de usuario. Si no hay apodo, el valor predeterminado será el nombre del agente.",
        "content.macros.operator.email.tooltip":        "El correo electrónico del agente como se ha introducido en su perfil de usuario.",
        "content.macros.skill.name.example":            "Envío",
        "content.macros.skill.description.example":     "Enviamos a cualquier ubicación de EE.UU y a múltiples ubicaciones internacionales",
        "content.macros.operator.displayname.example":  "Kelly",
        "content.macros.operator.nickname.example":     "Kelly",
        "content.macros.operator.email.example":        "Kelly@Company.com",

        "content.import.header": "Importar contenido",
        "content.import.description": "Importar su contenido predefinido desde un archivo externo. Esto hace que la edición sea más sencilla en todos los idiomas compatibles.",
        "content.import.kpCaption": "Más información",
        "content.import.note": "Tenga en cuenta que los elementos existentes serán sustituidos por los nuevos elementos importados.",
        "content.import.button.import": "Importar",
        "content.import.button.import.disabledTooltip": "No se seleccionó archivo",
        "content.import.instructions.step1.1": "Puede descargar una plantilla vacía ",
        "content.import.instructions.step1.linkText.template": "aquí",
        "content.import.instructions.step1.2": ", o su contenido actual, ",
        "content.import.instructions.step1.linkText.content": "aquí",
        "content.import.instructions.step1.3": ".",
        "content.import.instructions.step2.1": "Seleccione un archivo para subir (el tipo de archivo compatible es CSV).",
        "content.import.instructions.step2.2": "Se descargará automáticamente un archivo de copia de seguridad con los elementos actuales.",
        "content.import.instructions.step2.buttonText.chooseFile": "Elegir archivo...",

        "content.import.loader.upload.text": "Importación de Contenido predefinido en progreso",
        "content.import.loader.upload.buttonText": "Ejecutar en segundo plano",
        "content.import.loader.upload.buttonTooltip": "Importar datos en segundo plano y continúe usando LiveEngage",

        "content.import.notification.topBar.progress": "Importación de Contenido predefinido en progreso.",
        "content.import.notification.topBar.success": "{0} Contenido predefinido {1} importado correctamente. Haga clic para ver la lista de Contenido predefinido actualizada.",
        "content.import.notification.topBar.success.singular": "el elemento fue",
        "content.import.notification.topBar.success.plural": "los elementos fueron",
        "content.import.notification.topBar.error": "Ha fallado la importación de Contenido predefinido. Haga clic para ver más detalles.",

        "content.import.notification.success": "{0} Contenido predefinido {1}importado correctamente.<br /><br />Nota: cualquier categoría recién importada y sus elementos relacionados no son visibles a los agentes por defecto.",
        "content.import.notification.success.singular": "el elemento fue",
        "content.import.notification.success.plural": "los elementos fueron",
        "content.import.notification.error": "Se ha producido un problema al cargar el archivo. Inténtelo de nuevo.",
        "content.import.notification.error.refer.afterUpload": "Se ha producido un problema al cargar el archivo. Consulte el siguiente error para obtener más información.",
        "content.import.notification.error.refer.beforeUpload": "Se ha producido un problema con el archivo seleccionado. Consulte el siguiente error para obtener más información.",

        // content related errors
        "content.import.serverError.unknownError": "Se ha producido un problema al importar el Contenido predefinido",
        "content.import.serverError.5": "El nombre de la categoría supera el límite de {0} caracteres o contiene caracteres no permitidos",
        "content.import.serverError.100": "Cambie el nombre de la categoría",
        "content.import.serverError.104":  "Ha alcanzado el número máximo de elementos de Contenido predefinido. Intente eliminar los elementos no usados para añadir nuevos.",
        "content.import.serverError.107":  "Ha alcanzado el número máximo de acciones permitidas. Póngase en contacto con un representante de LivePerson para obtener ayuda.",
        "content.import.serverError.200": "Falta {0}",
        "content.import.serverError.201": "No permitido {0}, este valor debe ser un número",
        "content.import.serverError.202": "Falta {0}",
        "content.import.serverError.203": "Idioma no compatible",
        "content.import.serverError.204": "Falta {0}",
        "content.import.serverError.205": "Falta {0}",
        "content.import.serverError.206": "Caracter no permitido en {0}",
        "content.import.serverError.207": "Caracter no permitido en {0}",
        "content.import.serverError.208": "Falta {0}",
        "content.import.serverError.209": "No permitido {0}",
        "content.import.serverError.210": "El Contenido predefinido contiene más de un estado",
        "content.import.serverError.211": "No permitido {0}",
        "content.import.serverError.212": "No permitido {0}",
        "content.import.serverError.213": "Falta {0}",
        "content.import.serverError.214": "Falta {0}",
        "content.import.serverError.215": "El contenido predefinido tiene más de una combinación de teclas de acceso rápido. Cambie esta letra",
        "content.import.serverError.216": "Este Contenido predefinido tiene diferentes categorías en diferentes idiomas",
        "content.import.serverError.217": "Este contenido predefinido ya existe en {0}",
        "content.import.serverError.218": "El sistema soporta hasta {0} categorías. Elimine categorías e inténtelo de nuevo",
        "content.import.serverError.219": "La combinación de teclas de acceso directo ya está en uso",
        "content.import.serverError.220": "{0} supera el límite de {1} caracteres",
        "content.import.serverError.221": "{0} supera el límite de {1} caracteres",
        "content.import.serverError.222": "El contenido predefinido tiene más de una combinación de teclas de acceso rápido. Cambie este número",
        "content.import.serverError.233": "Este contenido predefinido tiene diferentes habilidades en diferentes idiomas.",
        "content.import.serverError.234": "Lo siguiente no existe en esta cuenta: ",
        "content.import.serverError.235": "La siguiente Líneas de negocio no existe en esta cuenta: ",
        // general errors
        "content.import.serverError.300": "El archivo seleccionado puede estar dañado o no es un archivo CSV",
        "content.import.serverError.301": "Falta/n la columna/s {0}. Compruebe su archivo CSV e inténtelo de nuevo",
        "content.import.serverError.302": "Uno o más nombres de columnas no coinciden con el formato esperado, como se indica a continuación:<br/>{0}<br/>Cambie su archivo CSV e inténtelo de nuevo.",
        "content.import.serverError.303": "El archivo seleccionado está vacío",
        "content.import.serverError.304": "Tipo de archivo no compatible. Solo son compatibles los archivos CSV.",
        "content.import.serverError.305": "El tamaño del archivo seleccionado supera el límite de {0}MB",
        "content.import.serverError.306": "Los elementos de Contenido predefinido supera el límite de elemento de {0}",
        "content.import.serverError.307": "Uno o más nombres de columnas no coinciden con el formato esperado, como se indica a continuación:{0}Cambie su archivo CSV e inténtelo de nuevo.",
        "content.import.serverError.308": "Codificación del archivo no compatible (debería ser UTF-8)",
        "content.import.serverError.399": "Se ha producido un problema importando el Contenido predefinido. Inténtelo de nuevo.",
        // general validation errors
        "content.import.serverError.400": "Se ha producido un problema importando el Contenido predefinido. Inténtelo de nuevo más tarde.",
        "content.import.serverError.headersMismatchEntry": "\"{0}\" en vez de \"{1}\"",

        "content.import.errorsList.header": "Contenido importado - Lista de errores",
        "content.import.errorsList.description.1": "Los siguientes elementos incluyen errores. Los errores deben corregirse y se debe volver a cargar el archivo.",
        "content.import.errorsList.description.link": "Descargar",
        "content.import.errorsList.description.2": "el archivo con los errores para editarlo inline.",

        "content.import.errorsList.table.heading.row": "Fila",
        "content.import.errorsList.table.heading.itemId": "ID de elemento",
        "content.import.errorsList.table.heading.languages": "Idiomas",
        "content.import.errorsList.table.heading.title": "Title",
        "content.import.errorsList.table.heading.text": "Texto",
        "content.import.errorsList.table.heading.categories": "Categorías",
        "content.import.errorsList.table.heading.LOBs": "Líneas de negocio",
        "content.import.errorsList.table.heading.skills": "Habilidades",
        "content.import.errorsList.table.heading.status": "Estado",

        "content.import.errorsList.table.heading.hotKeyLetter": "Letra de tecla de acceso directo", //// MYWORD_COMPANY_LENGTH_14.
        "content.import.errorsList.table.heading.hotKeyNumber": "Número de tecla de acceso directo", //// MYWORD_COMPANY_LENGTH_14.

        "content.filter.status.true":               "Activa",
        "content.filter.status.false":              "Inactivos",
        "content.filter.status.multiple":           "Múltiple",
        "content.filter.categories.placeholder":    "Categoría...",
        "content.filter.skills.placeholder":        "Habilidad...",
        "content.filter.status.placeholder":        "Estado...",
        "content.filter.languages.placeholder":     "Idioma...",
        "content.filter.lobs.placeholder": "Línea de negocio",
        "content.filter.lobs.unassigned": "No se ha asignado LOB",
        "content.filter.table.no.results":          "No hay contenido predefinido que mostrar.",
        "content.system.table.no.results":          "No hay mensajes automáticos que mostrar.",
        "content.window.text.table.no.results":     "No hay texto de la ventana que mostrar.",

        "content.system.messaging.event.CONSUMER_OPEN_NEW_CONVERSATION.name":                       "Mensaje de bienvenida para el cliente que vuelve",
        "content.system.messaging.event.CONSUMER_OPEN_NEW_CONVERSATION_FIRST_TIME.name":            "Primero mensaje de bienvenida",
        "content.system.messaging.event.CONSUMER_OPEN_NEW_CONVERSATION_OFF_HOURS.name":             "Mensaje de bienvenida para el cliente que vuelve que vuelve fuera de horas",
        "content.system.messaging.event.CONSUMER_OPEN_NEW_CONVERSATION_FIRST_TIME_OFF_HOURS.name":  "Primer mensaje de bienvenida fuera de horas",
        "content.system.messaging.event.AGENT_UPDATED_RESPONSE_TIME.name":                          "Actualización manual del tiempo de respuesta",
        "content.system.messaging.event.CONSUMER_ASKED_URGENT_RESPONSE_TIME.name":                  "Conversación marcada como urgente",
        "content.system.messaging.event.CONSUMER_CANCELED_URGENT_RESPONSE_TIME.name":               "La conversación ya no es urgente",
        "content.system.messaging.event.CONSUMER_SEND_MESSAGE_ON_OFFHOURS.name":                    "Mensaje fuera de horas en medio de conversación",
        "content.system.messaging.event.ENGAGEMENT_TRANSFERED.name":                                "Conversación transferida a una habilidad diferente",
        "content.system.messaging.event.TRANSFER_TO_A_NEW_AGENT.name":                              "Conversación transferida a un agente específico",
        "content.system.messaging.event.ANOTHER_AGENT_JOINED_CONVERSATION.name":                    "El coordinador de agente se une a la conversación",
        "content.system.messaging.event.JOINED_AGENT_LEFT_CONVERSATION.name":                       "El coordinador de agente deja la conversación",
        "content.system.messaging.event.CONSUMER_END_CONVERSATION.name":                            "El consumidor resuelve la conversación",
        "content.system.messaging.event.AGENT_END_CONVERSATION.name":                               "El agente resuelve la conversación",
        "content.system.messaging.event.CONSUMER_NON_RESPONSIVE.name":                              "Mensaje sin respuesta de consumidor",
        "content.system.messaging.event.AGENT_NON_RESPONSIVE.name":                                 "Mensaje sin respuesta de agente",
        "content.system.messaging.event.CONSUMER_OPEN_CONV_SYSTEM_EXTREME_LOAD.name":               "Mensaje de bienvenida de carga extrema",
        "content.system.messaging.event.YOU_ARE_CONNECTED_TO.name":                                 "El agente acepta la conversación",
        "content.system.messaging.event.BACK_TO_QUEUE.name":                                        "La conversación ha vuelto a la cola",
        "content.system.messaging.event.CONV_AWAITING_IN_QUEUE.name":                               "Mensaje esperando en cola",

        "content.system.messaging.edit.event.CONSUMER_OPEN_NEW_CONVERSATION.name":                       "Un consumidor que vuelve abre una conversación durante horas de trabajo",
        "content.system.messaging.edit.event.CONSUMER_OPEN_NEW_CONVERSATION_FIRST_TIME.name":            "Un consumidor abre una conversación por primera vez, durante horas de trabajo",
        "content.system.messaging.edit.event.CONSUMER_OPEN_NEW_CONVERSATION_OFF_HOURS.name":             "Un consumidor que vuelve abre una conversación fuera de horas de trabajo",
        "content.system.messaging.edit.event.CONSUMER_OPEN_NEW_CONVERSATION_FIRST_TIME_OFF_HOURS.name":  "Un consumidor abre una conversación por primera vez, fuera de horas de trabajo",
        "content.system.messaging.edit.event.AGENT_UPDATED_RESPONSE_TIME.name":                          "El tiempo de respuesta es actualizado manualmente por el agente",
        "content.system.messaging.edit.event.CONSUMER_ASKED_URGENT_RESPONSE_TIME.name":                  "El consumidor marca la conversación como urgente",
        "content.system.messaging.edit.event.CONSUMER_CANCELED_URGENT_RESPONSE_TIME.name":               "El consumidor descarta el estado urgente de la conversación",
        "content.system.messaging.edit.event.CONSUMER_SEND_MESSAGE_ON_OFFHOURS.name":                    "El consumidor envía el primer mensaje fuera de horas de trabajo en una conversación abierta",
        "content.system.messaging.edit.event.ENGAGEMENT_TRANSFERED.name":                                "La conversación se transfiere a una habilidad diferente",
        "content.system.messaging.edit.event.TRANSFER_TO_A_NEW_AGENT.name":                              "La conversación se ha transferido a un agente específico",
        "content.system.messaging.edit.event.ANOTHER_AGENT_JOINED_CONVERSATION.name":                    "El coordinador de agente se une a la conversación",
        "content.system.messaging.edit.event.JOINED_AGENT_LEFT_CONVERSATION.name":                       "El coordinador de agente que se ha unido deja la conversación",
        "content.system.messaging.edit.event.CONSUMER_END_CONVERSATION.name":                            "El consumidor resuelve la conversación",
        "content.system.messaging.edit.event.AGENT_END_CONVERSATION.name":                               "El agente resuelve la conversación",
        "content.system.messaging.edit.event.CONSUMER_NON_RESPONSIVE.name":                              "El consumidor no ha respondido durante X segundos/minutos/horas",
        "content.system.messaging.edit.event.AGENT_NON_RESPONSIVE.name":                                 "El agente no ha respondido durante X segundos/minutos/horas",
        "content.system.messaging.edit.event.CONSUMER_OPEN_CONV_SYSTEM_EXTREME_LOAD.name":               "El consumidor abre una conversación durante una carga extrema en el centro de contacto (cola con más de X conversaciones durante más de Y mins).",
        "content.system.messaging.edit.event.YOU_ARE_CONNECTED_TO.name":                                 "El consumidor está conectado a un agente",
        "content.system.messaging.edit.event.BACK_TO_QUEUE.name":                                        "El agente devuelve la conversación a la cola",
        "content.system.messaging.edit.event.CONV_AWAITING_IN_QUEUE.name":                               "Conversación desasignada durante más de X segundos/minutos/horas"
    };

    return Dictionary;
});
