/**
 * Created with IntelliJ IDEA.
 * User: itziky
 * Date: 7/2/13
 */

define(function () {
    "use strict";

    var Dictionary = {
        "tempString": "Este es un mantenedor de espacio temporal para la etapa de desarrollo.",
        "keepAlive.timeout.title" : "Desconexión de la sesión",
        "keepAlive.timeout.message" : "Su sesión está a punto de caducar.",
        "keepAlive.timeout.okText" : "Mantener sesión",
        "blockNavigation.title" : "Confirmar navegación",
        "blockNavigation.message" : "Está a punto de salir de la página.",
        "blockNavigation.objectAction.message" : "Salir de la página",
        "session.unauthorized.title" : "No autorizado",
        "session.unauthorized.message" : "No está autorizado para realizar esta acción.",
        "session.unauthorized.okText" : "Volver a iniciar sesión",
        "userBarMenu.menuItem.logout" : "Salir",
        "userBarMenu.menuItem.login" : "Iniciar sesión",
        "userBarMenu.header.account": "Cuenta",
        "userBarMenu.item.myProfile": "Mi perfil",
        "userBarMenu.item.myDetails": "Mis datos",
        "userBarMenu.item.myAccount": "Mi cuenta",
        "userBarMenu.item.auditTrail": "Registro de auditoria",
        "userBarMenu.item.statusPage": "Panel de control de estado del servicio",
        "userBarMenu.item.shiftStatus": "Estado de turnos",
        "userBarMenu.item.workingHours": "Programador de turnos",
        "userBarMenu.item.shiftStatus.online": "En línea",
        "userBarMenu.item.shiftStatus.off.hours": "Horas desactivado",
        "userBarMenu.item.customReasons.other": "(otro)",
        "userBarMenu.item.customReasons.default": "(predeterminada)",
        "userBarMenu.footer.soundButton.tooltip.on": "Silenciar todos los sonidos",
        "userBarMenu.footer.soundButton.tooltip.off": "Activar todos los sonidos",
        "signOutConfirmation.title" : "¿Seguro que desea salir?",
        "signOutConfirmation.end.user.session.title" : "Finalizar sesión de usuario",
        "signOutConfirmation.warning.chat": "¿Seguro que desea salir? Si tiene chats activos, se cerrarán automáticamente. Los chats cerrados ya no estarán disponibles.",
        "signOutConfirmation.message" : "Usted tiene: ",
        "signOutConfirmation.okText" : "Salir",
        "leaveConfirmation.title" : "No ha cerrado sesión.",
        "leaveConfirmation.message" : "¿Seguro que quiere salir?",
        "userBarMenu.menuItem.debug" : "Depurar",
        "userBarMenu.menuItem.debug.description.on" : "activar depuración",
        "userBarMenu.menuItem.debug.description.off" : "desactivar depuración",
        "userBarMenu.menuItemTray.TrialAccount" : "CUENTA DE PRUEBA",
        "userBarMenu.menuItemTray.TrialAccountDayLeft" : "SÓLO QUEDA UN DÍA",
        "userBarMenu.menuItemTray.TrialAccountDaysLeft" : "SÓLO QUEDAN {0} DÍAS",
        "userBarMenu.menuItemTray.ActivateAccount" : "ACTUALIZAR CUENTA",
        "userBarMenu.menuItemTray.OneUserFree" : "Actualizar ahora",
        "userBarMenu.menuItemTray.AddSeat": "¡Su cuenta de 1 usuario es gratuita! Añada más usuarios actualizando a uno de nuestros Programas Avanzados.",
        "userBarMenu.menuItemTray.AgentManager.AddSeat": "Para añadir más usuarios, la cuenta debe actualizarse a uno de nuestros Programas avanzados.",
        "userBarMenu.menuItemTray.AddUsers" : "Añadir más usuarios",
        "userBarMenu.menuItemTray.UpgradeNow" : "Actualizar ahora",
        "userBarMenu.menuItemTray.SignUpNow" : "Regístrese ahora para mantener a sus clientes conectados y su sitio Web con interacciones.",
        "userBarMenu.menuItemTray.sound.off.tooltip": "El sonido está apagado",
        "chatInvitation.chatWithUs" : "Hable con nosotros",
        "something.went.wrong" : "La operación ha fallado. Inténtelo de nuevo más tarde.",

        "topLevelLinks.link.knowledgeCenter": "Centro de conocimientos",
        "topLevelLinks.link.developersCommunity": "Comunidad de desarrolladores",

        "LiveEngageTag.title" : "Etiqueta de LiveEngage",
        "LiveEngageTag.description" : "Incorpore la etiqueta de LiveEngage en sus páginas Web para comenzar el seguimiento, monitorización e interacción de los visitantes de su sitio Web.",
        "LiveEngageTag.button.close" : "Cerrar",
        "LiveEngageTag.check.again" : "Comprobar de nuevo",
        "LiveEngageTag.select.and.copy" : "SELECCIONAR Y COPIAR",
        "LiveEngageTag.paste" : "PEGAR",
        "LiveEngageTag.repeat" : "REPETIR",
        "LiveEngageTag.the.code.below" : " el siguiente código",
        "LiveEngageTag.the.code.at.the.top" : "el código tan alto en el elemento de encabezamiento como sea posible",
        "LiveEngageTag.placing.the.tag" : "incorporar la etiqueta en tantas páginas Web como sea posible (LiveEngage sólo llega a las páginas etiquetadas)",
        "LiveEngageTag.select.and.copy.this.code" : "Seleccionar y copiar este código:",
        "LiveEngageTag.button.select" : "Seleccionar",
        "LiveEngageTag.send.email" : "Enviar este código por correo electrónico",
        "LiveEngageTag.needHelp" : "¿NECESITA AYUDA?",
        "LiveEngageTag.needHelp.video" : "Ver este vídeo",

        "DataSources.Top.Menu.Item": "Fuentes de datos",

        "Verify.website.tag.setup" : "Verifique la configuración de etiqueta de LiveEngage de su sitio. Siga los pasos siguientes para continuar.",
        "Tag.setup.completed" : "La configuración de LiveEngage se ha completado.",

        "upgradeAccount.readAll.text": "Información sobre",
        "upgradeAccount.benefits.link.text": "los beneficios que LiveEngage",
        "upgradeAccount.text": "tiene que ofrecer y los cambios que puede esperar tras la actualización de su cuenta.",
        "upgradeAccount.disclaimer": "Conozco las características y los cambios",
        "upgradeAccount.changeOne": "Usuarios asignados a nuestros grupos de permiso",
        "upgradeAccount.changeTwo": "Campañas actualizadas",
        "upgradeAccount.changeThree": "Aspecto mejorado de la Ventana de interacciones",
        "upgradeAccount.adminOnly": "*Contacte con nosotros para obtener ayuda",
        "upgradeAccount.unauthorized.adminOnly": "Contacte con un empleado de LivePerson para actualizar su cuenta.",
        "upgradeAccount.button.cpi": "Actualizar a CPI",
        "upgradeAccount.button.seat": "Actualizar a Basado en asiento",

        //language
        "en-US" : "English",
        "de-DE" : "Deutsch",
        "it-IT" : "Italiano",
        "ja-JP" : "日本語",
        "es-ES" : "Español",
        "pt-BR" : "Português (Brasil)",
        "zh-CN" : "中文 (简体)",
        "ko-KR" : "한국어",
        "fr-FR" : "Français",
        "tr-TR" : "Türkçe",
        "da-DK" : "Dansk",
        "fi-FI" : "Suomi",
        "ro-RO" : "Română",
        "ru-RU" : "Русский",

        //account languages

        "account.lang.af-ZA.name"   : "Afrikaans",
        "account.lang.sq-AL.name"   : "Albano",
        "account.lang.ar-AE.name"   : "Árabe",
        "account.lang.bg-BG.name"   : "Búlgaro",
        "account.lang.zh-CN.name"   : "Chino (Simplificado)",
        "account.lang.zh-CHT.name"  : "Chino (Tradicional)",
        "account.lang.zh-TW.name"  : "Chino - (tradicional Taiwán)",
        "account.lang.zh-HK.name"  : "Chino (tradicional Hong Kong)",
        "account.lang.hr-HR.name"   : "Croata",
        "account.lang.cs-CZ.name"   : "Checo",
        "account.lang.da-DK.name"   : "Danés",
        "account.lang.nl-NL.name"   : "Holandés",
        "account.lang.en-UK.name"   : "Inglés (UK)",
        "account.lang.en-US.name"   : "Inglés (US)",
        "account.lang.et-EE.name"   : "Estonio",
        "account.lang.fi-FI.name"   : "Finlandés",
        "account.lang.fr-FR.name"   : "Francés",
        "account.lang.de-DE.name"   : "Alemán",
        "account.lang.el-GR.name"   : "Griego",
        "account.lang.he-IL.name"   : "Hebreo",
        "account.lang.hu-HU.name"   : "Húngaro",
        "account.lang.is-IS.name"   : "Islandés",
        "account.lang.it-IT.name"   : "Italiano",
        "account.lang.ja-JP.name"   : "Japonés",
        "account.lang.ko-KR.name"   : "Coreano",
        "account.lang.lv-LV.name"   : "Letón",
        "account.lang.lt-LT.name"   : "Lituano",
        "account.lang.mk-MK.name"   : "Macedonio",
        "account.lang.nb-NO.name"   : "Noruego",
        "account.lang.pl-PL.name"   : "Polaco",
        "account.lang.pt-BR.name"   : "Portuguese (Brazil)",
        "account.lang.pt-PT.name"   : "Portuguese (Portugal)",
        "account.lang.ro-RO.name"   : "Rumano",
        "account.lang.ru-RU.name"   : "Ruso",
        "account.lang.Cy-sr-SP.name": "Serbio",
        "account.lang.sk-SK.name"   : "Eslovaco",
        "account.lang.sl-SI.name"   : "Eslovenio",
        "account.lang.es-ES.name"   : "Español",
        "account.lang.sv-SE.name"   : "Sueco",
        "account.lang.th-TH.name"   : "Tailandés",
        "account.lang.tr-TR.name"   : "Turcos",
        "account.lang.uk-UA.name"   : "Ucraniano",
        "account.lang.vi-VN.name"   : "Vietnamita",
        "account.lang.hi-IN.name"   : "Hindi",
        "account.lang.id-ID.name"   : "Indonesio",
        "account.lang.fr-CA.name"   : "Francés (Canadá)",
        "account.lang.ms-MY.name"   : "Malayo",
        "account.lang.es-419.name"  : "Español (Latinoamérica)",

        "account.lang.af-ZA.code" : "af-ZA",
        "account.lang.sq-AL.code" : "sq-AL",
        "account.lang.ar-AE.code" : "ar-AE",
        "account.lang.bg-BG.code" : "bg-BG",
        "account.lang.zh-CN.code" : "zh-CN",
        "account.lang.zh-CHT.code": "zh-CHT",
        "account.lang.zh-TW.code" : "zh-TW",
        "account.lang.zh-HK.code" : "zh-HK",
        "account.lang.hr-HR.code" : "hr-HR",
        "account.lang.cs-CZ.code" : "cs-CZ",
        "account.lang.da-DK.code" : "da-DK",
        "account.lang.nl-NL.code" : "nl-NL",
        "account.lang.en-UK.code" : "en-UK",
        "account.lang.en-US.code" : "en-US",
        "account.lang.et-EE.code" : "et-EE",
        "account.lang.fi-FI.code" : "fi-FI",
        "account.lang.fr-FR.code" : "fr-FR",
        "account.lang.de-DE.code" : "de-DE",
        "account.lang.el-GR.code" : "el-GR",
        "account.lang.he-IL.code" : "he-IL",
        "account.lang.hi-IN.code" : "hi-IN",
        "account.lang.hu-HU.code" : "hu-HU",
        "account.lang.is-IS.code" : "is-IS",
        "account.lang.it-IT.code" : "it-IT",
        "account.lang.ja-JP.code" : "ja-JP",
        "account.lang.ko-KR.code" : "ko-KR",
        "account.lang.lv-LV.code" : "lv-LV",
        "account.lang.lt-LT.code" : "lt-LT",
        "account.lang.mk-MK.code" : "mk-MK",
        "account.lang.nb-NO.code" : "nb-NO",
        "account.lang.pl-PL.code" : "pl-PL",
        "account.lang.pt-BR.code" : "pt-BR",
        "account.lang.pt-PT.code" : "pt-PT",
        "account.lang.ro-RO.code" : "ro-RO",
        "account.lang.ru-RU.code" : "ru-RU",
        "account.lang.Cy-sr-SP.code" : "Cy-sr-SP",
        "account.lang.sk-SK.code" : "sk-SK",
        "account.lang.sl-SI.code" : "sl-SI",
        "account.lang.es-ES.code" : "es-ES",
        "account.lang.sv-SE.code" : "sv-SE",
        "account.lang.th-TH.code" : "th-TH",
        "account.lang.tr-TR.code" : "tr-TR",
        "account.lang.uk-UA.code" : "uk-UA",
        "account.lang.vi-VN.code" : "vi-VN",
        "account.lang.id-ID.code" : "id-ID",
        "account.lang.fr-CA.code" : "fr-CA",
        "account.lang.ms-MY.code" : "ms-MY",
        "account.lang.es-419.code" : "es-419",


        //currency
        "USD" : "USD",
        "EUR" : "EUR",
        "JPY" : "JPY",
        "YEN" : "YEN",
        "CNY" : "CNY",
        "KRW" : "KRW",
        "GBP" : "GBP",

        //timeZone
        "Pacific/Kiritimati" : " Isla de la línea Islas de la Línea ",
        "Pacific/Apia" : " Hora de Samoa Occidental ",
        "Pacific/Wallis" : " Hora de Wallis y Futuna ",
        "Pacific/Wake" : " Hora de Wake ",
        "Pacific/Majuro" : " Hora de las Islas Marshall ",
        "Pacific/Fiji" : " Hora de Fiji ",
        "Pacific/Auckland" : " Hora Estándar de Nueva Zelanda ",
        "Pacific/Pohnpei" : " Hora de Pohnpei ",
        "Pacific/Noumea" : " Hora de Nueva Calcedonia ",
        "Pacific/Norfolk" : " Hora de Norfolk ",
        "Asia/Vladivostok" : " Hora de Vladivostok ",
        "Antarctica/Casey" : " Hora Estándar Occidental (Australia)",
        "Pacific/Port_Moresby" : " Hora de Papua Nueva Guinea ",
        "Pacific/Guam" : " Hora Estándar de Chamorro ",
        "Australia/Brisbane" : " Hora Estándar Oriental (Queensland)",
        "Australia/Sydney" : " Hora de Melbourne y Sydney ",
        "Asia/Yakutsk" : " Hora de Yakutsk ",
        "Pacific/Palau" : " Hora de Palau ",
        "Australia/Darwin" : " Hora Estándar Central (Territorio del Norte)",
        "Asia/Tokyo" : " Hora Estándar de Japón ",
        "Asia/Seoul" : " Hora Estándar de Corea ",
        "Asia/Jayapura" : " Hora de Indonesia Oriental ",
        "Australia/Eucla" : " Hora Estándar Central Occidental (Australia)",
        "Asia/Taipei" : " Hora Estándar de China ",
        "Asia/Singapore" : " Hora de Singapur ",
        "Asia/Shanghai" : " Hora Estándar de China ",
        "Asia/Manila" : " Hora de Filipinas ",
        "Asia/Makassar" : " Hora Indonesia Cental ",
        "Asia/Macau" : " Hora Estándar de China ",
        "Asia/Kuala_Lumpur" : " Hora de Malasia ",
        "Asia/Hong_Kong" : " Hora de Hong Kong ",
        "Asia/Vientiane" : " Hora de Indochina ",
        "Asia/Pontianak" : " Hora de Indonesia Occidental ",
        "Asia/Novosibirsk" : " Hora de Novosibirsk ",
        "Asia/Jakarta" : " Hora de Indonesia Occidental ",
        "Asia/Bangkok" : " Hora de Indochina ",
        "Asia/Rangoon" : " Hora de Myanmar ",
        "Asia/Dhaka" : " Hora de Bangladesh ",
        "Asia/Bishkek" : " Hora de Kirgizstan ",
        "Indian/Maldives" : " Hora de las Maldivas ",
        "Asia/Tashkent" : " Hora de Uzbekistan ",
        "Asia/Kolkata" : " Hora Estándar de India ",
        "Asia/Kathmandu" : " Hora de Nepal ",
        "Asia/Karachi" : " Hora de Pakistán ",
        "Asia/Dushanbe" : " Hora de Tajikistán ",
        "Asia/Ashgabat" : " Hora de Turkmenistán ",
        "Indian/Mauritius" : " Hora de Islas Mauricio ",
        "Indian/Mahe" : " Hora de Seychelles ",
        "Europe/Moscow" : " Hora Estándar de Moscú ",
        "Asia/Yerevan" : " Hora de Armenia ",
        "Asia/Tbilisi" : " Hora de Georgia ",
        "Asia/Kabul" : " Hora de Afghanistán ",
        "Asia/Dubai" : " Hora Estándar del Golfo ",
        "Asia/Baku" : " Hora de Azerbaiján ",
        "Indian/Comoro" : " Hora de África Oriental ",
        "Asia/Tehran" : " Hora Estándar de Irán ",
        "Asia/Riyadh" : " Hora Estándar de Arabia ",
        "Africa/Nairobi" : " Hora de África Oriental ",
        "Europe/Sofia" : " Hora de Estándar Europea ",
        "Asia/Jerusalem" : " Hora Estándar de Israel ",
        "Asia/Hebron" : " Hora de Estándar Europea ",
        "Africa/Maseru" : " Hora Estándar de Sudáfrica ",
        "Africa/Maputo" : " Hora de África Central ",
        "Africa/Johannesburg" : " Hora Estándar de Sudáfrica ",
        "Africa/Harare" : " Hora de África Central ",
        "Europe/Warsaw" : " Hora de Europa Central ",
        "Africa/Kinshasa" : " Hora de África Occidental ",
        "Europe/London" : " Hora del Meridiano de Greenwich ",
        "Europe/Lisbon" : " Hora de Europa Occidental ",
        "Africa/Accra" : " Hora del Meridiano de Ghana ",
        "Atlantic/Cape_Verde" : " Hora de Cabo Verde ",
        "Atlantic/Azores" : " Hora de las Azores ",
        "America/Scoresbysund" : " Hora de Groenlandia Oriental ",
        "Atlantic/South_Georgia" : " Hora Estándar de Georgia del Sur ",
        "America/Noronha" : " Hora de Fernando de Noronha ",
        "Atlantic/Stanley" : " Isla de Malvinas Islas Malvinas ",
        "Antarctica/Rothera" : " Hora de Rotera ",
        "America/St_Johns" : " Hora Estándar de Newfoundland ",
        "America/Paramaribo" : " Hora de Suriname ",
        "America/Montevideo" : " Hora de Uruguay ",
        "America/Miquelon" : " Hora Estándar de Pierre & Miquelon ",
        "America/Godthab" : " Hora de Groenlandia Occidental ",
        "America/Cayenne" : " Hora de Guinea Francesa ",
        "America/Bahia" : " Hora de Brasilia ",
        "America/Argentina/San_Luis" : " Hora de Argentina Occidental ",
        "America/Argentina/Buenos_Aires" : " Hora de Argentina ",
        "America/Santiago" : " Hora de Chile ",
        "America/Rio_Branco" : " Hora del Amazonas ",
        "America/Lower_Princes" : " Hora Estándar del Atlántico ",
        "America/La_Paz" : " Hora de Bolivia ",
        "America/Guyana" : " Hora de Guayana ",
        "America/Cuiaba" : " Hora del Amazonas ",
        "America/Caracas" : " Hora de Venezuela ",
        "America/Barbados" : " Hora Estándar del Atlántico ",
        "America/Asuncion" : " Hora de Paraguay ",
        "America/Aruba" : " Hora Estándar del Atlántico ",
        "America/New_York" : " Hora Estándar Oriental ",
        "America/Lima" : " Hora de Perú ",
        "America/Havana" : " Hora Estándar de Cuba ",
        "America/Guayaquil" : " Hora de Ecuador ",
        "America/Bogota" : " Hora de Colombia ",
        "America/Atikokan" : " Hora Estándar Oriental ",
        "Pacific/Galapagos" : " Hora de Galapagos ",
        "Pacific/Easter" : " Isla de Pascua Islas Orientales ",
        "America/Chicago" : " Hora Estándar Central ",
        "America/Phoenix" : " La Hora Estándar de la Montaña (MST) no observa el horario de verano ",
        "America/Denver" : " Hora Estándar de las Montañas ",
        "Pacific/Pitcairn" : " Hora Estándar de Pitcairn ",
        "America/Metlakatla" : " Hora Estándar de Metlakatla ",
        "America/Los_Angeles" : " Hora Estándar del Pacífico ",
        "Pacific/Marquesas" : " Hora de Marquesas ",
        "Pacific/Gambier" : " Hora de Gambier ",
        "America/Anchorage" : " Hora Estándar de Alaska ",
        "Pacific/Tahiti" : " Hora de Tahití ",
        "Pacific/Rarotonga" : " Islas cook Islas Cook ",
        "Pacific/Honolulu" : " Hora Estándar de Hawaii ",
        "Pacific/Niue" : " Hora de Niue ",
        "Pacific/Midway" : " Hora Estándar de Samoa ",

        //Time frames
        "timeFrame.period.am": "AM",
        "timeFrame.period.pm": "PM",

        // attribution model
        "First": "Primero",
        "Last": "Último",

        "tagFlowBanner.welcomeTitle" : "¡Bienvenido!",
        "tagFlowBanner.title" : "Comience a comprometerse con sus clientes",
        "tagFlowBanner.bannerContent.line1" : "Visitantes como estos podrían estar en su sitio Web ahora...",
        "tagFlowBanner.bannerContent.line2" : "Para llegar a ellos, deberá añadir la etiqueta de LiveEngage a sus sitios Web.",
        "tagFlowBanner.actionBtnText" : "Consiga la etiqueta de LiveEngage",
        "tagFlowBanner.actionBtnTooltip" : "Vuelva a su página de etiquetas.",
        "tagFlowBanner.LiveEngageTagPointer.bubble" : "La etiqueta de LiveEngage está aquí",

        "migrationDoneBanner.bannerContent.line1" : "Las campañas están ahora activas en su sitio Web",
        "migrationDoneBanner.bannerContent.line2" : "Sienta el nuevo LiveEngage y vea los beneficios",
        "migrationDoneBanner.actionBtnText" : "Continuar",

        "errors.generalError" : "Tiene {0} {1} en la página.",
        "errors.generalError.on.page" : "Tiene errores en la página.",
        "errors.generalError.error.text" : "error",
        "errors.generalError.errors.text" : "errores",
        /**************
         * server error messages
         * errors.serverError.errorCode : message
         * **********************/
        "errors.serverError.unknownError" : "Se ha producido un error desconocido.",
        "errors.serverError.1000": "Se ha producido un problema inesperado.",
        "errors.serverError.1001": "No se pudo completar la solicitud porque otro usuario está editando la misma entidad.",
        "errors.serverError.1002": "Elemento no encontrado.",
        "errors.serverError.1003": "No se pudo completar la solicitud. Existe una dependencia no especificada en el sistema.",
        "errors.serverError.1007": "Una campaña no puede ser publicada sin un objetivo definido.",
        "errors.serverError.1008": "Una campaña no puede ser publicada sin una audiencia objetivo definida.",
        "errors.serverError.1010": "Se ha producido un problema no especificado mientras se validaba el contenido de su solicitud. Inténtelo de nuevo.",
        "errors.serverError.1011": "Una interacción no puede crearse sin un punto de entrada.",
        "errors.serverError.1012": "Una interacción no puede crearse sin un comportamiento del visitante.",
        "errors.serverError.1013": "Su interacción no puede guardarse debido al siguiente problema: Una interacción integrada no puede vincularse a una zona no integrada.",
        "errors.serverError.1014": "La limitación solo puede actualizarse para interacciones proactivas.",
        "errors.serverError.1015": "La solicitud no puede completarse debido a un problema de dependencia.",
        "errors.serverError.1016": "Ya existe una entidad con el mismo nombre. Cambie el nombre e inténtelo de nuevo.",
        "errors.serverError.1017": "El texto que ha introducido es demasiado largo. Inténtelo de nuevo con una entrada más corta.",
        "errors.serverError.1018": "Su texto contiene caracteres no válidos.",

        "errors.serverError.1100": "Proceso fallido. Inténtelo de nuevo o contacte con el Soporte técnico de LivePerson.",
        "errors.serverError.1200": "Su sesión ha caducado. Inicie sesión de nuevo.",
        "errors.serverError.1201": "No tiene permiso para realizar la acción solicitada.",
        "errors.serverError.1205": "Privilegios insuficientes",
        "errors.serverError.1206": "No autenticado",
        "errors.serverError.1300": "Los datos recuperados de la BBDD no pueden transformarse a respuesta",

        "global.captions.publish" : "Publicar",
        "global.captions.unpublish" : "Dejar de publicar",
        "global.captions.disable" : "Desactivar",
        "global.captions.cancel" : "Cancelar",
        "global.captions.close" : "Cerrar",
        "global.captions.save" : "Guardar",
        "global.captions.send" : "Enviar",
        "global.captions.done" : "Listo",
        "global.captions.submit": "Enviar",
        "global.captions.continue": "Continuar",
        "global.captions.yes" : "Sí",
        "global.captions.no" : "No",
        "global.captions.edit" : "Modificar",
        "global.captions.apply" : "Aplicar",
        "global.captions.delete" : "Eliminar",
        "global.captions.restore.to.default" : "Restablecer a predeterminada",
        "global.captions.try.again" : "Inténtelo de nuevo",
        "global.captions.ok" : "Aceptar",
        "global.captions.action" : "Acción",
        "global.captions.actions" : "Acciones",
        "global.captions.add" : "Añadir",
        "global.captions.addNew" : "Añadir nueva",
        "global.captions.prev" : "Anterior",
        "global.captions.next" : "Siguiente",
        "global.captions.back" : "Volver",
        "global.captions.active" : "Activa",
        "global.captions.duplicate" : "Duplicar",
        "global.captions.setAsDefault" : "Establecer como predeterminado",
        "global.captions.are.you.sure" : "¿Está seguro?",
        "global.captions.open" : "Abrir",
        "global.captions.create" : "Crear",
        "global.captions.saveAs" : "Guardar como",
        "global.captions.reset" : "Reiniciar",
        "global.captions.select" : "Seleccionar",
        "global.captions.learnMore" : "Más información",
        "global.captions.move" : "Mover",
        "global.captions.export" : "Exportar",
        "global.captions.exportAll" : "Exportar todo",
        "global.captions.assignSkills" : "Asignar habilidades",
        "global.captions.setConcurrency" : "Establecer divisa",
        "global.captions.subscribe" : "Suscribirse",
        "global.captions.unsubscribe" : "Cancelar suscripción",
        "global.noImageSelect" : "No se ha seleccionado imagen",
        "global.url.enter": "Introducir URL",
        "global.background.color": "Color de fondo",
        "global.border.color": "Color del borde",
        "global.font.color": "Color del texto",
        "global.export.failed": "Error de exportación",
        "global.please.try.again": "Inténtelo de nuevo.",

        "global.captions.add.tooltip": "Añadir",
        "global.captions.edit.tooltip": "Modificar",
        "global.captions.delete.tooltip": "Eliminar",
        "global.captions.duplicate.tooltip": "Duplicar",
        "global.captions.move.tooltip": "Mover",
        "global.captions.exportAll.tooltip": "Exportando todos los usuarios, habilidades, conjuntos de permisos y grupos de agentes.",
        "global.captions.assignSkills.tooltip" : "Configurar las asignaciones de habilidades de los usuarios seleccionados.",
        "global.captions.setConcurrency.tooltip" : "Configurar el ajuste de concurrencia de los usuarios seleccionados.",

        "global.captions.dataNotUpdated": "Los datos mostrados no están actualizados.",
        "global.captions.refreshData": "Actualizar datos",

        "language" : "es-ES",
        "DataSources": "Fuentes de datos",
        "GoogleAnalyticsTitle": "Google Analytics",
        "GoogleAnalyticsDesc": "Las fuentes de datos le permiten elaborar sobre datos, recopilando información adicional de múltiples fuentes. Realice un seguimiento de las acciones clave y su valor monetario, y consiga una mejor información sobre los datos de sus visitantes.",
        "Connect": "Conectar",
        "Connected": "Conectado",
        "Disconnect": "Desconectar",
        "PleaseSignin": "OBSOLETO--Inicie sesión en su cuenta de Google relevante en la ventana emergente",
        "PopupVisible": "OBSOLETO--¿No aparece la ventana emergente?",
        "TryAgain": "OBSOLETO--Inténtelo de nuevo",
        "ConnectionSuccess": "Conectado a Google Analytics.",
        "ConnectionError": "No se pudo conectar a Google Analytics. Inténtelo de nuevo.",
        "AccessUrlError": "No se pudo conectar a Google Analytics. Inténtelo de nuevo.",
        "DisconnectConfirmTitle": "¿Está seguro?",
        "DisconnectConfirmMessage": "Si desconecta su cuenta de Google Analytics, LiveEngage no podrá utilizar los datos y por tanto se reducirá el nivel de público objetivo.",
        "DisconnectActionText": "Aceptar",

        "checkForVisitorsBanner.bannerContent.line1": "LiveEngage no pudo detectar visitantes en las últimas 24 horas",
        "checkForVisitorsBanner.actionBtnText" : "Implementar etiqueta",
        "checkForVisitorsBanner.countDown.checkingAgainIn" : "Comprobar de nuevo en:",
        "checkForVisitorsBanner.countDown.checkingForVisitors" : "Buscando visitantes:",

        "bannerCountDownSuccess.bannerContent.line1": "LiveEngage ha detectado actividad de visitante en su sitio Web.",

        "upgrade.failed.try.again": "Actualización fallida. Inténtelo de nuevo más tarde.",
        "upgrade.failed.permissions.try.again": "La actualización ha fallado debido a un error al convertir los permisos. Inténtelo de nuevo más tarde.",
        "upgrade.succeeded": "Ha actualizado correctamente la nueva Plataforma de LiveEngage.",
        "upgrade.changed.permissions": "Debido a la actualización, pueden haberse cambiado los permisos para algunos de sus usuarios. Revise los permisos otorgados.",

        "sessionTimeoutCodes.minutes": "{0} minutos",
        "sessionTimeoutCodes.hour": "{0} hora",
        "sessionTimeoutCodes.hours": "{0} horas",

        "slaUnitsCodes.days": "Días",
        "slaUnitsCodes.hours": "Horas",
        "slaUnitsCodes.minutes": "Minutos",

        "timeUnitCodes.days": "Días",
        "timeUnitCodes.hours": "Horas",
        "timeUnitCodes.minutes": "Minutos",
        "timeUnitCodes.seconds": "Segundos",

        // DEFAULT TOP BAR
        "GUEST_SitesVisitsObserved": "VISITAS A SITIOS WEB OBSERVADAS",
        "GUEST_LiveChats": "CHATS EN VIVO",
        "GUEST_Conversions": "AUMENTO DE CONVERSIONES",
        "GUEST_AvgOrderValues": "% AUM. MED. VALOR DE PEDIDO",

        "marketing.originatingChannel.0": "Directo",
        "marketing.originatingChannel.1": "Buscar",
        "marketing.originatingChannel.2": "Social",
        "marketing.originatingChannel.3": "Correo electrónico",
        "marketing.originatingChannel.4": "Recomendación",
        "marketing.originatingChannel.5": "Búsqueda pagada",
        "marketing.originatingChannel.6": "Mostrar",

        "serviceActivity.status.0": "Completo",
        "serviceActivity.status.1": "En progreso",
        "serviceActivity.status.2": "Aprobado",
        "serviceActivity.status.3": "Cancelado",
        "serviceActivity.status.4": "No aprobado",
        "serviceActivity.status.5": "Revisado",
        "serviceActivity.status.6": "Faltan detalles",
        "serviceActivity.status.7": "Cerrado",
        "serviceActivity.status.8": "Eliminado",
        "serviceActivity.status.9": "Asignado",
        "serviceActivity.status.10" : "Esperando al cliente",
        "serviceActivity.status.11" : "Esperando respuesta",
        "serviceActivity.status.12" : "Pendiente",
        "serviceActivity.status.13" : "Resuelto",

        "entities.skill.errors.name.required": "El nombre es obligatorio.",
        "entities.skill.errors.name.length": "El nombre no puede superar los 50 caracteres.",
        "entities.skill.errors.name.duplicated": "El nombre ya existe.",
        "entities.skill.errors.description.required": "La descripción es obligatoria.",
        "entities.skill.errors.description.length": "La descripción no puede superar los 300 caracteres.",
        "entities.skill.errors.maxWaitTime.required": "Se requiere el tiempo máximo de espera.",
        "entities.skill.errors.maxWaitTime.max": "El tiempo máximo de espera es de 9999",
        "entities.skill.errors.maxWaitTime.nan": "Introduzca un número válido.",
        "entities.errors.description.length": "La descripción no puede superar los 300 caracteres.",
        "entities.skill.errors.wrapUpTime.max": "El tiempo máximo de cierre es de 1800.",
        "entities.skill.errors.defaultSla.required": "Se requiere un tiempo de respuesta predeterminado.",
        "entities.skill.errors.urgentSla.required": "Se requiere un tiempo de respuesta urgente.",
        "entities.skill.errors.firstTimeSla.required": "Se requiere primer tiempo de respuesta.",
        "entities.skill.errors.workingHours.required": "Se requieren los días de trabajo",
        "entities.skill.errors.specialOccasion.required": "Se requiere la ocasión especial.",
        "entities.skill.errors.autoClose.required": "Se requiere cerrado automático.",
        "entities.skill.errors.autoClose.range": "El valor permitido está entre 25 minutos y 90 días.",
        "entities.skill.errors.dependency.conflict": "Esta habilidad ha sido actualizada por otro usuario; por favor, vuelva a abrirla e inténtelo de nuevo.",
        "entities.skill.errors.transferToAgent.required": "Se requiere transferencia a tiempo de agente.",
        "entities.skill.errors.transferToAgent.range": "El valor permitido está entre 1 segundo y 100 días",
        "entities.skill.errors.agentSurveyForMsgTimeoutInMinutes.max": "El tiempo de desconexión máximo es de 4320 minutos",
        "entities.skill.errors.fallbackSkill.required": "Se requiere habilidad de solución alternativa",

        "entities.skill.delete.error.dependencies": "La habilidad no puede eliminarse porque está asignada a las siguientes entidades:<br>{0}",
        "entities.skill.delete.error.dependencies.field.users": "Usuarios",
        "entities.skill.delete.error.dependencies.field.cannedResponses": "Contenido predefinido",
        "entities.skill.delete.error.dependencies.field.auto-messages": "Mensajes automáticos - Chat en vivo",
        "entities.skill.delete.error.dependencies.field.unified-auto-messages": "Mensajes automáticos - Mensajería",
        "entities.skill.delete.error.dependencies.field.widgets": "Widgets de integración",
        "entities.skill.delete.error.dependencies.field.external": "Cuestionarios",
        "entities.skill.delete.error.dependencies.field.engagements": "Interacciones",
        "entities.skill.delete.error.dependencies.field.campaigns": "Campañas",
        "entities.skill.delete.error.dependencies.field.skills": "Lista de transferencia de habilidades",
        "entities.skill.delete.error.dependencies.field.Survey": "Cuestionarios",

        /* TODO: Adiel: Here only for backward compatible for 7.12 need to be removed after 7.12 */
        "entities.user.errors.loginName.required": "Se requiere nombre de usuario.",
        "entities.user.errors.loginName.invalid": "El nombre de usuario debe usar caracteres en inglés, números o caracteres especiales.",
        "entities.user.errors.loginName.duplicated": "Ya existe el nombre de usuario.",

        "entities.user.errors.loginName.required.new": "Se requiere nombre de usuario.",
        "entities.user.errors.loginName.invalid.new": "El nombre de usuario debe usar caracteres en inglés, números o caracteres especiales.",
        "entities.user.errors.loginName.duplicated.new": "Ya existe el nombre de usuario.",
        "entities.user.errors.email.required": "El correo electrónico es obligatorio.",
        "entities.user.errors.email.invalid": "Introduzca una dirección de correo electrónico válida. Tenga en cuenta que la dirección debe contener solo letras inglesas.",
        "entities.user.errors.email.duplicated": "Ya existe el correo electrónico.",
        "entities.user.errors.nickName.required": "El apodo es obligatorio.",
        "entities.user.errors.displayName.required": "El nombre es obligatorio.",
        "entities.user.errors.displayName.duplicated": "El nombre ya existe.",
        "entities.user.errors.password.length": "La contraseña debe tener al menos 8 caracteres.",
        "entities.user.errors.password.required": "La contraseña es obligatoria.",
        "entities.user.errors.password.invalid": "La contraseña debe usar inglés, números o caracteres especiales únicamente.",
        "entities.user.errors.oldPassword.required": "Se requiere su contraseña actual.",
        "entities.user.errors.oldPassword.wrongCredentials": "Contraseña incorrecta.",
        "entities.user.errors.assignToGroup.required": "El grupo es obligatorio.",
        "entities.user.errors.profile.required": "Se requiere el perfil.",
        "entities.user.errors.appKey.required": "Se requiere la clave API.",
        "entities.user.errors.assignToGroup.notFromList": "Seleccione un grupo de la lista.",
        "entities.user.errors.password.passwordRestrictions": "Esta contraseña no es compatible con su política de contraseñas.",
        "entities.user.errors.password.usedPassword": "Ya ha usado esta contraseña.<br/>Introduzca una nueva contraseña.",
        "entities.user.errors.password.missingAlphaCharacters": "La contraseña debe incluir caracteres alfanuméricos.",
        "entities.user.errors.password.maximumNumberOfSequentialCharacters": "La contraseña tiene demasiados caracteres consecutivos (por ejemplo, abcde).",
        "entities.user.errors.password.tooShort": "La contraseña es demasiado corta.",
        "entities.user.errors.password.missingDigits": "La contraseña debe contener al menos un dígito.",
        "entities.user.errors.password.maximumNumberOfCharacterOccurrences": "La contraseña utiliza el mismo caracter demasiadas veces.",
        "entities.user.errors.password.missingSpecialCharacters": "La contraseña debe tener al menos un caracter especial.",
        "entities.user.errors.password.includesUsername": "La contraseña no debería incluir su nombre de usuario.",
        "entities.user.errors.password.restrictedPasswordPhrase": "La contraseña no puede contener frases de contraseña restringidas.",
        "entities.user.errors.password.passwordResetTooManyTimesToday": "La contraseña ya ha sido cambiada demasiadas veces hoy.<br/>Contacte con su supervisor.",
        "entities.user.errors.password.repeatsPreviouslyUsedPasswords": "Ya ha usado esta contraseña.<br/>Introduzca una nueva contraseña.",

        "entities.user.errors.general.invalidLengthOrPattern": "El texto supera la longitud permitida o utiliza un formato no compatible.",
        "entities.user.errors.general.uniqueness.violation": "Esto ya está en uso.",
        "entities.user.errors.general.mandatoryField": "Campo obligatorio.",
        "entities.user.errors.general.invalidRangeValue": "Valor incorrecto.",
        "entities.user.errors.general.lastAdminUser": "Eliminar el administrador solo es posible cuando haya otro usuario definido como administrador, con permisos administrativos completos.",
        "entities.user.errors.general.selfAdminRemove": "No puede eliminar el perfil del administrador usted mismo.",
        "entities.user.errors.outdated.revision.error": "No hemos podido guardar este usuario porque alguien está editándolo actualmente.",
        "entities.user.errors.entity.was.deleted": "No hemos podido guardar este usuario porque alguien lo ha eliminado.",

        "entities.lob.errors.name.required": "El nombre es obligatorio.",
        "entities.lob.errors.name.duplicated": "El nombre ya existe.",
        "entities.lob.errors.name.length": "El nombre no puede superar los 100 caracteres.",
        "entities.lob.errors.description.length": "La descripción no puede superar los 300 caracteres.",
        "entities.lob.errors.outdated.revision.error": "No hemos podido guardar esta línea de negocio porque alguien más está editándola actualmente.",
        "entities.lob.errors.entity.was.deleted": "No hemos podrido guardar esta línea porque alguien la ha eliminado.",
        "entities.lob.delete.error.general": "La línea de negocio no puede eliminarse",
        "entities.lob.delete.error.dependencies": "Esta línea de negocio no puede eliminarse porque está asignada a las siguientes entidades:<br>{0}",
        "entities.lob.delete.error.dependencies.field.users": "Usuarios",
        "entities.lob.delete.error.dependencies.field.cannedResponses": "Contenido predefinido",
        "entities.lob.delete.error.dependencies.field.campaigns": "Campañas",
        "entities.lob.delete.error.dependencies.field.skills": "Habilidades",

        "entities.agentReason.errors.text.required": "Se requiere el motivo personalizado.",
        "entities.agentReason.errors.text.duplicated": "El motivo personalizado ya existe.",
        "entities.agentReason.errors.text.length": "El motivo personalizado no puede superar los 100 caracteres.",
        "entities.agentReason.errors.outdated.revision": "No hemos podido guardar este motivo personalizado porque alguien está editándolo actualmente.",
        "entities.agentReason.errors.maxEntities": "Ha alcanzado el número máximo de motivos para el estado Ausente.",
        "entities.agentReason.errors.text.noChanges": "No se han realizado cambios.",
        "entities.agentReason.errors.already.deleted": "El estado seleccionado ya no existe.",
        "entities.agentReason.errors.delete.conflict": "Este estado está siendo utilizado actualmente, y no puede eliminarse.",
        "entities.agentReason.errors.dependency.conflict": "No hemos podido guardar este estado porque alguien está editándolo actualmente.",

        "entities.appInstall.errors.name.required": "El nombre de la aplicación es obligatorio.",
        "entities.appInstall.errors.name.maxLength": "La longitud máxima del nombre de la aplicación es de 128 caracteres.",
        "entities.appInstall.errors.description.maxLength": "La longitud máxima de la descripción de la aplicación es de 256 caracteres.",
        "entities.appInstall.errors.logoUri.required": "La URL del icono es obligatoria.",
        "entities.appInstall.errors.logoUri.maxLength": "La longitud máxima de la URL del icono es de 128 caracteres.",

        "entities.scheduling.errors.startDate.required":"Se requiere la fecha de inicio.",
        "entities.scheduling.errors.endDate.required":"Se requiere la fecha final.",
        "entities.scheduling.errors.invalidTimeRangeValues": "El evento debe terminar tras su comienzo.",

        "entities.schedule.errors.name.required": "El nombre es obligatorio.",
        "entities.schedule.errors.name.maxLength": "Ha alcanzado el número máximo de caracteres permitidos.",
        "entities.schedule.errors.name.duplicate": "El nombre ya existe. Escoge un nombre diferente.",
        "entities.schedule.errors.description.maxLength": "Ha alcanzado el número máximo de caracteres permitidos.",
        "entities.schedule.errors.generalError.internalError": "Hay un problema en la lista Programación. Inténtelo de nuevo más tarde.",
        "entities.schedule.errors.duplicate": "Se ha producido un error al duplicar la plantilla Programación.",
        "entities.schedule.errors.outdated.revision": "No hemos podido guardar esta plantilla de Programación porque alguien está editándola actualmente.",
        "entities.schedule.errors.schedule.was.deleted": "No hemos podido guardar esta plantilla de Programación porque alguien la ha eliminado.",
        "entities.schedule.errors.all.off": "Configura al menos un turno que funcione.",

        "entities.specialOccasion.errors.name.required": "El nombre es obligatorio.",
        "entities.specialOccasion.errors.name.maxLength": "Ha alcanzado el número máximo de caracteres permitidos.",
        "entities.specialOccasion.errors.name.duplicate": "El nombre ya existe. Escoge un nombre diferente.",
        "entities.specialOccasion.errors.dates.required": "Se requieren las fechas de inicio y final.",
        "entities.specialOccasion.errors.description.maxLength": "Ha alcanzado el número máximo de caracteres permitidos.",
        "entities.specialOccasion.errors.generalError.internalError": "Hay un problema en la lista Ocasión especial. Inténtelo de nuevo más tarde.",
        "entities.specialOccasion.errors.duplicate": "Se ha producido un error al duplicar la plantilla Ocasión especial.",
        "entities.specialOccasion.errors.outdated.revision": "No hemos podido guardar esta plantilla de Ocasión especial porque alguien está editándola actualmente.",
        "entities.specialOccasion.errors.specialOccasion.was.deleted": "No hemos podido guardar esta plantilla de Ocasión especial porque alguien la ha eliminado.",
        "entities.specialOccasion.errors.duplicate.event": "Ya existe una ocasión con el mismo nombre y fechas.",
        "entities.specialOccasion.errors.offline.dateLimit.event": "Una ocasión sin días laborables no puede superar los 30 días.",
        "entities.specialOccasion.errors.schedule.was.deleted": "No hemos podido guardar esta plantilla de Ocasión especial porque alguien la ha eliminado.",

        "unauthorized.title": "Acceso denegado",
        "unauthorizedAction.content": "Permiso requerido para realizar esta acción",
        "unauthorizedRoute.content": "Permiso requerido para acceder a esta página",

        "months.1.full": "Enero",
        "months.1.short": "En",
        "months.2.full": "Febrero",
        "months.2.short": "Feb",
        "months.3.full": "Marzo",
        "months.3.short": "Mar",
        "months.4.full": "Abril",
        "months.4.short": "Ab",
        "months.5.full": "Mayo",
        "months.5.short": "Mayo",
        "months.6.full": "Junio",
        "months.6.short": "Jun",
        "months.7.full": "Julio",
        "months.7.short": "Jul",
        "months.8.full": "Agosto",
        "months.8.short": "Ag",
        "months.9.full": "Septiembre",
        "months.9.short": "Sep",
        "months.10.full": "Octubre",
        "months.10.short": "Oct",
        "months.11.full": "Noviembre",
        "months.11.short": "Nov",
        "months.12.full": "Diciembre",
        "months.12.short": "Dic",

        "gallery.totalItems.text": "Número total de elementos:",

        "entities.software.mobileApp.name": "Aplicación móvil",
        "entities.software.mobileApp.longDescription": "Atraiga a los consumidores a su aplicación y permítales conectar con usted como los harían con sus amigos y familia mediante mensajería en la aplicación.",
        "entities.software.mobileApp.shortDescription": "Cree relaciones a largo plazo con los usuarios de la aplicación móvil de su marca.",
        "entities.software.instructions.mobileApp.0": "Descargue el paquete LiveEngage SDK y personalícelo para adaptarse al aspecto de su marca.",
        "entities.software.instructions.mobileApp.1": "Añada el SDK a la aplicación de la marca en la ubicación que desee.",
        "entities.software.instructions.mobileApp.2": "Los consumidores pueden hacer clic en «mensaje» directamente desde la aplicación para iniciar una conversación.",
        "entities.software.instructions.mobileApp.3": "Para obtener más información, consulte nuestra <a href='https://livepersoninc.github.io/dev-hub/current/consumer-experience-ios-sdk-quick-start.html' target='_blank'>documentación de SDK iOS</a> o nuestra <a href='https://livepersoninc.github.io/dev-hub/current/android-overview.html' target='_blank'>documentación de SDK Android</a>.",

        "entities.software.cmConnector.name": "CM",
        "entities.software.cmConnector.longDescription": "Conecte textos SMS directamente a sus operaciones de forma que los consumidores puedan contactar con usted con su método de mensajería preferido.",
        "entities.software.cmConnector.shortDescription": "Esté disponible para sus consumidores en su aplicación de mensajería nativa.",
        "entities.software.instructions.cmConnector.0": "Configure su cuenta y número de CM.",
        "entities.software.instructions.cmConnector.1": "Conecte su número a través de la interfaz de LiveEngage.",

        "gallery.dependency.indicator.title.LEGoalObject": "Las siguientes campañas dependen de este objetivo:",
        "gallery.dependency.indicator.title.LEVisitorProfile": "Las siguientes campañas dependen de esta audiencia objetivo:",
        "gallery.dependency.indicator.title.LeOnSiteLocation": "Las siguientes campañas dependen de esta ubicación:",
        "gallery.dependency.indicator.title.LEVisitorBehavioural": "Las siguientes campañas dependen de este comportamiento de visitante:",
        "gallery.dependency.indicator.title.WindowConfObject": "Las siguientes campañas dependen de esta ventana de interacción:",
        "gallery.dependency.indicator.title.ACSpecialOccasion": "Las siguientes entidades dependen de este elemento de ocasión especial:",
        "gallery.dependency.indicator.title.ACWorkingHours": "Las siguientes entidades dependen de este elemento de programación:",
        "gallery.dependency.dependeeType.LECampaignObject": "Campañas:",
        "gallery.dependency.dependeeType.ACSkillObject": "Habilidades:",
        "gallery.duplicate.location.error": "Se ha producido un error al duplicar el Punto de entrada.",
        "gallery.actions.addApiBasedWindow": "Añadir ventana basada en API",
        "gallery.actions.errors.galleryItem.cannot.delete.default": "Este elemento no puede eliminarse porque está asignado a la cuenta como elemento predeterminado.",
        "gallery.actions.errors.galleryItem.cannot.delete.item.assigned.to.entity": "Este elemento no puede eliminarse porque está asignado a la actual entidad."

    };

    return Dictionary;
});
