/**
 * Created with IntelliJ IDEA.
 * User: raml
 * Date: 3/25/13
 */
define(function () {
    "use strict";

    var Dictionary = {
        "send": "Enviar",
        "dismiss": "Descartar",
        "cancel": "Cancelar",
        "save": "Guardar",

        "instructionsToBeginChat": "Envíenos un mensaje de chat si necesita ayuda.",
        "endingChatSession": "Su sesión de chat ha finalizado. Comience a escribir abajo para iniciar otro chat.",
        "noAgentAvailableInfoMsg": "Todos los agentes están ocupados, por favor, espere....",
        "stillNoAgentAvailableInfoMsg": "Los agentes siguen ocupados. ¡Le atenderemos lo antes posible!",
        "generalErrorMsg": "Se ha producido un error; no se ha enviado su mensaje. Inténtelo de nuevo más tarde.",
        "requestTranscriptButton": "¿Necesita la transcripción?",

        "profileSuccessManagersDisplayName": "Gestores de éxito",
        "profileSuccessManagerCallout": "Déjenos ayudarle a tener éxito con LiveEngage.",
        "profileSuccessManagersSkillName": "Éxito",
        "profileCampaignExpertsDisplayName": "Expertos de campañas",
        "profileCampaignExpertsCallout": "Déjenos optimizar su presupuesto.",
        "profileCampaignExpertsSkillName": "Campañas",
        "profileTechnicalSupportDisplayName": "Soporte técnico",
        "profileTechnicalSupportCallout": "Déjenos ayudarle con sus dudas técnicas.",
        "profileTechnicalSupportSkillName": "LiveEngage",
        "profileAgentConsoleDisplayName": "Área de trabajo del agente",
        "profileAgentConsoleCallout": "Déjenos ayudarle a mejorar el rendimiento y eficiencia del agente.",
        "profileAgentConsoleSkillName": "Área de trabajo del agente",

        "survey.validationRequired": "Algunos elementos no han sido completados.",
        "survey.answerRequired": "La respuesta requerida está incompleta.",
        "survey.validationRequiredIndicator": "Los elementos con * son obligatorios.",
        "survey.unexpectedError": "Se ha producido un error inesperado mientras se enviaba el cuestionario.",
        "survey.validationError": "Una o más respuestas del cuestionario no es válida.",
        "survey.defaultTitle": "Cuestionario",

        "ConnectionArea": "Área de conexión",

        "chat.endChatButton": "Finalizar chat",
        "chat.emptyChatInputField": "Escriba su mensaje aquí...",
        "chat.connectingChatSession": "Conectando con",
        "chat.participantDefaultName": "Usted",
        "chat.errorChatSessionEnded": "Su sesión de chat ha finalizado.",
        "chat.agentIsTypingTooltip": "{0} está escribiendo",
        "chat.livePersonChatWidgetLivePersonEmployees": "Empleados de LivePerson",
        "chat.livePersonChatWidgetLivePersonTeams": "Equipos",
        "chat.livePersonChatWidgetSearchAreaText": "Buscar contactos en LivePerson",
        "chat.livePersonChatWidgetNoResults": "No hemos encontrado coincidencias de búsqueda.",
        "chat.livePersonChatWidgetContactUnavailable": "Este contacto no está disponible para chatear.",
        "chat.endedMessage": "El chat ha finalizado.",
        "chat.livePersonChatWidgetGroupUnavailable": "Este equipo no está disponible; deje un mensaje.",
        "chat.endQuestion": "¿Seguro que quiere finalizar el chat?",
        "chat.connection.error": "No hemos podido conectar su chat.",
        "chat.requestTeamChat.notFound": "No se pudo encontrar un equipo que coincida para comenzar el chat.",

        "connectionPanel.kpSearch": "Buscar contenido",
        "connectionPanel.noResults": "No hemos encontrado coincidencias de búsqueda.",
        "connectionPanel.error404": "Parece que hemos perdido la cuenta de este contenido.",

        "connectionArea.icon.tooltip": "Contacte con nosotros y obtenga más información",
        "connectionArea.minimize.icon.tooltip": "Minimizar el área de conexión.",
        "content.tab.tooltip": "Más información",
        "chat.tab.tooltip": "Contacte con LivePerson",


        "newsSnippet": "Novedades",
        "pageSnippet": "En esta página",
        "areaSnippet": "En este área",
        "recentSnippet": "Visitado recientemente",
        "searchResultsSnippet": "Resultados de búsqueda",
        "relatedSnippet": "Relacionado",

        "general.error": "Se ha producido un error; actualice la página.",
        "general.notification.error": "Se ha producido un error, inténtelo de nuevo.",
        "content.is.unavailable": "Este contenido no está disponible.",

        "chat.survey.notifications.error": "Se ha producido un problema al enviar la encuesta.",
        "chat.survey.notifications.success": "Gracias por contactar con nosotros.",

        "unregisteredUser.handle.bubble": "Hable con nosotros",
        "articlePage.relatedTitle": "Quizá esté interesado en...",

        "cases.extendedView.table.status.columnHeader": "ESTADO",
        "cases.extendedView.table.subStatus.columnHeader": "SUB ESTADO",
        "cases.extendedView.table.priority.columnHeader": "PRIORIDAD",
        "cases.extendedView.table.caseNumber.columnHeader": "Nº de CASO",
        "cases.extendedView.table.subject.columnHeader": "ASUNTO",
        "cases.extendedView.table.account.columnHeader": "CUENTA",
        "cases.extendedView.table.lob.columnHeader": "LANZAMIENTO",
        "cases.extendedView.table.contactDetails.columnHeader": "CONTACTO",
        "cases.extendedView.table.creationDate.columnHeader": "CREADO",
        "cases.extendedView.table.closedDate.columnHeader": "CERRADO",
        "cases.extendedView.description": "Ver, buscar y ordenar sus casos de asistencia",
        "cases.extendedView.title": "Casos de asistencia",
        "cases.extendedView.filter.tooltip": "Mostrar opciones del filtro",
        "cases.extendedView.filter.status": "Estado",
        "cases.extendedView.filter.accountid": "ID de cuenta",
        "cases.extendedView.filter.accountname": "Nombre de la cuenta",
        "cases.extendedView.filter.business": "Lanzamiento",
        "cases.extendedView.filter.name": "Nombre actual",
        "cases.extendedView.filter.reset": "Reiniciar",
        "cases.extendedView.filter.cancel": "Cancelar",
        "cases.extendedView.filter.filter": "Filtrar",
        "cases.extendedView.action.exportAll.start": "Exportar todos los casos",
        "cases.extendedView.action.exportAll.tooltip": "Exportar todos los casos a CSV",
        "cases.extendedView.action.add.tooltip": "Crear nuevo caso",

        "cases.attachmentDownload.info.start": "Descargar adjunto. Esto puede tardar unos minutos",
        "cases.attachmentDownload.error.failed": "No se ha podido descargar el adjunto.",


        "cases.attachmentUpload.info.start": "Se ha iniciado la subida de adjuntos; por favor, espere.",
        "cases.attachmentUpload.error.fileTooBig": "¡El archivo es demasiado grande! El tamaño máx. del archivo es 5 MB.",
        "cases.attachmentUpload.error.otherError": "Se ha producido un error; inténtelo de nuevo o seleccione otro archivo.",
        "cases.attachmentUpload.upload.error": "Error al subir {filename}. Inténtelo de nuevo o contacte con el Soporte técnico de LivePerson.",
        "cases.attachmentUpload.upload.success": "La subida de {filename} se ha realizado correctamente.",
        "cases.attachmentUpload.input.selectFile": "Elegir archivo",
        "cases.attachmentUpload.input.noFile": "No se seleccionó archivo.",
        "cases.attachmentItemView.remove": "Eliminar archivo",

        "cases.ticketTab.tooltip": "Casos de asistencia técnica",
        "cases.ticketTab.ticket.tooltip": "Abrir el caso {{caseNr}} en vista detallada",
        "cases.ticketTab.actionSearch.placeholder": "Buscar casos",
        "cases.ticketTab.actionExtended.ToolTip": "Mostrar información detallada",
        "cases.ticketTab.actionNew.Text": "Crear nuevo caso",
        "cases.ticketTab.actionNew.ToolTip": "Crear nuevo caso de asistencia",
        "cases.ticketTab.openFullList": "Abrir lista completa",
        "cases.ticketTab.closeFullList": "Cerrar lista completa",
        "cases.ticketTab.createNewCase": "Crear nuevo caso",
        "cases.ticketTab.recentlyOpenedCases": "Casos abiertos recientemente",
        "cases.ticketTab.recentlyClosedCases": "Casos cerrados recientemente",
        "cases.ticketTab.recentlyClosedCasesWithBug": "Casos recientes con errores",
        "cases.ticketTab.listItem.status": "Estado",

        "cases.detailedView.caseDetails": "Detalles del caso",
        "cases.detailedView.caseSubject": "Asunto del caso",
        "cases.detailedView.caseDescription": "Descripción del caso",
        "cases.detailedView.Attachments": "Adjuntos",
        "cases.detailedView.Comments": "Comentarios",
        "cases.detailedView.caseReportDetails": "Detalles de informe del caso",
        "cases.detailedView.caseOwner": "Propietario del caso",
        "cases.detailedView.accountID": "ID de cuenta",
        "cases.detailedView.accountName": "Nombre de la cuenta",
        "cases.detailedView.contactName": "Nombre de contacto",
        "cases.detailedView.contactEmail": "Correo electrónico de contacto",
        "cases.detailedView.contactPhone": "Teléfono de contacto",
        "cases.detailedView.statusDetails": "Detalles del estado",
        "cases.detailedView.priority": "PRIORIDAD",
        "cases.detailedView.status": "Estado",
        "cases.detailedView.subStatus": "Sub-estados",
        "cases.detailedView.creationDate": "Fecha de creación",
        "cases.detailedView.lastUpdateDate": "Última fecha de actualización",
        "cases.detailedView.closedDate": "Fecha de cierre",
        "cases.detailedView.makeCaseVisible": "Hacer el caso visible para otros usuarios de la cuenta",
        "cases.detailedView.closeCase.tooltip": "Puede cerrarse reportar caso",
        "cases.detailedView.closeCase.action": "Cerrar",
        "cases.detailedView.closeCaseMessage": "Por favor, cierre este caso. Razón del cierre: {reason}.",
        "cases.detailedView.closeCase.reason.resolved": "Resuelto",
        "cases.detailedView.closeCase.reason.cancelled": "Cancelado",
        "cases.detailedView.closeCase.reason.duplicate": "Duplicar",
        "cases.detailedView.closeCase.reason.unreproducible": "Irreproducible",
        "cases.notification.success": "Éxito!",

        "cases.detailedView.nothingToSave": "No hay nada que guardar",
        "cases.createView.newCaseHeader": "Crear un nuevo caso",
        "cases.createView.disclaimer": "Nota: los problemas y consultas enviados a través de este formulario se tratarán con prioridad media. </br>Para asistencia inmediata,",
        "cases.createView.chatWithUs": "hable con nosotros.",
        "cases.createView.suggestions": "Antes de enviar su caso, hemos pensado que encontraría los siguientes artículos útiles:",
        "cases.createView.issueDescription": "Describa el problema que se ha encontrado o la consulta que desea realizar:",
        "cases.createView.replicationDescription": "Indique los pasos de replicación detallados. </br>Nota: para permitir una replicación completa del problema, incluya los nombres de inicio de sesión de los usuarios afectados:",
        "cases.createView.scopeDescription": "Estado del alcance del impacto (cuántos agentes/visitantes/usuarios del total):",
        "cases.createView.issueFirstNoticedDescription": "Cuando se notó el problema por primera vez:",
        "cases.createView.precedingChangesQuestion": "¿Se aplicaron cambios previamente al sistema o sitio web o a la interfaz del sitio web con LivePerson?",
        "cases.createView.precedingChangesDescription": "Describa el cambio, y cuándo y en qué sistema se aplicó:",
        "cases.createView.uploadAddAttachments": "Adjunte capturas de pantalla, informes, registros u otros recursos de apoyo.",
        "cases.createView.error.MandatoryField": "Para asegurar la mejor experiencia de asistencia posible, complete los cambios requeridos.",
        "cases.noData": "No existen casos de asistencia.",
        "cases.ticketTab.createCaseDataNotAvailable": "Esta función depende de los datos que aún no se han cargado. Inténtelo de nuevo en unos momentos.",
        "cases.createView.error.ContactField": "Complete la información de contacto que falta.",
        "cases.createView.caseCreation.success": "Gracias por enviar su solicitud. Puede volver al portal en cualquier momento para comprobar el estado de esta solicitud. </br> El ID del caso es {caseNumber}.",
        "cases.createView.firstNoticedDate": "Seleccione una fecha…",
        "cases.createView.serviceInterruption": "Hemos encontrado un incidente de servicio que afecta a su cuenta. Por favor consulte nuestra página de estado antes de abrir un nuevo caso, ya que este incidente puede estar conectado con el problema que está a punto de reportar.",
        "cases.createView.ServiceHealthUrl": "Estado de salud del servicio.",
        "cases.createView.caseSeverity": "Seleccione la gravedad de este caso para su operación o negocio:",
        "cases.createView.severity.Critical": "Crítica",
        "cases.createView.severity.High": "Alta",
        "cases.createView.severity.Medium": "Media",
        "cases.createView.severity.tooltip.Critical": "Hay funciones críticas de su solución/plataforma que no están disponibles",
        "cases.createView.severity.tooltip.High": "Hay funciones importantes de su solución/plataforma que no funcionan correctamente o lo hacen peor de lo normal",
        "cases.createView.severity.tooltip.Medium": "Hay funciones de su solución/plataforma que no son críticas y se están comportando de forma anormal",
       
        "cases.createView.caseTopic": "Seleccione un tema del caso: ",
        "cases.createView.casePlatform": "Seleccione una plataforma: ",
        "cases.createView.topic.Bot": "Bot",
        "cases.createView.topic.SDK": "SDK",
        "cases.createView.topic.API": "API",
        "cases.createView.topic.AgentWorkspace": "Área de trabajo del agente",
        "cases.createView.topic.Campaign": "Campaña",
        "cases.createView.topic.Reports": "Informes",
        "cases.createView.topic.General": "General",
        "cases.createView.platform.Chat": "Chat",
        "cases.createView.platform.Messaging": "Mensajería",

        "cases.createView.subView.extraAttachments": "Para que podamos resolver su caso de forma rápida, por favor adjunte a continuación:</br>(el tamaño máximo del archivo es de 5MB)",
        "cases.createView.botView.logsAttach": "Archivos de registro",
        "cases.createView.botView.frameAttach": "Archivos JS Framework",
        "cases.createView.botView.codeAttach": "Código (al menos esas partes que implementan el SDK)",

        "cases.createView.sdkView.name": "Información de SDK",
        "cases.createView.sdkView.sdkVersion": "Versión de SDK:",
        "cases.createView.sdkView.osVersion": "Versión de SO:",
        "cases.createView.sdkView.device": "Dispositivo:",
        "cases.createView.sdkView.screenAttach": "Capturas de pantalla/vídeos:",

        "cases.datetimepicker.button.now": "Ahora",
        "cases.datetimepicker.label.hours": "Horas",
        "cases.datetimepicker.label.minutes": "Minutos",
        "cases.datetimepicker.label.time": "Islas de la Línea",

        "cases.createView.suggestions.loadingMessage": "Por favor tenga paciencia mientras buscamos una posible solución.",

        "notifications.tab.tooltip": "Área de notificación",
        "notifications.noData": "No tiene ninguna notificación.",

        "notifications.password.title": "Su contraseña está a punto de caducar.",
        "notifications.password.description": "Su contraseña caducará {expiration}.",
        "notifications.password.details": "Su contraseña caducará {expiration}. Para cambiar su contraseña ahora:</br></br><ol><li>Haga clic sobre su nombre en la esquina superior derecha.</li><li>Seleccione <b>Mis datos</b> en el menú de la cuenta.</li><li>Introduzca su nueva contraseña y haga clic en<b>Guardar</b>.</li></ol></br></br>Si necesita ayuda para restablecer su contraseña, póngase en contacto con el administrador de su cuenta.",
        "notifications.password.expiration.day": "en un día",
        "notifications.password.expiration.days": "en {number} días",
        "notifications.password.expiration.today": "hoy",

        "knowledgeCenter.title": "¡Eche un vistazo al nuevo Centro de conocimientos!",
        "knowledgeCenter.line1": "Estamos encantados de informarle que los artículos de Área de conexión se han movido a nuestro nuevo <a href='https://knowledge.liveperson.com/' target='_blank'>Centro de conocimientos</a>.",
        "knowledgeCenter.line2": "El Centro de conocimientos es una nueva y completa biblioteca de documentación de productos y contenido de asistencia al cliente. También incluye un bot, Casey, que le guiará directamente al contenido más relevante.",
        "knowledgeCenter.line3": "<a href='https://knowledge.liveperson.com/' target='_blank'>Entre en el nuevo Centro de conocimiento aquí</a>."

    };

    return Dictionary;
});
