/**
 * Created with IntelliJ IDEA.
 * User: tomers
 * Date: 5/9/13
 * Time: 2:14 PM
 * To change this template use File | Settings | File Templates.
 */

define(function () {
    "use strict";

    var Dictionary = {
        "global.save" : "Guardar",
        "global.cancel" : "Cancelar",
        "global.prev" : "Anterior",
        "global.next" : "Siguiente",
        "global.edit" : "Modificar",
        "global.view" : "Vista",

        "notification.error.title": "Se produjo un error",
        "notification.try.button": "Inténtelo de nuevo",
        "notification.confirm.title": "Confirmar",
        "urlComponent.dropdown.CONTAINS.text": "Contiene",
        "urlComponent.dropdown.EXACT.text": "Exacto",
        "urlComponent.dropdown.ADVANCED.text": "Avanzado",
        "urlComponent.dropdown.CONTAINS.includeTitle.placeholder": "Introduzca una URL o título de página",
        "urlComponent.dropdown.CONTAINS.urlOnly.placeholder": "Introduzca la URL de una página",
        "urlComponent.dropdown.EXACT.includeTitle.placeholder": "Introduzca una URL o título de página.",
        "urlComponent.dropdown.EXACT.urlOnly.placeholder": "Introduzca la URL de una página",
        "urlComponent.dropdown.ADVANCED.includeTitle.placeholder": "Introduzca una URL o título de página.",
        "urlComponent.dropdown.ADVANCED.urlOnly.placeholder": "Introduzca la URL de una página",
        "urlComponent.dropdown.CONTAINS.includeTitle.toolTip": "Incluye todas las páginas cuyas URL o títulos contengan el texto.",
        "urlComponent.dropdown.CONTAINS.urlOnly.toolTip": "Incluye todas las URL que contienen el texto.",
        "urlComponent.dropdown.EXACT.includeTitle.toolTip": "Incluye todas las páginas cuyas URL o títulos coincidan con el texto.",
        "urlComponent.dropdown.EXACT.urlOnly.toolTip": "Incluye todas las URL que coinciden con el texto.",
        "urlComponent.dropdown.ADVANCED.includeTitle.toolTip": "Incluye todas las páginas cuyas URL o títulos coincidan con el regex. Tenga en cuenta que solo son compatibles $ (termina con) y * (cualquier caracter).",
        "urlComponent.dropdown.ADVANCED.urlOnly.toolTip": "Incluye todas las URL que coinciden con el regex. Tenga en cuenta que solo son compatibles $ (termina con) y * (cualquier caracter).",

        "datePickerComponent.months.1.full": "Enero",
        "datePickerComponent.months.1.short": "En",
        "datePickerComponent.months.2.full": "Febrero",
        "datePickerComponent.months.2.short": "Feb",
        "datePickerComponent.months.3.full": "Marzo",
        "datePickerComponent.months.3.short": "Mar",
        "datePickerComponent.months.4.full": "Abril",
        "datePickerComponent.months.4.short": "Ab",
        "datePickerComponent.months.5.full": "Mayo",
        "datePickerComponent.months.5.short": "Mayo",
        "datePickerComponent.months.6.full": "Junio",
        "datePickerComponent.months.6.short": "Jun",
        "datePickerComponent.months.7.full": "Julio",
        "datePickerComponent.months.7.short": "Jul",
        "datePickerComponent.months.8.full": "Agosto",
        "datePickerComponent.months.8.short": "Ag",
        "datePickerComponent.months.9.full": "Septiembre",
        "datePickerComponent.months.9.short": "Sep",
        "datePickerComponent.months.10.full": "Octubre",
        "datePickerComponent.months.10.short": "Oct",
        "datePickerComponent.months.11.full": "Noviembre",
        "datePickerComponent.months.11.short": "Nov",
        "datePickerComponent.months.12.full": "Diciembre",
        "datePickerComponent.months.12.short": "Dic",
        "datePickerComponent.days.1.full": "Domingo",
        "datePickerComponent.days.1.short": "Do",
        "datePickerComponent.days.2.full": "Lunes",
        "datePickerComponent.days.2.short": "Lu",
        "datePickerComponent.days.3.full": "Martes",
        "datePickerComponent.days.3.short": "Ma",
        "datePickerComponent.days.4.full": "Miércoles",
        "datePickerComponent.days.4.short": "Mi",
        "datePickerComponent.days.5.full": "Jueves",
        "datePickerComponent.days.5.short": "Ju",
        "datePickerComponent.days.6.full": "Viernes",
        "datePickerComponent.days.6.short": "Vi",
        "datePickerComponent.days.7.full": "Sábado",
        "datePickerComponent.days.7.short": "Sa",

        "list.newItem.defaultValue": "+ Crear",
        "list.noItems.defaultValue": "El valor no coincide",

        "editableSingleSelect.list.newItem.default": "+ Crear",
        "editableSingleSelect.error.create.default": "Cree el elemento introducido",

        "errors.illegalInput.numbersOnly": "Introduzca un número",
        "errors.illegalInput.positiveNumbersOnly": "Introduzca un número mayor que cero",
        "errors.illegalInput.positiveNumbersOnlyWithZero": "Introduzca un número mayor o igual a cero",
        "errors.illegalInput.wholeNumbersOnlyWithZero": "Introduzca un número entero (0 o mayor).",
        "errors.illegalInput.positiveNumbersOnlyWithZeroAndTwoNumAfterDecimal": "Introduzca un número mayor o igual a cero, hasta dos lugares decimales.",
        "errors.illegalInput.numbersOnlyWithZeroAndTwoNumAfterDecimal": "Introduzca un número positivo, negativo o igual a cero, con hasta dos lugares decimales.",
        "errors.illegalInput.inputToLong": "Esta entrada no puede superar los {0} caracteres.",
        "errors.illegalInput.naturalNumber": "Introduzca un número mayor que cero",
        "errors.illegalInput.alphaNumeric": "Introduzca un número con caracteres alfanuméricos.",
        "errors.illegalInput.numbersBetweenMinToMax": "Introduzca un número entre {0} y {1}",
        "errors.tagscontainer.viewValidation.registerChanges": "Pulse INTRO o TAB para enviar sus cambios.",
        "errors.tagscontainer.viewValidation.selectFromList": "Seleccione un valor existente de la lista.",
        "errors.multiselect.viewValidation.registerChanges": "Pulse INTRO o TAB para enviar sus cambios.",
        "errors.multiselect.viewValidation.findFromList": "Seleccione un elemento de la siguiente lista.",
        "errors.multiselect.viewValidation.findOrAddFromList": "Para seleccionar una palabra clave, elija un elemento de la siguiente lista o pulse ENTER o TAB.",

        "notification.layer.init": "Buscando datos {0}",
        "notification.layer.connected": "Hemos realizado un seguimiento de sus datos {0} en las últimas 24 horas.",
        "notification.layer.error": "No hemos podido comprobar los datos {0}. Inténtelo de nuevo más tarde.",
        "notification.layer.disconnected": "No hemos recibido datos {0} en las últimas 24 horas.",
        "notification.layer.disconnected.button": "Configurar seguimiento",

        "notification.layer.tracking": "actividad del carrito",
        "notification.layer.marketing.info": "fuente de marketing",
        "notification.layer.customer.info": "Información del cliente",
        "notification.layer.viewed.product": "Producto visualizado",
        "notification.layer.service.activity": "actividad del servicio",
        "notification.layer.visitor.error": "error del visitante",
        "notification.layer.personal.info": "Información personal",
        "notification.layer.transaction": "Información de la transacción",
        "notification.layer.goal.lead": "Información de cliente potencial",
        "notification.layer.location.section": "secciones",

        "notification.layer.google.init": "Buscar los datos de Google AdWords.",
        "notification.layer.google.analytics.init": "Buscar los datos de Google Analytics.",
        "notification.layer.google.connected": "Hemos recuperado correctamente los datos de su cuenta de Google AdWords.",
        "notification.layer.google.analytics.connected": "Hemos recuperado correctamente los datos de su cuenta de Google Analytics.",
        "notification.layer.google.disconnected": "No hemos recuperado correctamente los datos de su cuenta de Google AdWords.",
        "notification.layer.google.analytics.disconnected": "No hemos recibido los datos de su cuenta de Google Analytics.",
        "notification.layer.google.disconnected.button": "Conectar con Google",
        "notification.errors.unknownError" : "Se ha producido un error desconocido.",

        "timeframe.operationHours": "Horas de operación",
        "timeframe.date.startDate": "Fecha de inicio",
        "timeframe.date.endDate": "Fecha final",
        "timeframe.date.noEndDate": "Sin fecha final",
        "timeframe.time.allHours": "Todas las horas",
        "timeframe.time.to": "hasta",
        "timeframe.timeZone": "Zona horaria",
        "timeframe.forever": "Para siempre",

        "notAvailable": "N/A",

        "persona.admin.tooltip": "Crear y gestionar usuarios y configuración de la cuenta.",
        "persona.marketer.tooltip": "Crear y gestionar campañas. Realizar un seguimiento de su rendimiento y mejorarlas en base a las métricas mostradas.",
        "persona.agent.tooltip": "Ver los visitantes de su sitio Web en tiempo real, incluyendo información sobre quiénes son, su viaje digital y chats actuales.",
        "persona.automation.tooltip": "Crear y gestionar bots en sus cuentas. Utilice el \"Creador de conversación\" para crear interacciones automatizadas y gestionar los bots de proveedores de IA externos.",
        "persona.agentManagerWorkspace.tooltip": "Realice un seguimiento en tiempo real de los datos de gestión del equipo, incluyendo información sobre el estado de la cola, el rendimiento de los agentes y los datos a nivel de conversación.",

        "persona.admin.text": "USUARIOS",
        "persona.marketer.text": "CAMPAÑAS",
        "persona.agent.text": "VISITANTES",
        "persona.newAgentWorkspace.text": "CONEXIONES",
        "persona.automation.text": "AUTOMATIZACIÓN",
        "persona.agentManagerWorkspace.text": "GERENTES",

        "dependencyIndicator.more": "y muchas cosas más",

        "paging.page.label": "Página ",
        "paging.item.label": "Elemento ",
        "paging.of.label": " de ",
        "paging.clearAllSelected.text": "Borrar selección",

        "errors.no.data.404": "Parece que hemos perdido la cuenta del contenido de las páginas.",
        "refresh.data": "Actualizar",

        "image.carousel.next": "Imagen siguiente",
        "image.carousel.prev": "Imagen anterior",

        "page.dependencies.loading": "Cargando dependencias...",

        "ckeditor.plugins.link.name": "Nombre del vínculo",
        "ckeditor.plugins.link.error.url.required": "Introducir URL",

        "emoticons.angry": "enfadado",
        "emoticons.apathetic": "apático",
        "emoticons.clap": "aplauso",
        "emoticons.confused": "confundido",
        "emoticons.happy": "feliz",
        "emoticons.laugh": "reír",
        "emoticons.meh": "regular",
        "emoticons.sad": "triste",
        "emoticons.surprised": "sorprendido",
        "emoticons.thumbs_down": "mal",
        "emoticons.thumbs_up": "bien",
        "emoticons.tongue": "burla",
        "emoticons.very_happy": "muy feliz",
        "emoticons.wink": "guiño",

        "emojicons.alternate.grinning_face": "cara sonriente",
        "emojicons.alternate.smiling_face_with_open_mouth": "cara sonriente con boca abierta",
        "emojicons.alternate.winking_face": "cara con guiño",
        "emojicons.alternate.face_with_stuck_out_tongue_and_winking_eye": "cara sacando la lengua y guiñando un ojo",
        "emojicons.alternate.confused_face": "cara confundida",
        "emojicons.alternate.angry_face": "cara enfadada",
        "emojicons.alternate.thumbs_up": "bien",
        "emojicons.alternate.thumbs_down": "mal",
        "emojicons.alternate.grinning_face_with_smiling_eyes": "cara sonriente con ojos sonrientes",
        "emojicons.alternate.smiling_face_with_sunglasses": "cara sonriente con gafas de sol",
        "emojicons.alternate.face_with_tears_of_joy": "cara con lágrimas de alegría",
        "emojicons.alternate.smiling_face_with_open_mouth_and_smiling_eyes": "cara sonriente con boca abierta y ojos sonrientes",
        "emojicons.alternate.smiling_face": "cara sonriente",
        "emojicons.alternate.face_savouring_delicious_food": "cara saboreando una comida deliciosa",
        "emojicons.alternate.relieved_face": "cara aliviada",
        "emojicons.alternate.sleeping_face": "cara adormilada",
        "emojicons.alternate.anguished_face": "cara angustiada",
        "emojicons.alternate.crying_face": "cara llorando",
        "emojicons.alternate.flushed_face": "cara sonrojada",
        "emojicons.alternate.smirking_face": "cara con sonrisa burlona",
        "emojicons.alternate.unamused_face": "cara no divertida",
        "emojicons.alternate.pouting_face": "cara de morros",
        "emojicons.alternate.face_screaming_in_fear": "cara gritando de miedo",
        "emojicons.alternate.weary_face": "cara fatigada",
        "emojicons.alternate.pensive_face": "cara pensativa",
        "emojicons.alternate.clapping_hands": "manos aplaudiendo",
        "emojicons.alternate.ok_hand": "mano de OK",
        "emojicons.alternate.folded_hands": "manos cruzadas",
        "emojicons.alternate.heart": "corazón",
        "emojicons.alternate.alarm_clock": "despertador",

        "upload.fileSelectLabel.message.noFileChosen": "No se seleccionó archivo",
        "upload.iframeTitle.tooltip": "Subir archivo",

        "gridView.filter.button.filter": "Filtrar",
        "gridView.filter.button.reset":  "Reiniciar",
        "gridView.filter.multiselect.noResults":  "Sin resultados",
        "gridView.filter.timeframe.maxDaysLabel": "(Máx {0} días)",

        "gridView.loader.searching": "Buscando...",
        "gridView.loader.filtering": "Filtrando...",
        "gridView.loader.sorting": "Ordenando...",
        "gridView.loader.loading": "Cargando...",

        "gallery.set.as.default.tooltip": "Predeterminado",
        "gallery.api.based.tooltip": "Ventana basada en API",

        "agent.picture.upload.image": "Subir imagen",
        "agent.picture.delete.image": "Eliminar imagen",
        "agent.picture.disclaimer": "Tamaño recomendado: 200x200 píxeles (hasta 0,5 MB).<br/>Formatos compatibles: PNG, JPG, GIF.<br/>Tenga en cuenta que las fotos subidas pueden almacenarse en servidores externos.",

        "gridSelectedItems.numOfItems.part1": "Mostrar",////example for the next text:  Showing [Start Index]-[End Index] of [Total] items ([#] selected)
        "gridSelectedItems.numOfItems.part2": "de",
        "gridSelectedItems.numOfItems.part3": "artículos",
        "gridSelectedItems.numOfItems.selected.part1": " seleccionado",

        "schedulePicker.add.text": "Establecer días y horas",
        "schedulePicker.details.text": "Detalles:",
        "schedulePicker.timezone.text": "Zona horaria:",
        "schedulePicker.days.0": "Domingo:",
        "schedulePicker.days.1": "Lunes:",
        "schedulePicker.days.2": "Martes:",
        "schedulePicker.days.3": "Miércoles:",
        "schedulePicker.days.4": "Jueves:",
        "schedulePicker.days.5": "Viernes:",
        "schedulePicker.days.6": "Sábado:",
        "schedulePicker.allday": "Todo el día",
        "schedulePicker.custom.from": "Desde: ",
        "schedulePicker.custom.to": "A: ",

        "specialOccasionPicker.add.text": "Establecer ocasiones especiales",
        "specialOccasionPicker.details.text": "Detalles:",
        "specialOccasionPicker.timezone.text": "Zona horaria:",
        "specialOccasionPicker.occasions.single": "Se ha definido 1 ocasión",
        "specialOccasionPicker.occasions.multiple": "{0} ocasiones definidas"
    };

    return Dictionary;
});
