/**
 * Created with IntelliJ IDEA.
 * User: omerh
 * Date: 3/20/13
 * Time: 5:42 PM
 * To change this template use File | Settings | File Templates.
 */
define(function () {
    "use strict";

    var Dictionary = {
        "language": "es-ES",
        "exampleList.header": "Translated by Example dictionary",
        //Engagement widget
        "consumerTyping": "El consumidor está escribiendo...",
        "participantTyping": "El visitante está escribiendo...",
        "participantSingleNewMessage": "1 nuevo mensaje",
        "participantNewMessages": "{0} Nuevos mensajes",
        "participantDefaultName": "Visitante",
        "autoMessageBotDefaultName": "información",
        "agentDefaultName": "Agente",
        "hideEngagement": "Ocultar interacción",
        "hideConversation": "Ocultar conversación",
        "returnToQueue": "Devolver la conversación a la cola",//// MYWORD_COMPANY_LENGTH_28
        "closeConversation": "Cerrar conversación",
        "leaveConversation": "Dejar conversación",

        "CRMLink": "Abrir ventana CRM.",
        "add": "Añadir",

        //Chat
        "chatHasEnded": "El chat ha finalizado.",
        "chatHasTransferred": "El chat ha sido transferido.",
        "chatTransferTimeText": "Chat transferido: ",
        "chatEndTimeText": "Chat finalizado: ",
        "chatDurationText": "Duración: ",
        "chatPrivateLine": "Privado",
        "chatAutomatedLine": "Automatizado",
        "averageWaitTime" : "Tiempo medio de espera",

        //State widget
        "online": "En línea",
        "backIn5": "Vuelvo en seguida",
        "back_soon": "Vuelvo en seguida",
        "away": "Ausente",
        "offline": "Offline",

        //Account widget
        "aw_agentName": "Nombre:",
        "signOut": "Salir",
        "account": "Cuenta:",
        "enableDebug": "Habilitar registros",
        "disableDebug": "Deshabilitar registros",
        "muteSounds": "El sonido está apagado",
        "playSounds": "El sonido está conectado",
        "version": "{{buildVersion}}",

        //Login widget
        "accountCaps": "CUENTA:",
        "userNameCaps": "NOMBRE DE USUARIO:",
        "passwordCaps": "CONTRASEÑA:",
        "loginErrorAccount": "El número de cuenta facilitado no es válido.",
        "loginErrorLocked": "Actualmente no puede iniciar sesión. Esto podría deberse a una cuenta desactivada o que se ha alcanzado el límite máximo de agentes.",
        "loginErrorCredentials": "Se ha producido un error al iniciar sesión; verifique sus credenciales.",
        "loginHeader": "Área de interacción de visitante de LiveEngage",
        "forgotAccount": "¿Ha olvidado su número de cuenta?",
        "forgotPassword": "¿Ha olvidado su contraseña?",
        "rememberMe": "Recordarme.",
        "signIn": "Iniciar sesión.",
        "mandatoryMissing": "Complete los campos que faltan.",

        //Agent notifications
        "agentNotification.AcceptedChatSingle": "Ha aceptado 1 nueva interacción.",
        "agentNotification.AcceptedChatMulti": "Ha aceptado {0} nuevas interacciones.",
        "agentNotification.NewLineSingle": "Tiene un mensaje no leído.",
        "agentNotification.NewLineMulti": "Tiene {0} mensajes no leídos.",
        "agentNotification.NewRequestSingle": "Tiene una nueva solicitud de chat.",
        "agentNotification.NewRequestMulti": "Tiene {0} nuevas solicitudes de chat.",
        "agentNotification.OpenConversationSingle": "Tiene una nueva solicitud de conversación.",
        "agentNotification.OpenConversationMulti": "Tiene {0} nuevas solicitudes de conversación.",
        //Agent tab notifications
        "agentTabNotificationSingle": "nueva notificación",
        "agentTabNotificationMulti": "nuevas notificaciones",
        //Agent Desktop notifications
        "agentDesktopNotification.NewLineSingle": "{0} le ha enviado un mensaje",
        "agentDesktopNotification.NewWidgetNotification": "Nueva notificación de {0}",
        "agentDesktopNotification.AcceptedChatSingle": "Ha aceptado una nueva interacción",
        "agentDesktopNotification.NewRequestSingle": "Nuevo chat entrante",
        "agentDesktopNotification.NewRequestBodySingle": "Tiene un nuevo chat esperando",
        "agentDesktopNotification.NewRequestBodyMulti": "Tiene un total de {0} nuevos chats esperando",
        "agentDesktopNotification.NewOpenConversationSingle": "Nueva conversación entrante",
        "agentDesktopNotification.NewOpenConversationBodySingle": "Tiene una nueva conversación esperando",
        "agentDesktopNotification.NewOpenConversationBodyMulti": "Tiene un total de {0} nuevas conversaciones esperando",

        // Agent Paste Dialog Notifications.
        "agentDialogsNotifications.PasteToEditorNotification.title": "Mantenga la información del cliente segura",
        "agentDialogsNotifications.PasteToEditorNotification.description": "Confirme que el contenido del mensaje pertenece a este cliente",

        // Agent Summary widget
        "agentSummaryTextareaTitle": "Resumen de la conversación:",
        "agentSummaryTextareaPlaceholder": "Introducir resumen...",
        "agentSummaryDisabledMessage": "La conversación ha estado cerrada durante {0} días. No puede enviarse el Resumen de la conversación",

        //Agent Actions widget
        "AgentActionsWidgetContainer": "Resumen de la conversación",

        //Agent on-behalf widget
        "conversationOutcomes" : "Resultados de la conversación",

        //Agent outcomes widget - Submit SDEs on behalf
        "agentOutComesSubmit" : "Enviar",

        //SDE title mappings
        "purchaseTitle" : "Compra",
        "leadTitle" : "Cliente potencial",
        "serviceTitle" : "Servicio",

        //SDE states
        "sdeNoFieldsFilled": "Por favor, complete al menos un campo antes de enviar",
        "sdeSubmissionError": "No se ha podido enviar el SDE; por favor complételo e inténtelo de nuevo",
        "sdeSubmissionNotPossibleError": "Ya no puede enviar datos para esta interacción",
        "sdeSubmissionValidationError" : "Uno de los campos enviados no es válido",
        "sdeSubmissionSuccess": "Los datos se han añadido correctamente a la sesión",

        //SDE property mappings to default
        "purchasetotal" : "Total",
        "purchaseorderId" : "ID de pedido",
        "purchasecurrency": "Divisa",
        "leadcurrency": "Divisa",
        "leadtopic" : "Tema",
        "leadvalue" : "Valor",
        "leadleadId" : "ID del cliente potencial",
        "servicetopic" : "Tema",
        "servicestatus": "Estado",
        "servicecategory": "Categoría",
        "serviceserviceId": "ID del servicio",
        "servicestatusdefault" : "Seleccione un estado.",

        //Agent Survey widget
        "agentSurvey": "Cuestionario de agente.",
        "surveyErrorsGeneral": "Falta un campo obligatorio o uno o más campos no son válidos. Corrija la información y envíe de nuevo el cuestionario.",
        "surveyErrorsNoSurvey": "Necesita establecerse un cuestionario para este chat.",
        "SurveyIsInactive": "El cuestionario está inactivo.",
        "surveyErrorsNoChat": "No hay chat asociado con esta sesión.",
        "surveyErrorsSubmissionFailure": "Se ha producido un problema al enviar el cuestionario.",
        "surveySubmitted": "El cuestionario ha sido enviado.",
        "defaultSelectValue": "Seleccione una opción.",
        "surveySubmit": "Listo",
        "retryButtonTitle": "Volver a intentar",

        //Chat history widget
        "past_engagements": "Interacciónes pasados",
        "empty_chat_history_msg": "No hay registros de historial que mostrar.",
        "error_chat_history_msg": "Error al cargar las interacciones pasadas.",
        "chatHistoryError": "No se ha podido cargar el historial de interacciones.",
        "chatDurationTranscriptText": "Duración",

        "engagementsHistory_csatTitle" : "CSAT",
        "engagementsHistory_CSAT_CalcInfo_tooltip": "CSAT agregado en base a {0} de {1} conversaciones en las cuales el consumidor completó un cuestionario CSAT.",

        "surveySubmitRequiredTitle": "Enviar cuestionario",
        "surveySubmitRequiredDescription": "No ha enviado una encuesta para ese interacción. ¿Seguro que desea cerrarlo?",
        "surveySubmitRequiredOkButton": "Cerrar interacción",
        "surveySubmitRequiredCancelButton": "Cancelar",

        //Canned Answers widget
        "preDefinedContent": "Contenido predefinido",
        "preDefinedContentErrorsNoPredefinedContent": "Este chat no tiene el contenido predefinido recomendado.",
        "preDefinedContentErrorsNoChat": "No hay chat asociado con esta sesión.",

        //Offline orb widget
        "offLine": "Cerrado",
        "OfflineOrbViewController_clearAll": "Borrar todo",
        "OfflineOrbViewController_clearAll_tooltip": "Borrar todas las interacciones cerradas",
        "OfflineOrbViewController_clearAllCompleted": "Borrar todas las completadas",
        "OfflineOrbViewController_clearAllCompleted_tooltip": "Borrar todas las conversaciones sin cuestionarios pendientes",

        // Engagement orb
        "engagementOrbVisitorClosedConnectionNotification": "El visitante ha finalizado la interacción.",
        "engagementOrbChatClosedConnectionNotification": "La conversación ha finalizado.",
        "conversationOrbConsumerClosedConnectionNotification": "El consumidor ha cerrado la conversación.",
        "conversationOrbAgentManagerClosedConnectionNotification": "La conversación se ha cerrado.",
        "conversationOrbAutoClosedConnectionNotification": "El sistema ha cerrado automáticamente la conversación.",
        "conversationOrbTakeoverClosedConnectionNotification": "La conversación ha sido asumida por {0}.",
        "engagementOrbCoBrowseSessionStarted": "La sesión de CoBrowse se ha iniciado",
        "engagementOrbCoBrowseSessionEnded": "La sesión de CoNavegación ha finalizado",
        "engagementOrbCoBrowseSessionFailed": "La sesión de CoBrowse ha fallado",
        "engagementOrbCoBrowseOfferTimeOut": "Tiempo de espera agotado de la invitación de CoBrowse",
        "engagementOrbCoBrowseOfferDeclined": "Invitación a CoBrowse rechazada",
        "engagementOrbCallAccepted": "'{0}' aceptó su llamada",
        "engagementOrbCallEnded": "La llamada ha finalizado",
        "engagementOrbCallMissed": "'{0}' perdió su llamada",
        "engagementOrbCallDeclined": "'{0}' rechazó su llamada",
        "engagementOrbStepUpNotification": "Esta conversación ha sido autenticada",
        //Queue orb widget
        "waitingInQueue": "Esperando",
        "accept": "Aceptar",
        "waitForChatAccept": "Aceptando",

        "VisitorInfoViewController_email": "Dirección de correo de contacto",
        "VisitorInfoViewController_geoCountry": "País",
        "VisitorInfoViewController_country": "País",
        "VisitorInfoViewController_os": "Sistema operativo",
        "VisitorInfoViewController_operatingSystem": "Sistema operativo",
        "VisitorInfoViewController_geoTimeZone": "Zona horaria",
        "VisitorInfoViewController_skill": "Habilidad",
        "VisitorInfoViewController_browser": "Navegador",
        "VisitorInfoViewController_currentPage": "Página actual",
        "VisitorInfoViewController_previousPages": "Páginas anteriores",
        "VisitorInfoViewController_navigationHistory": "Navegación de página",
        "VisitorInfoViewController_startPageTitle": "Página",
        "VisitorInfoViewController_maxPageTitle": "de",
        "VisitorInfoViewController_sso": "SSO",
        "VisitorInfoViewController_ip": "IP",
        "VisitorInfoViewController_ipAddress": "IP",
        "VisitorInfoViewController_state": "Estado",
        "VisitorInfoViewController_title": "Título de la página",
        "VisitorInfoViewController_engagementStartTime": "Inicio del interacción",
        "VisitorInfoViewController_visitStartTime": "Inicio de la visita",
        "VisitorInfoViewController_contactID": "Identificador",
        "VisitorInfoViewController_geoCity": "Ciudad",
        "VisitorInfoViewController_geoOrg": "Organización",
        "VisitorInfoViewController_startTime": "Hora de inicio",
        "VisitorInfoViewController_endTime": "Hora de finalización",
        "VisitorInfoViewController_duration": "Duración",
        "VisitorInfoViewController_visitorId": "ID del visitante",
        "VisitorInfoViewController_referrer": "Derivador",
        "VisitorInfoViewController_agentName": "Nombre del agente",
        "VisitorInfoViewController_visitorName": "Nombre del visitante",
        "VisitorInfoViewController_consumerName": "Nombre del consumidor",
        "VisitorInfoViewController_consumerId": "ID del consumidor",
        "VisitorInfoViewController_conversationId": "ID de la conversación",



        "showMore": "Mostrar más",
        "showLess": "Mostrar menos",

        "noSkillFound": "N/A",
        "noSkillAvailable": "N/A",

        "notAvailable": "N/A",
        "unassigned": "No asignado",
        "uncategorized": "No categorizado",

        "inActiveSkill" : "Habilidad inactiva",
        "inActiveAgent" : "Agente inactivo",

        "noDataText": "No hay contenido que mostrar.",

        // ---------------- Messaging items ------------------
        "colAgentName": "NOMBRE DEL AGENTE",
        "consumerName": "NOMBRE DEL CONSUMIDOR",
        "agentGroup": "GRUPO DE AGENTES",
        "conversationInfo": "Información de la conversación",
        "phoneNumber": "NÚMERO DE MÓVIL",
        "phoneNumberTooltip": "El teléfono móvil del consumidor",
        "CSAT": "CSAT",
        "CSATTooltip": "Satisfacción del cliente según lo indica el consumidor en la conversación más reciente.",
        "SLA": "TIEMPO DE RESPUESTA",
        "SLATooltip": "Duración del tiempo restante hasta que se requiera una respuesta.",
        "SLA_days": "{0}d",
        "SLA_days_hours": "{0}d {1}h",
        "SLA_hours": "{0} h.",
        "SLA_hours_minutes": "{0}h {1}m",
        "SLA_minutes": "{0}m",
        "SLATooltip_day": "1 día",
        "SLATooltip_day_hour": "1 día 1 hora",
        "SLATooltip_day_hours": "1 día {0} horas",
        "SLATooltip_day_hour_minute": "1 día 1 hora 1 minuto",
        "SLATooltip_day_hour_minutes": "1 día 1 hora {0} minutos",
        "SLATooltip_day_hours_minute": "1 día {0} horas 1 minuto",
        "SLATooltip_day_hours_minutes": "1 día {0} horas {1} minutos",
        "SLATooltip_day_hour_minute_second": "1 día 1 hora 1 minuto 1 segundo",
        "SLATooltip_day_hour_minute_seconds": "1 día 1 hora 1 minuto {0} segundos",
        "SLATooltip_day_hour_minutes_second": "1 día 1 hora {0} minutos 1 segundo",
        "SLATooltip_day_hour_minutes_seconds": "1 día 1 hora {0} minutos {1} segundos",
        "SLATooltip_day_hours_minute_second": "1 día {0} horas 1 minuto 1 segundo",
        "SLATooltip_day_hours_minute_seconds": "1 día {0} horas 1 minuto {1} segundos",
        "SLATooltip_day_hours_minutes_second": "1 día {0} horas {1} minutos 1 segundo",
        "SLATooltip_day_hours_minutes_seconds": "1 día {0} horas {1} minutos {2} segundos",
        "SLATooltip_day_hour_second": "1 día 1 hora 1 segundo",
        "SLATooltip_day_hour_seconds": "1 día 1 hora {0} segundos",
        "SLATooltip_day_hours_second": "1 día {0} horas 1 segundo",
        "SLATooltip_day_hours_seconds": "1 día {0} horas {1} segundos",
        "SLATooltip_day_minute_second": "1 día 1 minuto 1 segundo",
        "SLATooltip_day_minute_seconds": "1 día 1 minuto {0} segundos",
        "SLATooltip_day_minutes_second": "1 día {0} minutos 1 segundo",
        "SLATooltip_day_minutes_seconds": "1 día {0} minutos {1} segundos",
        "SLATooltip_day_minute": "1 día 1 minuto",
        "SLATooltip_day_minutes": "1 día {0} minutos",
        "SLATooltip_day_second": "1 día 1 segundo",
        "SLATooltip_day_seconds": "1 día {0} segundos",
        "SLATooltip_days": "{0} días.",
        "SLATooltip_days_hour": "{0} días 1 hora",
        "SLATooltip_days_hours": "{0} días {1} horas",
        "SLATooltip_days_hour_minute": "{0} días 1 hora 1 minuto",
        "SLATooltip_days_hour_minutes": "{0} días 1 hora {1} minutos",
        "SLATooltip_days_hours_minute": "{0} días {1} horas 1 minuto",
        "SLATooltip_days_hours_minutes": "{0} días {1} horas {2} minutos",
        "SLATooltip_days_hour_minute_second": "{0} días 1 hora 1 minuto 1 segundo",
        "SLATooltip_days_hour_minute_seconds": "{0} días 1 hora 1 minuto {1} segundos",
        "SLATooltip_days_hour_minutes_second": "{0} días 1 hora {1} minutos 1 segundo",
        "SLATooltip_days_hour_minutes_seconds": "{0} días 1 hora {1} minutos {2} segundos",
        "SLATooltip_days_hours_minute_second": "{0} días {1} horas 1 minuto 1 segundo",
        "SLATooltip_days_hours_minute_seconds": "{0} días {1} horas 1 minuto {2} segundos",
        "SLATooltip_days_hours_minutes_second": "{0} días {1} horas {2} minutos 1 segundo",
        "SLATooltip_days_hours_minutes_seconds": "{0} días {1} horas {2} minutos {3} segundos",
        "SLATooltip_days_hour_second": "{0} días 1 hora 1 segundo",
        "SLATooltip_days_hour_seconds": "{0} días 1 hora {1} segundos",
        "SLATooltip_days_hours_second": "{0} días {1} horas 1 segundo",
        "SLATooltip_days_hours_seconds": "{0} días {1} horas {2} segundos",
        "SLATooltip_days_minute_second": "{0} días 1 minuto 1 segundo",
        "SLATooltip_days_minute_seconds": "{0} días 1 minuto {0} segundos",
        "SLATooltip_days_minutes_second": "{0} días {1} minutos 1 segundo",
        "SLATooltip_days_minutes_seconds": "{0} días {1} minutos {2} segundos",
        "SLATooltip_days_minute": "{0} días 1 minuto",
        "SLATooltip_days_minutes": "{0} días {1} minutos",
        "SLATooltip_days_second": "{0} días 1 segundo",
        "SLATooltip_days_seconds": "{0} días {1} segundos",
        "SLATooltip_hour": "1 hora",
        "SLATooltip_hours": "{0} horas",
        "SLATooltip_hour_minute": "1 hora 1 minuto",
        "SLATooltip_hour_minutes": "1 hora {0} minutos",
        "SLATooltip_hours_minute": "{0} horas 1 minuto",
        "SLATooltip_hours_minutes": "{0} horas {1} minutos",
        "SLATooltip_hour_minute_second": "1 hora 1 minuto 1 segundo",
        "SLATooltip_hour_minute_seconds": "1 hora 1 minuto {0} segundos",
        "SLATooltip_hour_minutes_second": "1 hora {0} minutos 1 segundo",
        "SLATooltip_hour_minutes_seconds": "1 hora {0} minutos {1} segundos",
        "SLATooltip_hours_minute_second": "{0} horas 1 minuto 1 segundo",
        "SLATooltip_hours_minute_seconds": "{0} horas 1 minuto {1} segundos",
        "SLATooltip_hours_minutes_second": "{0} horas {1} minutos 1 segundo",
        "SLATooltip_hours_minutes_seconds": "{0} horas {1} minutos {2} segundos",
        "SLATooltip_hour_second": "1 hora 1 segundo",
        "SLATooltip_hour_seconds": "1 hora {0} segundos",
        "SLATooltip_hours_second": "{0} horas 1 segundo",
        "SLATooltip_hours_seconds": "{0} horas {1} segundos",
        "SLATooltip_minute": "1 minuto",
        "SLATooltip_minutes": "{0} minutos",
        "SLATooltip_minute_second": "1 minuto 1 segundo",
        "SLATooltip_minute_seconds": "1 minuto {0} segundos",
        "SLATooltip_minutes_second": "{0} minutos 1 segundo",
        "SLATooltip_minutes_seconds": "{0} minutos {1} segundos",
        "SLATooltip_second": "1 segundo",
        "SLATooltip_seconds": "{0} segundos",

        "SLATooltipOverdue": "vencido",
        "SLATooltipOverdue_day": "1 día vencido",
        "SLATooltipOverdue_day_hour": "1 día 1 hora vencido",
        "SLATooltipOverdue_day_hours": "1 día {0} horas vencido",
        "SLATooltipOverdue_day_hour_minute": "1 día 1 hora 1 minuto vencido",
        "SLATooltipOverdue_day_hour_minutes": "1 día 1 hora {0} minutos vencido",
        "SLATooltipOverdue_day_hours_minute": "1 día {0} horas 1 minuto vencido",
        "SLATooltipOverdue_day_hours_minutes": "1 día {0} horas {1} minutos vencido",
        "SLATooltipOverdue_day_hour_minute_second": "1 día 1 hora 1 minuto 1 segundo vencido",
        "SLATooltipOverdue_day_hour_minute_seconds": "1 día 1 hora 1 minuto {0} segundos vencido",
        "SLATooltipOverdue_day_hour_minutes_second": "1 día 1 hora {0} minutos 1 segundo vencido",
        "SLATooltipOverdue_day_hour_minutes_seconds": "1 día 1 hora {0} minutos {1} segundos vencido",
        "SLATooltipOverdue_day_hours_minute_second": "1 día {0} horas 1 minuto 1 segundo vencido",
        "SLATooltipOverdue_day_hours_minute_seconds": "1 día {0} horas 1 minuto {1} segundos vencido",
        "SLATooltipOverdue_day_hours_minutes_second": "1 día {0} horas {1} minutos 1 segundo vencido",
        "SLATooltipOverdue_day_hours_minutes_seconds": "1 día {0} horas {1} minutos {2} segundos vencido",
        "SLATooltipOverdue_day_hour_second": "1 día 1 hora 1 segundo vencido",
        "SLATooltipOverdue_day_hour_seconds": "1 día 1 hora {0} segundos vencido",
        "SLATooltipOverdue_day_hours_second": "1 día {0} horas 1 segundo vencido",
        "SLATooltipOverdue_day_hours_seconds": "1 día {0} horas {1} segundos vencido",
        "SLATooltipOverdue_day_minute_second": "1 día 1 minuto 1 segundo vencido",
        "SLATooltipOverdue_day_minute_seconds": "1 día 1 minuto {0} segundos vencido",
        "SLATooltipOverdue_day_minutes_second": "1 día {0} minutos 1 segundo vencido",
        "SLATooltipOverdue_day_minutes_seconds": "1 día {0} minutos {1} segundos vencido",
        "SLATooltipOverdue_day_minute": "1 día 1 minuto {0} vencido",
        "SLATooltipOverdue_day_minutes": "1 día {0} minutos vencido",
        "SLATooltipOverdue_day_second": "1 día 1 segundo vencido",
        "SLATooltipOverdue_day_seconds": "1 día {0} segundos vencido",
        "SLATooltipOverdue_days": "{0} días vencido",
        "SLATooltipOverdue_days_hour": "{0} días 1 hora vencido",
        "SLATooltipOverdue_days_hours": "{0} días {1} horas vencido",
        "SLATooltipOverdue_days_hour_minute": "{0} días 1 hora 1 minuto vencido",
        "SLATooltipOverdue_days_hour_minutes": "{0} días 1 hora {1} minutos vencido",
        "SLATooltipOverdue_days_hours_minute": "{0} días {1} horas 1 minuto vencido",
        "SLATooltipOverdue_days_hours_minutes": "{0} días {1} horas {2} minutos vencido",
        "SLATooltipOverdue_days_hour_minute_second": "{0} días 1 hora 1 minuto 1 segundo vencido",
        "SLATooltipOverdue_days_hour_minute_seconds": "{0} días 1 hora 1 minuto {1} segundos vencido",
        "SLATooltipOverdue_days_hour_minutes_second": "{0} días 1 hora {1} minutos 1 segundo vencido",
        "SLATooltipOverdue_days_hour_minutes_seconds": "{0} días 1 hora {1} minutos {2} segundos vencido",
        "SLATooltipOverdue_days_hours_minute_second": "{0} días {1} horas 1 minuto 1 segundo vencido",
        "SLATooltipOverdue_days_hours_minute_seconds": "{0} días {1} horas 1 minuto {2} segundos vencido",
        "SLATooltipOverdue_days_hours_minutes_second": "{0} días {1} horas {2} minutos 1 segundo vencido",
        "SLATooltipOverdue_days_hours_minutes_seconds": "{0} días {1} horas {2} minutos {3} segundos vencido",
        "SLATooltipOverdue_days_hour_second": "{0} días 1 hora 1 segundo vencido",
        "SLATooltipOverdue_days_hour_seconds": "{0} días 1 hora {1} segundos vencido",
        "SLATooltipOverdue_days_hours_second": "{0} días {1} horas 1 segundo vencido",
        "SLATooltipOverdue_days_hours_seconds": "{0} días {1} horas {2} segundos vencido",
        "SLATooltipOverdue_days_minute_second": "{0} días 1 minuto 1 segundo vencido",
        "SLATooltipOverdue_days_minute_seconds": "{0} días 1 minuto {0} segundos vencido",
        "SLATooltipOverdue_days_minutes_second": "{0} días {1} minutos 1 segundo vencido",
        "SLATooltipOverdue_days_minutes_seconds": "{0} días {1} minutos {2} segundos vencido",
        "SLATooltipOverdue_days_minute": "{0} días 1 minuto {2} vencido",
        "SLATooltipOverdue_days_minutes": "{0} días {1} minutos vencido",
        "SLATooltipOverdue_days_second": "{0} días 1 segundo vencido",
        "SLATooltipOverdue_days_seconds": "{0} días {1} segundos vencido",
        "SLATooltipOverdue_hour": "1 hora vencido",
        "SLATooltipOverdue_hours": "{0} horas vencido",
        "SLATooltipOverdue_hour_minute": "1 hora 1 minuto vencido",
        "SLATooltipOverdue_hour_minutes": "1 hora {0} minutos vencido",
        "SLATooltipOverdue_hours_minute": "{0} horas 1 minuto vencido",
        "SLATooltipOverdue_hours_minutes": "{0} horas {1} minutos vencido",
        "SLATooltipOverdue_hour_minute_second": "1 hora 1 minuto 1 segundo vencido",
        "SLATooltipOverdue_hour_minute_seconds": "1 hora 1 minuto {0} segundos vencido",
        "SLATooltipOverdue_hour_minutes_second": "1 hora {0} minutos 1 segundo vencido",
        "SLATooltipOverdue_hour_minutes_seconds": "1 hora {0} minutos {1} segundos vencido",
        "SLATooltipOverdue_hours_minute_second": "{0} horas 1 minuto 1 segundo vencido",
        "SLATooltipOverdue_hours_minute_seconds": "{0} horas 1 minuto {1} segundos vencido",
        "SLATooltipOverdue_hours_minutes_second": "{0} horas {1} minutos 1 segundo vencido",
        "SLATooltipOverdue_hours_minutes_seconds": "{0} horas {1} minutos {2} segundos vencido",
        "SLATooltipOverdue_hour_second": "1 hora 1 segundo vencido",
        "SLATooltipOverdue_hour_seconds": "1 hora {0} segundos vencido",
        "SLATooltipOverdue_hours_second": "{0} horas 1 segundo vencido",
        "SLATooltipOverdue_hours_seconds": "{0} horas {1} segundos vencido",
        "SLATooltipOverdue_minute": "1 minuto vencido",
        "SLATooltipOverdue_minutes": "{0} minutos vencido",
        "SLATooltipOverdue_minute_second": "1 minuto 1 segundo vencido",
        "SLATooltipOverdue_minute_seconds": "1 minuto {0} segundos vencido",
        "SLATooltipOverdue_minutes_second": "{0} minutos 1 segundo vencido",
        "SLATooltipOverdue_minutes_seconds": "{0} minutos {1} segundos vencido",
        "SLATooltipOverdue_second": "1 segundo vencido",
        "SLATooltipOverdue_seconds": "{0} segundos vencido",

        "waitTimeTooltip_for": " durante ",
        "waitTimeTooltip_after": " tras esperar durante ",

        "unreadMessages": "La conversación tiene mensajes no leídos.",
        "conversationStatusTooltip": "Estado de la conversación.",
        "conversationSkillTooltip" : "La habilidad asignada a la conversación.",
        "unreadMessagesByAssignedAgent": "{0}mensajes no leídos por {1}{2}",
        "transferredToAgent": "Transferida a ",
        "assignedToAgent": "Asignada a ",

        "conversationClosedByManagerNotificationTitle": "Conversación cerrada",
        "conversationClosedByManagerNotificationText": "Su conversación con \"{0}\" se ha cerrado y estará disponible en su lista de conversaciones cerradas.",
        "conversationReturnedToQueueByManagerNotificationTitle": "La conversación ha vuelto a la cola",
        "conversationReturnedToQueueByManagerNotificationText": "Su conversación con \"{0}\" ha vuelto a la cola y ya no estará visible.",

        "STATE_CLOSED_CONVERSATION": "Conversación cerrada",
        "STATE_CLOSED_CONVERSATION_AGENT": "Conversación cerrada por el agente.",
        "STATE_CLOSED_CONVERSATION_CONSUMER": "Conversación cerrada por el consumidor.",
        "STATE_CLOSED_CONVERSATION_TIMEOUT": "Conversación cerrada automáticamente por el sistema.",
        "STATE_IN_CONVERSATION": "Conversación abierta",
        "URGENT_CONVERSATION": "Conversación urgente",
        "FIRST_TIME_CONVERSATION": "Primera conversación",
        "OVERDUE_CONVERSATION": "Conversación vencida",
        "IN_QUEUE_CONVERSATION" : "Conversación en la cola",
        "IN_SURVEY_CONVERSATION" : "cerrado, en cuestionario",
        "CLOSE_REASON_AGENT": "Agente",
        "CLOSE_REASON_CONSUMER": "Consumidor",
        "CLOSE_REASON_TIMEOUT": "Automático",

        "post_survey_dialogStart": "Cuestionario iniciado",
        "post_survey_dialogEnd": "Encuesta enviada.",
        "survey_in_progress": "cuestionario en progreso",
        "survey_in_progress_error_content_message": "Este mensaje o el contenido no puede enviarse porque existe un cuestionario en progreso.",

        "MESSAGE_RECEIVED": "El consumidor ha recibido el mensaje.",
        "MESSAGE_READ": "El consumidor ha leído el mensaje.",
        "MESSAGE_SENT": "El mensaje ha sido enviado al consumidor.",
        "MESSAGE_NACK": "El mensaje no pudo ser entregado al consumidor.",
        "MESSAGE_VIEWED": "El consumidor ha abierto el mensaje.",
        "MESSAGE_ERROR": "Se ha producido un error mientras el consumidor intentaba ver el mensaje.",

        "structure_content_message_failed": "Error: su mensaje no pudo ser enviado.",

        "MY_CONNECTIONS_LIST_table_title": "Conexiones abiertas",
        "MY_CONNECTIONS_LIST_table_description": "Todas las conexiones y conversaciones que están abiertas actualmente y aún tienen que ser resueltas.",
        "MY_CONNECTIONS_LIST_empty": "Sin conexiones.",
        "MY_CONNECTIONS_LIST_emptyFiltered": "No hay conexiones que coincidan que mostrar.",
        "MY_CONNECTIONS_LIST_error": "No se pudo cargar la lista Conexiones abiertas; vuelva a cargar la página.",
        "MY_CONNECTIONS_LIST_TotalItemsSingle" : "Está visualizando una conexión",
        "MY_CONNECTIONS_LIST_TotalItemsMulti" : "Está visualizando {0} conexiones",
        "MY_CONNECTIONS_LIST_PartialItems" : "Está visualizando {0}-{1} de {2} conexiones",

        "APP_CONNECTIONS_LIST_table_title": "Conexiones abiertas",
        "APP_CONNECTIONS_LIST_table_description": "Todas las conexiones y conversaciones que están abiertas actualmente y aún tienen que ser resueltas.",
        "APP_CONNECTIONS_LIST_empty": "Sin conexiones.",
        "APP_CONNECTIONS_LIST_emptyFiltered": "No hay conexiones que coincidan que mostrar.",
        "APP_CONNECTIONS_LIST_error": "No se pudo cargar la lista Conexiones abiertas; vuelva a cargar la página.",
        "APP_CONNECTIONS_LIST_TotalItemsSingle" : "Está visualizando una conexión",
        "APP_CONNECTIONS_LIST_TotalItemsMulti" : "Está visualizando {0} conexiones",
        "APP_CONNECTIONS_LIST_PartialItems" : "Está visualizando {0}-{1} de {2} conexiones",

        "CONNECTIONS_LOG_table_title": "Todas las conexiones",
        "CONNECTIONS_LOG_table_description": "Ver, ordenar y buscar conexiones y conversaciones actuales y pasadas.",
        "CONNECTIONS_LOG_empty": "Sin conexiones.",
        "CONNECTIONS_LOG_emptyFiltered": "No hay conexiones que coincidan que mostrar.",
        "CONNECTIONS_LOG_error": "No se pudo cargar la lista Todas las conexiones, por favor vuelva a cargar la página.",
        "CONNECTIONS_LOG_TotalItemsSingle" : "Está visualizando una conexión",
        "CONNECTIONS_LOG_TotalItemsMulti" : "Está visualizando {0} conexiones",
        "CONNECTIONS_LOG_PartialItems" : "Está visualizando {0}-{1} de {2} conexiones",
        "CONNECTIONS_LOG_search_caption" : "Filtrar por palabra clave:",
        "CONNECTIONS_LOG_search_caption_tooltip" : "Filtrar por palabras o frases presentes en la transcripción y/o cuestionarios.",

        "CONNECTIONS_LOG.chatStartTooltip" : "Hora en que el consumidor inició la conversación, en hora local.",
        "CONNECTIONS_LOG.conversationStatusTooltip" : "Estado de la conversación (abierta o cerrada).",
        "CONNECTIONS_LOG.sentimentTooltip" : "Puntuación de conexión significativa (MCS). Disponible actualmente en inglés y francés.",
        "CONNECTIONS_LOG.csatTooltip" : "Satisfacción del cliente puntuada de 1 a 5 como indicó el cliente al final de la conversación.",
        "CONNECTIONS_LOG.skillTooltip" : "Habilidad asignada a la conversación.",
        "CONNECTIONS_LOG.pastChatAgentNameTooltip" : "El último agente asignado a la conversación.",
        "CONNECTIONS_LOG.activeChatAgentGroupTooltip" : "El nombre del grupo de agentes del agente que fue asignado a la conversación.",
        "CONNECTIONS_LOG.pastChatAgentNameTooltipMultiValue" : "El nombre del agente(s) asignado a la conversación.",
        "CONNECTIONS_LOG.activeChatAgentGroupTooltipMultiValue" : "El grupo de agentes al que pertenece el agente asignado a la conversación.",
        "CONNECTIONS_LOG.lastMessageTimeTooltip" : "Hora del último mensaje de la conversación.",
        "CONNECTIONS_LOG.engLengthTooltip" : "Plazo de tiempo desde el que el consumidor inició la conversación hasta que fue finalizada por el agente o el consumidor.  Para las conversaciones abiertas, la duración mostrada representa el tiempo desde el inicio hasta el momento de visualizar los datos.",
        "CONNECTIONS_LOG.conversation_summary" : "buscar por palabra o frase específica que son parte del resumen de la conversación.",
        "CONNECTIONS_LOG.engagement_attributes" : "buscar por la información pasada como atributos dentro de los Atributo de interacción. Por ejemplo: nombre, correo electrónico, id del cliente, etc.",
        "CONNECTIONS_LOG.surveyNameIdTooltip" : "El nombre del cuestionario o su ID.",
        "CONNECTIONS_LOG.npsTooltip" : "La Puntuación de promoción neta del cliente desde 0 a 10, tal como la envió el cliente en el cuestionario.",
        "CONNECTIONS_LOG.fcrTooltip" : "La Resolución de la primera llamada del cliente tal como la envió el cliente en el cuestionario.",
        "CONNECTIONS_LOG.freeTextAnswerTooltip" : "Filtrar por palabras o frases específicas.",
        "CONNECTIONS_LOG.csatPCSTooltip" : "La Satisfacción del cliente del cliente desde 0 a 5, tal como la envió el cliente en el cuestionario.",

        "CONNECTIONS_LOG_disable_filter_tooltip": "Los filtros no pueden aplicarse cuando está habilitado buscar por ID de conversación",

        "CONNECTIONS_LOG_action_allConnectionsSearchOnToken": "Generar token",
        "CONNECTIONS_LOG_action_allConnectionsSearchOnTokenTooltip": "Generar un token de formulario seguro que le permita buscar el formulario en las conversaciones.",
        "generateTokenTitle": "Generación de token.",
        "copyToken": "Copiar token",
        "generateTokenFailedTitle": "Se ha producido un error.",
        "generateTokenFailedMessage": "No se ha podido generar un token, por favor, inténtelo de nuevo.",
        "generateTokenPciCompliantFailedMessage": "No se ha podido generar el token - El Formulario seguro no está disponible.",
        "tryAgain": "Inténtelo de nuevo",

        "MESSAGING_AGENT_LIST_table_title" : "Agentes de mensajería",
        "MESSAGING_AGENT_LIST_table_description" : "Lista de agentes de mensajería con sesión iniciada, incluyendo información sobre su disponibilidad, KPIs de conversación y rendimiento.",
        "MESSAGING_AGENT_LIST_empty": "No hay agentes",
        "MESSAGING_AGENT_LIST_emptyFiltered": "No hay agentes que coincidan que mostrar.",
        "MESSAGING_AGENT_LIST_error": "No se pudo cargar la lista de agentes, por favor vuelva a cargar la página.",
        "MESSAGING_AGENT_LIST_TotalItemsSingle" : "Está viendo 1 agente",
        "MESSAGING_AGENT_LIST_TotalItemsMulti" : "Está viendo {0} agentes",
        "MESSAGING_AGENT_LIST_PartialItems" : "Está viendo {0}-{1} de {2} agentes",

        "MESSAGING_AGENT_LIST_table_column_status_tooltip" : "Estado",
        "MESSAGING_AGENT_LIST_table_column_agentName" : "NOMBRE DEL AGENTE",
        "MESSAGING_AGENT_LIST_table_column_agentName_tooltip" : "Nombre del agente",
        "MESSAGING_AGENT_LIST_table_column_agent_group" : "GRUPO DE AGENTES",
        "MESSAGING_AGENT_LIST_table_column_agent_group_tooltip" : "El grupo al que se ha asignado el agente.",
        "MESSAGING_AGENT_LIST_table_column_skills" : "HABILIDADES",
        "MESSAGING_AGENT_LIST_table_column_skills_tooltip" : "Las habilidades asignadas al agente.",
        "MESSAGING_AGENT_LIST_table_column_concurrent" : "ABIERTA",
        "MESSAGING_AGENT_LIST_table_column_concurrent_tooltip" : "El número de conversaciones abiertas que han sido gestionadas por el agente.",
        "MESSAGING_AGENT_LIST_table_column_maxConcurrent" : "ABRIR MÁX",
        "MESSAGING_AGENT_LIST_table_column_maxConcurrent_tooltip" : "El número máximo configurado de conversaciones de alta intensidad.",
        "MESSAGING_AGENT_LIST_table_column_load" : "CARGA",
        "MESSAGING_AGENT_LIST_table_column_load_tooltip" : "Peso total de las conversaciones asignadas dividido por el número máximo configurado por el agente de conversaciones de alta intensidad.",
        "MESSAGING_AGENT_LIST_table_column_active" : "ACTIVA",
        "MESSAGING_AGENT_LIST_table_column_active_tooltip" : "Número de conversaciones a intensidad completa.",
        "MESSAGING_AGENT_LIST_table_column_stateDuration" : "DURACIÓN DE ESTADO",
        "MESSAGING_AGENT_LIST_table_column_stateDuration_tooltip" : "Tiempo desde que el agente cambió su estado, y si procede, el motivo específico.",
        "MESSAGING_AGENT_LIST_table_column_onlineRate" : "% EN LÍNEA",
        "MESSAGING_AGENT_LIST_table_column_onlineRate_tooltip" : "El % de tiempo que el agente ha pasado en el estado En línea de su tiempo total con sesión iniciada en las últimas 12 horas.",
        "MESSAGING_AGENT_LIST_table_column_closedConversations" : "CERRADO",
        "MESSAGING_AGENT_LIST_table_column_closedConversations_tooltip" : "Número de conversaciones propiedad del agente que fueron resueltas en las últimas 12 horas (cerradas automáticamente, o por el agente o consumidor).",

        "conversationTransferTimeText": "Conversación transferida: ",
        "conversationEndTimeText": "Conversación cerrada",
        "openConversation": "Conversación abierta",

        "isConversationResolvedTitle": "Resuelto",
        "isConversationResolvedText_true": "Sí",
        "isConversationResolvedText_false": "No",
        "isConversationResolvedTooltip_true": "El consumidor marcó esta conversación como resuelta",
        "isConversationResolvedTooltip_false": "El consumidor marcó esta conversación como no resuelta",

        // ---------------------------------------------------

        "transferEngagementTitle": "Transferir interacción",
        "transferConversationTitle": "Transferir conversación",
        "all": "Todo",
        "byAgent": "Agente",
        "bySkill": "Habilidad",
        "byAccount": "Cuenta",
        "skills": "Habilidades",
        "overloadedAgent": "Sobrecargado",
        "agentUnavailable": "Agente no disponible",
        "visitor_name": "Nombre del visitante",
        "transferEngagementTo": "Transfiriendo la interacción a ",
        "loadingAgentsAndSkills": "Recuperando agentes y habilidades desde el servidor. Por favor, espere...",
        "closingTheEngagement": "La interacción se ha transferido con éxito,<br/>Cerrando la interacción...",
        "transferFailedToRetrieveData": "No se han podido recuperar los datos de transferencia.<br/><br/>Inténtelo de nuevo.",
        "backToList": "Volver a la lista",
        "transfer": "Transferir",
        "next": "Siguiente",
        "toAgent": "Al agente",
        "toSkill": "A la habilidad",
        "currentConversationSkill": "habilidad de la conversación actual",
        "transferConversation": "Transferir conversación",
        "transferErrorTargetUnavailable": "No se ha podido transferir. Es posible que <span class=\"lpview_agent_to_transfer_name bold_name\">{0}</span> ya no esté disponible.",
        "transferWillCloseMessage": "Esto cerrará la interacción en el área de interacción del visitante.",
        "transferWillCloseConversation": "Esto eliminará la conversación de su vista.",
        "noteTitle": "Nota:",
        "search": "Buscar",
        "onlineAgents": "Agentes en linea",
        "loggedInAgents" : "Agentes con sesión iniciada",
        "transfer_by_skill_no_wait_time": "El tiempo de espera esperado no puede determinarse en este momento",
        "transfer_by_skill_expected_wait_time": "Tiempo de espera previsto: {0}",
        "disconnectedEngagementError": "Ha sido desconectado por el servidor. Un usuario con su nombre de usuario acaba de iniciar sesión en el sistema.",
        "concurrentAgentReachedError": "No se puede iniciar sesión en el área de interacción del visitante; se ha alcanzado el número máximo de usuarios simultáneos.",
        "unableToLogInError": "No se puede iniciar sesión en el área de interacción del visitante.",
        "unableToLogInTitle": "No se puede iniciar sesión",
        "loginErrorMessage" : "",

        "transferToAgentConversationNotificationTitle": "Conversación transferida",
        "transferToAgentConversationNotificationMessage": "Su conversación con {0} ha sido transferida a {1} y dejará de estar visible.",

        "transferToAgent.join.disabled": "No puede unirse a esta conversación porque ya está esperando en su cola",

        "transferToAgent.error.agentNoSkill": "El agente de destino ya no está asignado a la habilidad de destino.",
        "transferToAgent.error.agentNotInConversation": "El agente que transfiere debe ser un agente asignado o un participante unido a la conversación.",
        "transferToAgent.error.noSuchAgent": "El agente de destino no existe.",
        "transferToAgent.error.userMissingPrivilleges": "El usuario no tiene permisos para ejecutar la transferencia al agente.",
        "transferToAgent.error.closedConversation": "La conversación se ha cerrado.",
        "transferToAgent.error.closedDialog": "La conversación se ha cerrado.",
        "transferToAgent.error.noAssignedAgent": "No hay agente asignado en la conversación.",
        "transferToAgent.error.disabledFeature": "No se ha habilitado la función Transferir a agente.",
        "transferToAgent.error.noSuchSkill": "La habilidad de destino no existe.",
        "transferToAgent.error.unauthorizedUser": "Usuario no autorizado.",
        "transferToAgent.error.consumerMissingPrivilleges": "El consumidor no permitió transferir la conversación.",
        "transferToAgent.error.default": "La operación ha fallado. Inténtelo de nuevo.",

        "noAgentsFound": "No hay agentes disponibles para transferir.",
        "noSkillsFound": "No hay habilidades disponibles para transferir.",
        "noAccountFound": "No hay cuentas disponibles para transferir.",
        "help": "Ayuda",

        "contentSanitized": "Para minimizar la interferencia con su flujo de trabajo,se eliminaron elementos del contenido que envió. El contenido se mostrará al visitante según la política de administrador de su sitio Web.",
        "contentSanitizedPrivateMessage": "Para minimizar la interferencia con su flujo de trabajo,se eliminaron elementos del contenido que envió.",
        "contentTooLong": "Su mensaje contenía demasiados caracteres y no pudo ser enviado.",
        "sendLineError": "No se pudo enviar el mensaje. Compruebe su contenido e inténtelo de nuevo.",
        "systemMessageSource": "Sistema",

        "VisitorInfoWidget": "Información del visitante",
        "PCIDataWidget": "Datos PCI",
        "AgentSurveyWidget": "Cuestionario de agente.",
        "AgentSurveyMessagingWidget": "Cuestionario de agente.",
        "AgentSummaryWidget": "Resumen",
        "PreDefinedWidget": "Contenido predefinido",
        "ChatHistoryWidget": "Historial de interacciones",
        "EngagementWidget": "Chat",
        "PageNavigationWidget": "Navegación de página",
        "VisitorListEngagementWidget" : "Chat",
        "MyConnectionsEngagementWidget" : "Conversación",
        "AppConnectionsEngagementWidget" : "Conversación",
        "ConnectionsLogEngagementWidget" : "Conversación",
        "EngagementsHistoryEngagementWidget" : "Chat",
        "OperatorAlertsWidget": "Alertas",
        "VisitInfoWidget": "Información de la visita",
        "ConsumerInfoWidget": "Información del consumidor",
        "AIAssistWidget": "Acciones recomendadas",
        "csatRate": "CSAT",
        "EngagementsHistoryVisitInfoWidget": "Información de la visita",
        "transcript": "Transcripción",
        "visitorInfo": "Información del visitante",
        "pageHasNoTitle": "(La página no tiene título)",
        "sectionsLabel": "Secciones:",

        "paging_start_tooltip": "inicio",
        "paging_prev_tooltip": "Ant.",
        "paging_next_tooltip": "Siguiente",
        "paging_end_tooltip": "Finalizar",

        "OperatorAlertsDescription": "Descripción",
        "OperatorAlertsTime": "Tiempo iniciado",

        "noTitle": "Sin título",
        "endEngagementTitle": "Está a punto de finalizar la interacción con el visitante:",
        "endEngagementDescription": "Su interacción se moverá a la lista de cerradas. Aún podrá modificar la información de los visitantes.",
        "cancel": "Cancelar",
        "ok": "Aceptar",
        "confirm": "Confirmar",
        "reconnect": "Volver a conectar",
        "endEngagement": "Fin de la interacción",
        "unableToDisplayChatTranscript": "No se puede mostrar el cuestionario del chat.",
        "AreYouSure" : "¿Está seguro?",
        "StatusChange" : "Cambio de estado",
        "StatusChangeText" : "Tenga en cuenta que su estado ha cambiado a Ausente.",

        "signoutTitle": "¿Seguro que desea salir?",
        "signoutDescription": "Los chats activos pasarán a la cola de habilidades y los chats cerrados ya no estarán disponibles.",
        "signoutWarning": "Actualmente tiene sesión iniciada en una sesión de agente activa. Si tiene chats activos, se transferirán a otros agentes. Sus chats cerrados dejarán de estar disponibles.",
        "signoutWarningAsyncMessaging": "Sesión de Agente activa (actualmente, ha iniciado la sesión como Agente).",

        "connectionProblems": "Problemas de conexión",
        "connectionProblemsDescription": "Estamos experimentando problemas de conexión; por favor, sea paciente mientras el área de interacción del visitante vuelve a conectarse...",
        "pleaseWait": "Por favor espera mientras LiveEngage intenta reconectar.",
        "connectionProblemQueueOrbTooltip": "LiveEngage está reconectando; temporalmente, no podrá recibir nuevos chats.",
        "connectionProblemSendLineTooltip": "LiveEngage está reconectando; no puede enviar mensajes actualmente.",
        "connectionProblemDropdownMenuTooltip": "LiveEngage está reconectando; el menú de acciones está deshabilitado temporalmente.",

        "waitingForConversations": "Esperando conversaciones...",
        "noRecommendedContent": "No hay contenido que mostrar.",
        "noDataToDisplay": "No hay contenido que mostrar.",
        "navigateAwayWarning": "Sesión de Agente activa (actualmente, ha iniciado la sesión como Agente).",

        "hotkeysTitle": "Teclas de acceso rápido",
        "hotkeysDescription": "(Ctrl + `)",
        "quickContentTitle": "Contenido rápido",

        "hotkeyDescriptionAcceptNextChat": "Aceptar interacción",
        "hotkeyDescriptionStatusWidget": "Estado (alternar)",
        "hotkeyDescriptionFocusNavigationBack": "Interacción anterior",
        "hotkeyDescriptionFocusNavigationForward": "Próximo interacción",
        "hotkeyDescriptionCloseEngagement": "Finalizar/cerrar el interacción",
        "hotkeyDescriptionTransferEngagement": "Transferir interacción",
        "hotkeyDescriptionTransferConversation": "Transferir conversación",
        "hotkeyDescriptionSignout": "Salir",
        "hotkeyDescriptionClosedList": "Lista de cerradas",
        "hotkeyDescriptionInactiveList": "Lista de cerradas",
        "hotkeyDescriptionStatusToAway": "Cambiar estado a Ausente",
        "hotkeyDescriptionStatusToOnline": "Cambiar estado a En línea",
        "hotkeyDescriptionStatusToOccupied": "Cambiar estado a Vuelvo en seguida",
        "hotkeyDescriptionNextToTakeAction": "Próxima respuesta de la interacción",
        "hotkeyDescriptionNextActiveEngagement": "Próximo interacción activo",
        "hotkeyDescriptionPrevActiveEngagement": "Interacción activo anterior",
        "hotkeyDescriptionVisitorList": "Lista de visitantes",
        "hotkeyDescriptionVisitorTables": "Tablas de visitantes",
        "hotkeyDescriptionAcceptConversation": "Aceptar conversación",
        "hotkeyDescriptionRespondToNext": "Responder al siguiente",
        "hotkeyDescriptionHideConversation": "Ocultar conversación",
        "hotkeyDescriptionCloseConversation": "Cerrar conversación",
        "hotkeyDescriptionMyConnectionsList": "Lista de conexiones abiertas",
        "hotkeyDescriptionAppConnectionsList": "Lista de conexiones abiertas",
        "hotkeyDescriptionReturnToQueue": "Devolver la conversación a la cola",
        "hotkeyDescriptionListView": "Vista de la lista",

        "hotkeyDescriptionSignoutTooltip": "Salir de su cuenta.",
        "hotkeyDescriptionHideConversationTooltip": "Ocultar la conversación de forma que se ejecute en segundo plano y pueda reanudarse más tarde.",
        "hotkeyMyConnectionsListTooltip": "Navegar a la lista de Conexiones abiertas.",
        "hotkeyAppConnectionsListTooltip": "Navegar a la lista de Conexiones abiertas.",
        "hotkeyClosedListTooltip": "Navegar a la lista Cerradas.",
        "hotkeyListViewTooltip": "Navegar a la vista de la lista.",
        "hotkeyDescriptionAcceptConversationTooltip": "Aceptar una conversación entrante.",
        "hotkeyDescriptionReturnToQueueTooltip": "Devolver la conversación actual a la cola.",
        "hotkeyDescriptionCloseConversationTooltip": "Marcar la conversación como cerrada.",

        "alt": "Alt",
        "ctrl": "Ctrl",
        "shift": "Mayús",
        "ctrlAlt": "Alt+Ctrl",
        "ctrlShift": "Ctrl+Mayús",
        "altShift": "Alt+Mayús",
        "ctrlAltShift": "Alt+Ctrl+Mayús",

        "alphaReleaseNotesLink": "Actualizar notas",
        "alphaNote": "Esta es una aplicación alfa y no incluye todas las funcionalidades disponibles en otras consolas de LivePerson.",

        "loadWidgetURL": "Introduzca la URL del widget que desea cargar.",
        "loadWidgetTitle": "Cargar widget",

        "visitorState": "ESTADO",
        "visitorName": "NOMBRE DEL VISITANTE",
        "audience": "AUDIENCIA",
        "from": "PAÍS",
        "organization": "ORGANIZACIÓN",
        "skill": "HABILIDAD",
        "searchKeywords": "PALABRAS CLAVES",
        "currentPage": "PÁGINA ACTUAL",
        "device": "DISPOSITIVO",
        "deviceFamily": "DISPOSITIVO",
        "ip": "IP",
        "numOfViewedPages": "PÁGINAS",
        "browser": "NAVEGADOR",
        "visitStartTime": "INICIO DE LA VISITA",
        "activeChatAgentName": "APODO DEL AGENTE",
        "activeChatAgentGroup": "GRUPO DE AGENTES",
        "pastChatAgentName" : "NOMBRE DEL AGENTE",
        "chatStart" : "INICIO",
        "chatTransferEndBorder": "Chat transferido",
        "chatTransferStartBorder": "Iniciar chat con",
        "splitSessionSeparator": "Está reanudando su chat con",
        "engLength" : "DE INT.",
        "duration" : "DURACIÓN",
        "interactiveChat" : "INTERACTIVO",
        "status": "ESTADO",
        "conversationStatus": "ESTADO",
        "startPage": "PÁGINA DE INICIO",
        "MCS": "MCS",
        "chatDuration": "DURACIÓN DEL CHAT",
        "agentType": "TIPO DE AGENTE",
        "filterByAgentType": "Filtrar por tipo de agente",
        "agentTypeHuman": "Humano",
        "agentTypeBot": "Bot",





        "visitorStateTooltip": "Indica el estado del visitante.",
        "sentimentTooltip" : "Puntuación de conexión significativa (MCS). Disponible actualmente en inglés y francés.",
        "visitorNameTooltip": "Nombre del visitante de el cuestionario pre chat.",
        "audienceTooltip": "AUDIENCIA",
        "fromTooltip": "El visitante está navegando desde el país indicado.",
        "organizationTooltip": "ORGANIZACIÓN",
        "skillTooltip": "Habilidades asignadas a la interacción.",
        "nonValidSkillTooltip" : "La habilidad ya no está activa.",
        "searchKeywordsTooltip": "PALABRAS CLAVES",
        "currentPageTooltip": "El visitante está navegando por la página Web indicada.",
        "deviceTooltip": "Dispositivo que estaba usando el cliente durante el chat.",
        "ipTooltip": "IP",
        "numOfViewedPagesTooltip": "Número de páginas que el visitante ha visitado durante la sesión.",
        "browserTooltip": "NAVEGADOR",
        "deviceFamilyTooltip": "Familia de dispositivo",
        "visitStartTimeTooltip": "Hora en la que el visitante comenzó la sesión.",
        "activeChatAgentNameTooltip": "El apodo del agente aparecerá aquí cuando haya sido asignado un agente.",
        "activeChatAgentGroupTooltip": "El nombre del grupo de agentes aparecerá aquí cuando un agente haya sido asignado.",
        "pastChatAgentNameTooltip": "El agente que gestionó el chat.",
        "nonValidAgentNameTooltip" : "La habilidad ya no está activa.",
        "chatStartTooltip" : "La hora en la que el agente se conecto por primera vez con el agente. Hora en hora local.",
        "engLengthTooltip" : "Tiempo desde cuando los visitantes se conectaron a los agentes hasta que se cierra la ventana de interacción.",
        "interactiveChatTooltip" : " Una interacción se vuelve bilateral cuando el visitante introduce el texto.",
        "startPageTooltip": "La primera página del chat",
        "chatDurationTooltip": "Duración del chat",

        "selectValueBelow": "Seleccionar valor",
        "actions": "Acciones",
        "visitorList": "Lista de visitantes",
        "visitorListDescription": "Los visitantes de su sitio Web en tiempo real, incluyendo información sobre quiénes son, su viaje digital.",
        "inviteToChat": "Invitar a chat",
        "block": "Bloquear",
        "visitorListEmpty": "No hay visitantes en el sitio Web.",
        "visitorListError": "No se pudo cargar la lista de Visitantes; vuelva a cargar la página.",
        "visitorListTotalVisitorsSingle" : "1 visitante en su sitio Web",
        "visitorListTotalVisitorsMulti" : "{0} visitantes en su sitio Web",
        "visitorListShowingVisitors" : "Mostrando {0}-{1} de {2} visitantes en su sitio Web",

        "VISITOR_LIST_table_title": "Visitantes de la Web",
        "VISITOR_LIST_table_description": "Su espacio de trabajo para las conexiones en vivo con consumidores a través de la Web y los sitios móviles. Ver todas las conversaciones junto con los visitantes en tiempo real.",
        "VISITOR_LIST_empty": "No hay visitantes en el sitio Web.",
        "VISITOR_LIST_emptyFiltered": "No hay visitantes que coincidan para mostrar.",
        "VISITOR_LIST_emptyStart2End": "Ha llegado al final de la lista de visitantes.",
        "VISITOR_LIST_error": "No se pudo cargar la lista de Visitantes; vuelva a cargar la página.",
        "VISITOR_LIST_TotalItemsSingle" : "1 visitante en su sitio Web",
        "VISITOR_LIST_TotalItemsMulti" : "{0} visitantes en su sitio Web",
        "VISITOR_LIST_PartialItems" : "Mostrando {0}-{1} de {2} visitantes en su sitio Web",
        "VISITOR_LIST_PreFiltering_TotalItemsSingle" : "Hay un total de 1 visitante en su sitio Web",
        "VISITOR_LIST_PreFiltering_TotalItemsMulti" : "Hay un total de {0} visitantes en su sitio Web.",

        "ENGAGEMENTS_HISTORY_table_title": "Historial Web",
        "ENGAGEMENTS_HISTORY_table_description": "Ver, buscar y ordenar su historial del chat Web, incluyendo la información sobre transcripciones y cuestionarios.",
        "ENGAGEMENTS_HISTORY_empty": "No hay interacciones que coincidan para mostrar.",
        "ENGAGEMENTS_HISTORY_emptyFiltered": "No hay interacciones que coincidan para mostrar.",
        "ENGAGEMENTS_HISTORY_error": "Se ha producido un problema al cargar sus datos. Actualice.",
        "ENGAGEMENTS_HISTORY_TotalItemsSingle" : "1 interacción",
        "ENGAGEMENTS_HISTORY_TotalItemsMulti" : "{0} interacciones",
        "ENGAGEMENTS_HISTORY_PartialItems" : "Mostrando {0}-{1} de {2} interacciones",
        "ENGAGEMENTS_HISTORY_search_caption" : "Filtrar por palabra clave:",
        "ENGAGEMENTS_HISTORY_search_caption_tooltip" : "Filtrar por palabras o frases presentes en la transcripción y/o cuestionarios.",
        "ENGAGEMENTS_HISTORY_action_webHistoryExportToCsv" : "Exportar a CSV",
        "ENGAGEMENTS_HISTORY_action_webHistoryExportToCsv_tooltip" : "Esto exportará los resultados de su filtro/búsqueda a un archivo CSV.",
        "ENGAGEMENTS_HISTORY_action_webHistoryExportToJson" : "Exportar a JSON",
        "ENGAGEMENTS_HISTORY_action_webHistoryExportToJson_tooltip" : "Esto exportará los resultados de su filtro/búsqueda como JSON.",
        "ENGAGEMENTS_HISTORY_action_tooltip_too_many_records" : "Hay demasiados registros a exportar. Estreche su búsqueda a menos de 100.000 transcripciones, o utilice el API de historial Web para exportar todos los elementos.",
        "ENGAGEMENTS_HISTORY_notify_export_start": "Exportar historial Web",
        "ENGAGEMENTS_HISTORY_notify_export_error": "Error de exportación. Inténtelo de nuevo.",
        "ENGAGEMENTS_HISTORY_disable_filter_tooltip": "Los filtros no pueden aplicarse cuando la búsqueda por ID de interacción está habilitada.",


        "history_search_filter_transcript" : "Transcribir línea",
        "history_search_filter_surveys" : "Cuestionarios",
        "history_search_filter_SDEs" : "Atributo de interacción",
        "history_search_filter_chat_ID" : "ID de la interacción",
        "history_search_filter_transcripts" : "Transcripciones",
        "history_search_filter_conversation_ID" : "ID de la conversación",
        "history_search_filter_visitor_info" : "Información del visitante",
        "history_search_filter_response_time": "Tiempo de respuesta",
        "history_search_filter_summary": "Resumen",
        "filter_after_title_separator": ":",
        "history_search_filter_conversation_summary": "Resumen de la conversación",
        "history_search_filter_engagement_attributes": "Atributo de interacción",

        "AGENT_LIST_table_title": "Agentes",
        "AGENT_LIST_table_title_all": "Todos los agentes",
        "AGENT_LIST_table_description": "Lista de agentes en línea en tiempo real, incluyendo información sobre su disponibilidad y capacidad.",
        "AGENT_LIST_empty": "No hay agentes en línea. Filtrar estado del agente para ver los agentes con sesión iniciada.",
        "AGENT_LIST_emptyFiltered": "No hay agentes que mostrar.",
        "AGENT_LIST_error": "Se ha producido un problema al cargar sus datos. Actualice.",
        "AGENT_LIST_table_column_elapsedTimeInState": "DURACIÓN DE ESTADO",
        "AGENT_LIST_table_column_agentName": "NOMBRE DEL AGENTE",
        "AGENT_LIST_table_column_skills": "HABILIDADES",
        "AGENT_LIST_table_column_concurrent": "CHATS ACTUALES",
        "AGENT_LIST_table_column_maxConcurrent": "MÁX. SIMULTÁNEOS",
        "AGENT_LIST_table_column_status_tooltip": "Estado",
        "AGENT_LIST_table_column_elapsedTimeInState_tooltip": "Periodo de tiempo desde el que el Agente entró en el estado actual",
        "AGENT_LIST_table_column_agentName_tooltip": "El nombre del agente.<br/>Visualizaciones máx.: 100 agentes.",
        "AGENT_LIST_table_column_skills_tooltip": "Habilidades asignadas al agente.",
        "AGENT_LIST_table_column_concurrent_tooltip": "Número de chats actuales que están siendo gestionados por el agente.",
        "AGENT_LIST_table_column_maxConcurrent_tooltip": "Máximos chats simultáneos que el agente puede gestionar.",
        "AGENT_LIST_filter_skills_title": "Habilidades",
        "AGENT_LIST_nickname": "Apodo",
        "AGENT_LIST_unlimited": "Ilimitado",
        "AGENT_LIST_TotalItemsSingle" : "Está viendo 1 agente",
        "AGENT_LIST_TotalItemsMulti" : "Está viendo {0} agentes",
        "AGENT_LIST_PartialItems" : "Está viendo {0}-{1} de {2} agentes",
        "AGENT_LIST_elapsed_time_status_tooltip": "El agente ha estado en este estado durante: ",
        "STATE_NONE": "El visitante no está en el sitio Web",
        "STATE_IN_SITE": "El visitante no está visitando el sitio Web",
        "STATE_IN_CHAT": "El visitante está participando en el chat",
        "STATE_NO_CHAT": "El visitante ha rechazado el chat",
        "STATE_WAITING_FOR_CHAT": "El visitante está esperando el chat",
        "STATE_CHAT_REFUSED": "El visitante ha rechazado el chat",
        "STATE_AFTER_CHAT": "El chat ha finalizado",
        "STATE_OFFLINE_IMPRESSION" : "Visitante expuesto a chat offline",
        "STATE_REP_WANTS_TO_CHAT": "El visitante ha sido invitado al chat",
        "STATE_LEFT_SITE": "El visitante ha dejado el sitio Web",
        "STATE_REP_PUSH_CHAT": "El agente ha interactuado manualmente con un visitante en un chat",
        "STATE_SAVED": "Guardado",
        "STATE_INTERNAL": "Interno",
        // STATE_NONE: "Sin voz",
        "STATE_VISITOR_WANTS_TO_VOICE": "El visitante solicitó que se le llamara",
        "STATE_WAITING_FOR_ANSWER": "Esperando respuesta",
        "STATE_CONNECTING": "Conectando",
        "STATE_IN_CALL": "En una llamada",
        "STATE_DONE": "Desconectado",
        "STATE_ERROR": "No se pudo iniciar la llamada",
        "STATE_CONNECTING_REMOTE": "Conectando remoto",
        "STATE_IN_CALL_REMOTE": "En llamada remota",
        "STATE_REP_WANTS_TO_VOICE": "El agente solicitó que se le llamara",
        "STATE_REP_TO_REP": "Agente a agente",
        "STATE_NO_CALL": "El visitante rechazó que se le llamara",
        "STATE_WAITING_RETRY": "Esperando para volver a intentarlo",
        "STATE_IVR": "IVR",
        "STATE_SCHEDULED_CALLBACK": "Llamada programada",
        "STATE_SCHEDULED_CALLBACK_FAILURE": "Error de llamada programada",

        "joinConversation": "Unirse a conversación",
        "resumeConnection": "Reanudar conexión",
        "lostConnectionTitle": "Se ha perdido la conexión",
        "lostConnectionDescription": "Se ha perdido la conexión al servidor; reconectando...",
        "close": "Cerrar",
        "agentSessionTimedOutTitle": "Desconexión de la sesión del agente",
        "agentSessionTimedOutDescription": "Su sesión se ha desconectado. Haga clic en Aceptar para volver a conectarse.",
        "to": "A:",
        "agentName" : "Nombre del agente",
        "addComment" : "Agregar comentario",
        "privateMessage" : "Mensaje privado",
        "privateMessageDescription" : "Sólo los agentes pueden ver este mensaje.",
        "openEngagement" : "Abrir interacción",
        "send" : "Enviar",
        "unformatted_text_copyToClipboard": "Copiar como texto sin formato",
        "unformatted_text_selectAll": "Seleccionar todo el texto",
        "unformatted_text_selectAllTooltip": "Tras hacer clic en este botón, utilice su teclado o ratón para copiar y pegar el texto.",
        "try_joining_again_text": "Intentar unirse de nuevo",
        "failed_to_join_conversation_error_text": "No ha podido unirse a la conversación; inténtelo de nuevo.",

        "CHATINPUT_disabledOldConverasation": "La conversación ha estado cerrada durante {0} días y no puede reanudarse",

        "newChatReceivedTooltip" : "¡Se ha recibido un nuevo chat!",
        "newConversationReceivedTooltip" : "¡Se ha recibido una nueva conversación!",

        "maxChatsReached" : "Se ha alcanzado el límite de chats.",

        "filter_button_filter": "Filtrar",
        "filter_button_reset": "Reiniciar",
        "filter_button_set": "Establecer",

        "filter_duration_title_sla_is": "El tiempo de respuesta es",
        "filter_duration_length": "La longitud es",
        "filter_duration_longer": "Mayor que",
        "filter_duration_shorter": "Menor que",
        "filter_duration_between": "Entre",
        "filter_duration_minutes": "minutos",
        "filter_duration_and": "y",


        "filter_duration_unit_seconds": "Segundos",
        "filter_duration_unit_minutes": "Minutos",
        "filter_duration_unit_hours": "Horas",
        "filter_duration_unit_days": "Días",

        "filter_timeFrame_now": "Ahora",

        "filter_title_isAgentSurvey": "Cuestionario de agente.",
        "filter_true_button_isAgentSurvey": "Sí",
        "filter_false_button_isAgentSurvey": "No",

        "filter_title_isInteractive": "Chat interactivo",
        "filter_true_button_isInteractive": "Sí",
        "filter_false_button_isInteractive": "No",

        "filter_title_skills": "Habilidades",
        "filter_title_agents": "Nombres de agentes",
        "filter_deleted_agents_title": "Incluir agentes eliminados",
        "filter_deleted_indication": "Eliminado",
        "filter_title_agentGroups": "Grupos de agentes",
        "filter_title_device": "Dispositivo",
        "filter_title_mcs": "MCS",
        "filter_title_status": "Estado",
        "filter_title_source": "Fuente",
        "filter_title_selectSurvey": "Seleccionar un cuestionario",

        "filter_time_frame_from": "Desde",
        "filter_time_frame_to": "Hasta",

        "filter_title_agentStatus": "Estado del agente:",
        "filter_online_agentStatus": "En línea",
        "filter_back_soon_agentStatus": "Vuelvo en seguida",
        "filter_away_agentStatus": "Ausente",

        "filter_status_title_show_status" : "Mostrar estado",

        "filter_mcs_positive": "Positivo",
        "filter_mcs_negative": "Negativo",
        "filter_mcs_from": "Desde",
        "filter_mcs_to": "Hasta",

        "predefined_error": "No se ha podido cargar el contenido recomendado.",
        "predefined_errorMessage": "No se ha podido cargar el contenido predefinido.",
        "predefined_error_refresh": "Actualizar",

        "custom_widget_errorMessage": "No se pudo cargar el widget.",
        "custom_widget_errorMessage_url_too_long": "No se ha podido cargar el widget, la URL es demasiado larga.",
        "custom_widget_errorMessage_fail_to_get_data": "No se ha podido cargar el widget, no se han podido cargar los datos del visitante.",
        "custom_widget_errorInfoLink": "Más información sobre las posibles razones",
        "custom_widget_errorFallbackTextBeforeLink": "¿Ha iniciado sesión en la aplicación?",
        "custom_widget_errorFallbackLink": "Haga clic aquí,",
        "custom_widget_errorFallbackTextAfterLink": " y luego actualice el widget.",

        "pilot_mode": "Vista del coordinador",
        "custom_widget_refresh_button": "Recargando el widget con los parámetros actualizados.",

        "SENTIMENT_positive": "Chat con MCS positiva.",
        "SENTIMENT_negative": "Chat con MCS negativa.",
        "SENTIMENT_neutral": "Chat con MCS neutral.",

        "engagement_sentiment_tooltip_positive": "Se ha detectado una MCS positiva en esta conversación.",
        "engagement_sentiment_tooltip_negative": "Se ha detectado una MCS negativa en esta conversación.",
        "engagement_sentiment_message": "Se ha detectado una MCS negativa en esta conversación.",
        "engagement_failed_messages": "{0} de sus mensajes no se enviaron.",
        "engagement_failed_messages_resend": "Clic para reenviar",

        "operatorAlerts_errorMessage" : "No se han podido cargar las alertas.",

        "VISIT_INFO_errorMessage" : "No se ha podido cargar la información de la visita.",
        "VISIT_INFO_campaignInfo": "Información de campaña",
        "VISIT_INFO_goal": "Objetivo",
        "VISIT_INFO_goalDescription": "Descripción del objetivo",
        "VISIT_INFO_goalTooltip": "El objetivo definido para la campaña desde la cual se inició la conversación. El rendimiento de la campaña se mide por cuántos visitantes alcanzan el objetivo definido. Esto permite medir el éxito de la campaña.",
        "VISIT_INFO_campaignName": "Campaña",
        "VISIT_INFO_campaignDescription": "Descripción de la campaña",
        "VISIT_INFO_campaignNameTooltip": "La campaña desde la cual se inició la conversación.",
        "VISIT_INFO_chatSkill": "Habilidad de chat",
        "VISIT_INFO_engagementSkill": "Habilidad de la interacción",
        "VISIT_INFO_engagementSkillTooltip": "La habilidad definida en la interacción desde la cual se inició la conversación.",
        "VISIT_INFO_targetAudience": "Audiencia objetivo",
        "VISIT_INFO_targetAudienceDescription": "Descripción de la audiencia objetivo",
        "VISIT_INFO_targetAudienceTooltip": "La audiencia objetivo configurada para la campaña desde la cual se inició la conversación. La audiencia objetivo se utiliza para definir los atributos de los visitantes que son objetivo como parte de la campaña. Por ejemplo, los visitantes de ciertas ubicaciones geográficas que escribieron términos de búsqueda específicos para llegar al sitio web.",
        "VISIT_INFO_behavior": "Comportamiento",
        "VISIT_INFO_behaviorDescription": "Descripción del comportamiento",
        "VISIT_INFO_behaviorTooltip": "El comportamiento configurado para la interacción desde la cual se inició la conversación. Los comportamientos se utilizan para definir cuándo mostrar interacciones a los visitantes a través de su recorrido digital. Por ejemplo, cuando un visitante abandona su carrito de la compra.",
        "VISIT_INFO_lob": "Línea de negocio",
        "VISIT_INFO_lobDescription": "Descripción de la línea de negocio",
        "VISIT_INFO_lobTooltip": "La línea de negocio definida en la campaña desde la cual se inició la conversación. Las líneas de negocio indican la división o unidad de negocio que coincide.",
        "VISIT_INFO_engagementType": "Tipo de interacción",
        "VISIT_INFO_agentNote": "Nota para el agente",
        "VISIT_INFO_agentNoteTooltip": "Nota a los agentes a medida que introdujeron los ajustes desde la interacción desde la cual se inició la conversación.",
        "VISIT_INFO_source": "Fuente",
        "VISIT_INFO_sourceDescription": "De donde viene el consumidor.",
        "VISIT_INFO_sourceTooltip": "La fuente configurada para la interacción desde la cual se inició la conversación.",
        "VISIT_INFO_employeeId": "ID del empleado",
        "VISIT_INFO_engagementName": "Nombre de la interacción",
        "VISIT_INFO_engagementNameTooltip": "La interacción desde la cual se inició la conversación.",

        //these values come from the same enum as "engagementGallery.source" in campaigns
        "VISIT_INFO_offsite_WEB_SITE": "Sitio Web",
        "VISIT_INFO_offsite_SOCIAL_MEDIA": "Red social",
        "VISIT_INFO_offsite_EMAIL": "Correo electrónico",
        "VISIT_INFO_offsite_DIGITAL_ADVERTISING": "Publicidad digital",
        "VISIT_INFO_offsite_PRINT": "Imprimir",
        "VISIT_INFO_offsite_TV": "TV",
        "VISIT_INFO_offsite_IVR": "IVR",
        "VISIT_INFO_offsite_OTHER": "Otro",
        "VISIT_INFO_offsite_EXTERNAL": "API",

        "VISIT_INFO_ENGAGEMENT_INFO": "Información de interacción",
        "VISIT_INFO_ENGAGEMENT_ID": "ID",

        "VISIT_INFO_visitorInfo": "Información del visitante",
        "VISIT_INFO_visitorName": "Nombre del visitante",
        "VISIT_INFO_waitTime": "Tiempo de espera",
        "VISIT_INFO_sessionId": "ID de sesión",
        "VISIT_INFO_country": "País",
        "VISIT_INFO_countryCode": "Código de país",
        "VISIT_INFO_geoState": "Estado geo",
        "VISIT_INFO_city": "Ciudad",
        "VISIT_INFO_isp": "ISP",
        "VISIT_INFO_organization": "Organización",
        "VISIT_INFO_operatingSystem": "Sistema operativo",
        "VISIT_INFO_browser": "Navegador",
        "VISIT_INFO_chatState": "Estado del chat",
        "VISIT_INFO_referrer": "Derivador",
        "VISIT_INFO_sso": "SSO",
        "VISIT_INFO_mobileDevice": "Dispositivo",
        "VISIT_INFO_Device_DESKTOP": "Escritorio",
        "VISIT_INFO_Device_TABLET": "Tablet",
        "VISIT_INFO_Device_MOBILE": "Smartphone",
        "VISIT_INFO_Device_NO_DEVICE": "Dispositivo no disponible",
        "VISIT_INFO_mcs_positive": "Positivo",
        "VISIT_INFO_mcs_negative": "Negativo",

        "VISIT_INFO_ipAddress": "Dirección IP",

        "VISIT_INFO_chatInfo": "Información del chat",
        "VISIT_INFO_rtSessionId": "ID de sesión en tiempo real",
        "VISIT_INFO_accountId": "ID de cuenta",
        "VISIT_INFO_agentName": "Nombre del agente",
        "VISIT_INFO_agentId": "ID DEL AGENTE",
        "VISIT_INFO_agentNickname": "Apodo del agente",
        "VISIT_INFO_chatRequestedTime": "Tiempo solicitado del chat",
        "VISIT_INFO_chatStartTime": "Tiempo de inicio del chat",
        "VISIT_INFO_spectatedEngagement": "Interacción observada",

        "VISIT_INFO_searchEngine": "Motor de búsqueda",
        "VISIT_INFO_searchEngineProvider": "Proveedor de búsqueda",
        "VISIT_INFO_searchEngineKeywords": "Buscar palabras clave",

        "VISIT_INFO_preChat": "Cuestionario pre-chat",
        "VISIT_INFO_preChatQuestion": "Pregunta de cuestionario pre-chat",
        "VISIT_INFO_postChat": "Cuestionario post-chat",
        "VISIT_INFO_postChatQuestion": "Pregunta de cuestionario post-chat",
        "VISIT_INFO_agentSurvey": "Cuestionario de agente.",
        "VISIT_INFO_agentSurveyQuestion": "Pregunta de cuestionario de agente",
        "VISIT_INFO_customVariables": "Personalizar variables",
        "VISIT_INFO_customVariable": "Variable personalizada",

        "VISIT_INFO_leadGeneration": "Generación de clientes potenciales",
        "VISIT_INFO_topic": "Tema",
        "VISIT_INFO_value": "Valor",
        "VISIT_INFO_leadId": "ID del cliente potencial",

        "VISIT_INFO_transaction": "Transacción",
        "VISIT_INFO_orderId": "ID de pedido",
        "VISIT_INFO_total": "Total",
        "VISIT_INFO_sku": "SKU",
        "VISIT_INFO_productName": "Nombre del producto",
        "VISIT_INFO_price": "Precio",
        "VISIT_INFO_category": "Categoría",
        "VISIT_INFO_quantity": "Cantidad",

        "VISIT_INFO_viewedProducts": "Productos visualizados",

        "VISIT_INFO_shoppingCartUpdate": "Actualizar carrito de la compra",
        "VISIT_INFO_cartValue": "Valor total del carrito",
        "VISIT_INFO_cartNumberOfItems": "Artículos",

        "VISIT_INFO_marketingInfo": "Fuente de marketing",
        "VISIT_INFO_originatingChannel": "Canal de origen",
        "VISIT_INFO_affiliate": "Afiliado",
        "VISIT_INFO_campaignId": "ID de campaña",

        "VISIT_INFO_personalInfo": "Información personal",
        "VISIT_INFO_personalName": "Nombre",
        "VISIT_INFO_age": "Edad",
        "VISIT_INFO_birthday": "Cumpleaños",
        "VISIT_INFO_gender": "Género",
        "VISIT_INFO_company": "Empresa",
        "VISIT_INFO_address_region": "Región",
        "VISIT_INFO_address_country": "País",
        "VISIT_INFO_phone": "Número de teléfono",
        "VISIT_INFO_phoneType": "Tipo de teléfono",
        "VISIT_INFO_email": "Dirección de correo electrónico.",
        "VISIT_INFO_CONVERSATION_ID": "ID",
        "VISIT_INFO_CONVERSATION_START_TIME": "Hora de inicio",
        "VISIT_INFO_CONVERSATION_SOURCE": "Fuente",
        "VISIT_INFO_CONVERSATION_DEVICE": "Dispositivo",
        "VISIT_INFO_CONVERSATION_OS": "Sistema operativo",
        "VISIT_INFO_CONVERSATION_BROWSER": "Navegador",
        "VISIT_INFO_CONVERSATION_INFO": "Información de la conversación",
        "VISIT_INFO_CONSUMER_ID": "ID del consumidor",

        "VISIT_INFO_SOURCE_facebook": "Facecbook",
        "VISIT_INFO_SOURCE_sms": "SMS",
        "VISIT_INFO_SOURCE_line": "LÍNEA",
        "VISIT_INFO_SOURCE_google": "Google",
        "VISIT_INFO_SOURCE_apple": "Chat de negocio Apple",
        "VISIT_INFO_SOURCE_whatsapp": "WhatsApp del negocio",
        "VISIT_INFO_SOURCE_rcs": "Mensajería empresarial RCS",
        "VISIT_INFO_SOURCE_whc": "WHC",
        "VISIT_INFO_SOURCE_bmrcs": "bmrcs",
        "VISIT_INFO_SOURCE_plusmessage": "+Mensaje",
        "VISIT_INFO_SOURCE_vfrcs": "vfrcs",
        "VISIT_INFO_SOURCE_wechat": "WeChat",

        "VISIT_INFO_customerInfo": "Información del cliente",
        "VISIT_INFO_customerStatus": "Estado",
        "VISIT_INFO_customerType": "Tipo",
        "VISIT_INFO_customerId": "ID de cliente",
        "VISIT_INFO_customerBalance": "Saldo",
        "VISIT_INFO_customerRegistrationDate": "Registro",
        "VISIT_INFO_customerLastActivityDate": "Fecha del último pago",
        "VISIT_INFO_customerSocialId": "ID social",
        "VISIT_INFO_customerIMEI": "IMEI",
        "VISIT_INFO_customerUserName": "Nombre del usuario",
        "VISIT_INFO_customerCompanySize": "Tamaño de la empresa",
        "VISIT_INFO_customerAccountName": "Nombre de la cuenta",
        "VISIT_INFO_customerRole": "Función",
        "VISIT_INFO_companyBranch": "Filial de la empresa",
        "VISIT_INFO_loginStatus": "Estado de inicio de sesión",
        "VISIT_INFO_storeZipCode": "Código postal de la tienda",
        "VISIT_INFO_storeNumber": "Número de tienda",
        "VISIT_INFO_language": "Idioma",

        "VISIT_INFO_GENDER_FEMALE": "Femenino",
        "VISIT_INFO_GENDER_MALE": "Masculino",
        "VISIT_INFO_GENDER_OTHER": "Otro",

        "VISIT_INFO_visitorError": "Error del visitante",
        "VISIT_INFO_error": "Error",
        "VISIT_INFO_message": "Mensaje",
        "VISIT_INFO_code": "Código",
        "VISIT_INFO_level": "Nivel",
        "VISIT_INFO_contextId": "ID de contexto",
        "VISIT_INFO_resolved": "Resuelto",

        "VISIT_INFO_serviceActivity": "Actividad del servicio",
        "VISIT_INFO_SAID": "ID",
        "VISIT_INFO_SATopic": "Tema",
        "VISIT_INFO_SAStatus": "Estado",
        "VISIT_INFO_SACategory": "Categoría",

        "VISIT_INFO_searchedContent": "Contenido buscado",

        "CONSUMER_INFO_consumerInfo": "Información del consumidor",
        "CONSUMER_INFO_consumerName": "Nombre del consumidor",
        "Messaging_session": "Sesión de mensajería",

        "RICH_TEXT_CHAT_INPUT_sanitizeMessage": "Este contenido ha sido bloqueado en el Espacio de trabajo del agente, pero estará visible para su visitante una vez enviado.",

        // CoBrowse:
        "CoBrowse" : "CoBrowse",
        "COBROWSE_INVITE_ACCEPT_BUTTON": "Aceptar",
        "COBROWSE_INVITE_REJECT_BUTTON": "Rechazar",

        "COBROWSE_MENU_ITEM_TITLE_VIEW_ONLY": "CoBrowse - Solo ver",
        "COBROWSE_MENU_ITEM_DESCRIPTION_VIEW_ONLY": "",
        "COBROWSE_MENU_ITEM_TITLE_SHARED": "CoBrowse - Compartido",
        "COBROWSE_MENU_ITEM_DESCRIPTION_SHARED": "",
        "COBROWSE_MENU_ITEM_TITLE_END_SESSION": "Finalizar sesión CoNavegación",
        "COBROWSE_MENU_ITEM_DESCRIPTION_END_SESSION": "",

        "COBROWSE_NOTIFICATION_MESSAGE_VISITOR_PENDING_OFFER": "El visitante tiene una invitación de CoBrowse pendiente.",
        "COBROWSE_NOTIFICATION_MESSAGE_VISITOR_ACCEPTED": "El visitante ha aceptado la invitación de CoBrowse.",
        "COBROWSE_NOTIFICATION_MESSAGE_VISITOR_DECLINE": "El visitante ha rechazado la invitación de CoBrowse.",
        "COBROWSE_NOTIFICATION_MESSAGE_VISITOR_SESSION_END": "La sesión de CoNavegación ha finalizado..",
        "COBROWSE_NOTIFICATION_MESSAGE_ERROR_OFFER_TIMED_OUT": "La invitación de CoBrowse ha caducado.",
        "COBROWSE_NOTIFICATION_MESSAGE_ERROR_SERVICE_UNAVAILABLE": "El servicio CoBrowse no está disponible actualmente.",
        "COBROWSE_TRANSFER_DIALOG_MESSAGE" : "Transferir esta interacción finalizará la sesión de CoBrowse.",
        "COBROWSE_INVITE_MESSAGE_shared": "Le he invitado a unirse a una sesión de CoBrowse, donde podré acompañarle en un recorrido por el sitio Web. Para comenzar, haga clic en Aceptar.",
        "COBROWSE_INVITE_MESSAGE_view": "Le he invitado a unirse a una sesión de CoBrowse, donde podré acompañarle en un recorrido por el sitio Web. Para comenzar, haga clic en Aceptar.",
        "COBROWSE_NOTIFICATION_MESSAGE_ERROR_VISITOR_NOT_JOINED_SESSION": "El visitante ha aceptado la invitación a CoBrowse, pero no pudo conectar.",
        "COBROWSE_NOTIFICATION_MESSAGE_VISITOR_JOINED_SESSION": "El visitante se ha unido a la sesión de CoBrowse.",
        "COBROWSE_NOTIFICATION_MESSAGE_VISITOR_LEFT_SESSION": "El visitante ha salido de la sesión de CoBrowse.",
        "COBROWSE_NOTIFICATION_MESSAGE_VISITOR_OFFER_REVOKED": "Invitación a CoBrowse cancelada.",
        "COBROWSE_NOTIFICATION_MESSAGE_GENERIC_ERROR": "No se ha podido conectar con CoBrowse.",
        "COBROWSE_NOTIFICATION_MESSAGE_ERROR_PENDING_REQUEST": "Ya se ha enviado la invitación a CoBrowse. Solo puede enviarse una invitación cada vez.",
        "COBROWSE_NOTIFICATION_MESSAGE_ERROR_ACTIVE_SESSION" : "Sesión de CoBrowse en progreso.",
        "COBROWSE_RIBBON_TITLE" :  "Sesión de CoBrowse",
        "VOICE_CALL_RIBBON_TITLE" :  "Llamada de voz",
        "VIDEO_CALL_RIBBON_TITLE" :  "Llamada de vídeo",

        "CALL_NOTIFICATION_MESSAGE_VISITOR_SESSION_END" : "Estuvo en una llamada con '{0}'",
        "CALL_NOTIFICATION_MESSAGE_ERROR_OFFER_TIMED_OUT" : "'{0}' perdió su llamada",
        "CALL_NOTIFICATION_MESSAGE_VISITOR_DECLINE" : "'{0}' rechazó su llamada",

        "CONNECTIONS_STATE_FILTER_OPEN" : "Abrir",
        "CONNECTIONS_STATE_FILTER_FIRST_TIME" : "Consumidor por primera vez",
        "CONNECTIONS_STATE_FILTER_URGENT" : "Urgente",
        "CONNECTIONS_STATE_FILTER_OVERDUE" : "Abierta-vencida",
        "CONNECTIONS_STATE_FILTER_CLOSE" : "Cerrado (agente/consumidor)",
        "CONNECTIONS_STATE_FILTER_IN_QUEUE" : "En cola",


        // agent summary view
        "AGENT_SUMMARY_title": "Resumen",

        //manual sla
        "MANUAL_SLA_minutes": "Minutos",
        "MANUAL_SLA_hours": "Horas",
        "MANUAL_SLA_days": "Días",
        "MANUAL_SLA_x_minutes": "{0} Minutos",
        "MANUAL_SLA_1_hour": "1 hora",
        "MANUAL_SLA_x_hours": "{0} Hora",
        "MANUAL_SLA_1_day": "1 día",
        "MANUAL_SLA_x_days": "{0} Días",
        "MANUAL_SLA_Change_SLA_manually": "Cambiar el tiempo de respuesta manualmente:",
        "MANUAL_SLA_Header": "El tiempo de respuesta se estableció manualmente y es ahora fijo. Los mensajes enviados/recibidos no influirán en el tiempo de respuesta.",
        "MANUAL_SLA_Restore": "Restaurar tiempo de respuesta predeterminado ",

        "LABEL_custom": "Personalizar",
        "BUTTON_submit": "Enviar",

        "RESUME_CONNECTION_errorTitle": "No se puede reanudar la conexión",
        "RESUME_CONNECTION_errorDescription": "La conexión no puede reanudarse ahora mismo. Inténtelo de nuevo más tarde.",

        "ENGAGEMENT_HEADER_AUTHENTICATED_ICON_TOOLTIP" : "Este cliente está autenticado",
        "VERIFIED_DATA_TOOLTIP_SUFFIX" : " (Datos verificados)",

        "LAST_MESSAGE_TIME": "HORA DEL ÚLTIMO MENSAJE",
        "LAST_MESSAGE": "ÚLTIMO MENSAJE",
        "CONVERSATION_START_TIME": "HORA DE INICIO",
        "CONVERSATION_DEVICE": "DISPOSITIVO",
        "CONVERSATION_SOURCE_TOOLTIP": "Fuente",

        "takeover": "Asumir",
        "takeoverConversationTitle": "Asumir conversación",
        "takeoverConversationDescription": "Está a punto de asumir la conversación y asignársela a usted mismo",
        "takingOverConversation": "Asumir la conversación",
        "takeoverConversationError": "La acción de asumir no pudo completarse. <br/> Inténtelo de nuevo",
        "takeoverConversationNotificationTitle": "La conversación ha sido asumida",
        "takeoverConversationNotificationMessage": "Su conversación con {0} ha sido asumida por {1} y dejará de estar visible.",

        //PCI FORM
        "secure_form_send_event_text":	"{0} ha enviado un formulario seguro: {1}.",
        "secure_form_received_event_text" : "El visitante ha recibido un formulario seguro: {0}.",
        "secure_form_viewed_event_text": "El visitante ha visualizado un formulario seguro: {0}.",
        "secure_form_agent_viewed_event_text": "El agente ha visualizado el formulario seguro: {0}.",

        "secure_form_submit_event_text_generic": "El formulario seguro ha sido enviado.",
        "secure_form_viewed_event_text_generic": "El consumidor ha visualizado el formulario seguro.",
        "secure_form_error_event_text_generic" : "Se ha producido un error al enviar/recibir el Formulario seguro.",

        "secure_form_submmitted_text" : "El formulario se ha enviado correctamente. <br/> Para proteger su información, no se pueden volver a abrir los formularios enviados.",
        "secure_form_submit_event_text": "Se ha enviado el siguiente formulario seguro: {0}.",
        "secure_form_error_event_text" : "Se ha producido un error al enviar/recibir el formulario seguro: {0}.",
        "secure_form_aborted_event_text" : "El siguiente formulario seguro ha caducado: {0}.",
        "secure_form_expired_text" : "El formulario seguro ha caducado. Contacte con su agente para obtener ayuda.",

        "secure_forms_list_errorMessage": "No se han podido cargar los formularios seguros.",
        "secure_forms_list_error_refresh": "Volver a cargar",
        "secure_forms_list_errorInfoLink": "",

        "secure_forms_history_errorMessage": "El chat ha finalizado y ya no tiene permiso para acceder a este formulario.",
        "secure_forms_iframe_errorMessage": "No se ha podido cargar el formulario seguro.",
        "secure_forms_iframe_errorMessage_form_calculation": "No se ha podido cargar el formulario seguro. <br/> Cuando se cargue el formulario, permanezca en la página hasta que se complete la carga.",
        "secure_forms_iframe_error_refresh": "Volver a cargar",
        "secure_forms_iframe_errorInfoLink": "",

        "predefined_content_errorMessage": "No se han podido cargar los mensajes predefinidos.",
        "predefined_content_error_refresh": "Volver a cargar",
        "predefined_content_errorInfoLink": "",

        "predefined_content_tab_tooltip": "Mensajes predefinidos",
        "secure_forms_tab_tooltip": "Formularios seguros",
        "secure_forms_tooltip": "Haga clic para enviar el formulario seguro",

        "secure_forms_init_state_text" : "El formulario seguro <strong class=\'lpview_secure_forms_init_state_text_form_name\'></strong> ha sido enviado.",
        "secure_forms_init_state_display_button": "Ver formulario seguro",

        "secure_forms_logo_tooltip": "Este formulario seguro de conformidad con DSS de PCI.",
        "secure_forms_header_title" : "Éste es un formulario seguro",
        "secure_forms_header_description": "Los detalles proporcionados aquí están protegidos.",

        //IDNV
        "idnv_dropup": " Introduzca los caracteres {0} y {1} {2} de su {3}",
        "idnv_message": " Introduzca los caracteres {0} y {1} de su {2}.",
        "idnv_submit_button_tooltip": "Complete todos los campos antes de enviar.",
        "idnv_tooltip": "Haga clic para enviar una pregunta de identificación.",
        "idnv_numeric_input_tooltip":  "Introduzca un número entre 1 y 99.",

        //Photo_sharing
        "photo_sharing_image_caption": "imagen",
        "photo_sharing_image_notification": "|imagen| {0}",
        "photo_sharing_view_index": "{0} de {1} ",
        "photo_sharing_view_error": "Error al cargar imagen",

        // Audio Messaging
        "audio_messaging_caption": "audio",
        "audio_messaging_notification": "Mensaje de audio",

        "history_search_filter_status": "Estado",
        "history_search_filter_start_time": "Hora de inicio",
        "history_search_filter_skill": "Habilidad",
        "history_search_filter_agent_group": "GRUPO DE AGENTES",
        "history_search_filter_agent_MCS": "MCS",
        "history_search_filter_agent_Csat": "CSAT",
        "history_search_filter_device": "Dispositivo",
        "history_search_filter_source": "Fuente",
        "history_search_filter_agent_name": "Nombre del agente",
        "history_search_filter_duration": "Duración",
        "history_search_filter_survey_attributes": "Atributos del cuestionario",
        "history_search_filter_survey_bot_conversations": "Mostrar solo las conversaciones del bot de cuestionario",
        "history_search_filter_survey": "Cuestionario",
        "history_search_filter_survey_name": "Nombre",
        "history_search_filter_survey_id": "ID",
        "history_search_filter_survey_enter_id": "Introducir ID",
        "history_search_filter_question_brick": "Lote de preguntas",
        "history_search_filter_nps": "NPS",
        "history_search_filter_fcr": "FCR",
        "history_search_filter_fcr_yes": "Sí",
        "history_search_filter_fcr_no": "No",
        "history_search_filter_invalid_free_text_answer": "Mostrar conversaciones con respuesta no válida por parte del consumidor",
        "history_search_filter_open_question_answered": "Mostrar conversación con pregunta de texto libre respondida",
        "history_search_filter_free_text_answer": "Texto de la respuesta",
        "history_search_filter_question_brick_name_or_id": "Introduzca nombre o ID del lote",
        "history_search_filter_free_text_answer_separator": "o",
        "history_search_numeric_range_validation_error": "Intervalo no válido, \"Desde\" no puede ser mayor que \"Hasta\"",

        "statusFilterStateOpen": "Abrir",
        "statusFilterStateClose": "Cerrado",
        "statusFilterStateLocked": "Bloqueado",
        "deviceFilterStateTablet": "Tablet",
        "deviceFilterStateDesktop": "Escritorio",
        "deviceFilterStateMobile": "Móvil",
        "deviceFilterStateNA": "NA",
        "sourceFilterStateApp": "Aplicación",
        "sourceFilterStateWeb": "Web",
        "sourceFilterStateAgent": "Agente",
        "sourceFilterStateSMS": "SMS",
        "sourceFilterStateFacebook": "Facecbook",
        "conversationInQueueFilter": "Mostrar solo las conversaciones en cola",

        //Content Preview
        "content_preview_not_participant_error" : "Este mensaje no puede enviarse porque no es un participante en esta conversación. Vuelva a unirse a la conversación e inténtelo de nuevo.",
        "content_preview_error_title": "No se ha podido enviar el contenido",
        "content_preview_error_msg": "La vista previa no se ha podido cargar.<br>Póngase en contacto con el administrador de su cuenta.",
        "content_preview_conv_close_error": "Este mensaje no puede enviarse porque la conversación se ha cerrado. Vuelva a abrir la conversación e inténtelo de nuevo.",

        //Structured Content
        "structured_content_error_title": "No se ha podido enviar Contenido estructurado",
        "structured_content_preview_error_msg": "La vista previa no se ha podido cargar.<br>Póngase en contacto con el administrador de su cuenta.",
        "structured_content_length_limit_error": "Este mensaje supera el límite de {0} caracteres y no puede ser enviado. Por favor, reduzca el número de caracteres e inténtelo de nuevo.",
        "structured_content_conv_close_error": "Este mensaje no puede enviarse porque la conversación se ha cerrado. Vuelva a abrir la conversación e inténtelo de nuevo.",
        "structured_content_not_participant_error": "Este mensaje no puede enviarse porque no es un participante en esta conversación. Vuelva a unirse a la conversación e inténtelo de nuevo.",
        "structured_content_plain_text": "Contenido avanzado",
        "structured_content_render_error_title": "¡Vaya!",
        "structured_content_render_error_description": "No se ha podido cargar esta tarjeta.",
        "structured_content_unauthorized_content_error": "Su mensaje contiene contenido no autorizado y por tanto no se ha enviado al consumidor. Revise su contenido o póngase en contacto con su administrador.",

        //Quick Replies
        "quick_replies_action_reported_message": "El consumidor ha hecho clic en un botón",
        "quick_replies_render_error_title": "¡Vaya!",
        "quick_replies_render_error_description": "No se han podido cargar las respuestas rápidas.",
        "quick_replies_not_supported_for_live_chat" : "El tipo de mensaje no es compatible en el chat",

        //Bot Escalation
        "bot_escalation_visitor_info_title": "Resumen de escalación de bot",
        "bot_escalation_visitor_info_topics": "Temas identificados:",
        "bot_escalation_visitor_info_reason": "Motivo de la escalación:",
        "bot_escalation_visitor_info_duration": "Duración de la conversación:",
        "bot_escalation_visitor_info_last_topic": "Escalación a agente humano",
        "bot_escalation_chat_bubble_title": "Recapitulación de la conversación con bot",
        "bot_escalation_chat_bubble_topics": "Temas identificados:",
        "bot_escalation_chat_bubble_reason": "Motivo de la escalación:",
        "bot_escalation_chat_bubble_duration": "Duración de la conversación:",

        //amex - Online Presence
        "presence_online": "En línea",
        "presence_today": "Visto hoy por última vez a las {0}",
        "presence_yesterday": "Visto hoy por última vez ayer a las {0}",
        "presence_old": "Visto por última vez {0}",

        "agent_deleted_indication": "(Eliminado)",

        //visit info widget default tooltips
        "visitorBehavior.default.name": "Todos los comportamientos (recomendado)",
        "visitorBehavior.default.description": "Le permite dirigirse a toda la audiencia objetivo de esta campaña sin importar el comportamiento del visitante",
        "visitorProfile.default.name": "Todos los visitantes",
        "visitorProfile.default.description": "Audiencia objetivo predeterminada creada automáticamente. Tiene como objetivo a los visitantes de alto valor de su sitio Web.",

        "chatLine.state.tooltip.profane": "El mensaje contiene contenido prohibido y ha sido bloqueado.",
        "chatLine.state.tooltip.validationFailedServer": "Su texto contiene caracteres no válidos y por tanto no ha sido enviado al consumidor. Revise su contenido e inténtelo de nuevo.",

        "richTextChatLineInput.invalidInputWarningDialog.title" : "Aviso",
        "richTextChatLineInput.invalidInputWarningDialog.message" : "Su texto contiene caracteres no válidos y no puede enviarse. Revise su contenido e inténtelo de nuevo.",

        "fileSharing.error.fileType": "{0} El tipo de archivo no compatible en el canal actual del consumidor. Seleccione los tipos de archivo compatibles: {1}",
        "fileSharing.errorTitle.fileType": "Tipo de archivo no compatible.",
        "fileSharing.error.fileSize": "El tamaño del archivo supera la limitación de {0} MB",
        "fileSharing.errorTitle.fileSize": "Tamaño de archivo no compatible",
        "fileSharing.tooltip.send": "Añadir adjunto",
        "fileSharing.tooltip.disabled": "El consumidor no puede recibir los archivos",
        "fileSharing.tooltip.retry": "No se ha podido enviar el archivo. Haga clic para volver a intentarlo",
        "fileSharing.tooltip.error": "No se ha podido enviar el archivo",
        "fileSharing.tooltip.download": "Descargar",
        "fileSharing.addCaption": "Añada una leyenda",
        "fileSharing.preview": "Vista previa",
        "fileSharing.unknown_file": "DESCONOCIDO",
        "fileSharing.no_preview": "No hay vista previa disponible para este archivo. Haga clic para descargar",
        "fileSharing.file_messaging_notification": "|archivo| {0}",
        "fileSharing.file_messaging_caption": "archivo",

        "reply.message.tooltip":"Este mensaje se ha enviado usando la función Responder.",


        // AI Assist / Maven text strings
        "ai_assist_recommended_automations": "",
        "ai_assist_maven": "",
        "ai_assist_no_automations": "No hay ninguna automatización que sugerir.",
        "ai_assist_waiting_for_messages": "Esperando mensajes adicionales",
        "ai_assist_intent": "Intención",
        "ai_assist_relevance": "Relevancia",
        "ai_assist_response": "Respuesta",
        "ai_assist_vote_up": "Voto positivo",
        "ai_assist_vote_down": "Voto negativo",
        "ai_assist_send": "Enviar",
        "ai_assist_bad_intent": "La intención se malinterpretó",
        "ai_assist_bad_bot": "El bot no coincide con la intención",
        "ai_assist_score_high": "Alta",
        "ai_assist_score_medium": "Media",
        "ai_assist_score_low": "Baja",
        "ai_assist_transfer": "Transferir",
        "ai_assist_bot_can_assist": "{0} puede ayudar",
        "ai_assist_show_more": "Mostrar más",
        "ai_assist_use_article": "Usar Artículo",
        "ai_assist_select_reason": "Seleccione un motivo o escriba el suyo propio",
        "ai_assist_dropdown": "Desplegable",
        "ai_assist_bot_is_assisting": "{0} está ayudando al visitante.",
        "ai_assist_bot_remove_bot": "Puede eliminar el bot de la conversación en cualquier momento.",
        "ai_assist_paused": "Las acciones recomendadas se pausan mientras haya un bot en la conversación.",
        "ai_assist_join": "Unirse",
        "ai_assist_remove": "Eliminar",
        "ai_assist_remove_bot_from_conversation": "Eliminar bot de la conversación",


        //Smart suggestions & auto complete
        "smart_suggestions.nothing_to_suggest": "Nada que sugerir"
    };

    return Dictionary;
});
