/**
 * Created with IntelliJ IDEA.
 * User: omerh
 * Date: 3/20/13
 * Time: 5:42 PM
 * To change this template use File | Settings | File Templates.
 */
define(function () {
    "use strict";

    var Dictionary = {
        // example module dictionary, pay attention that every key should start with the module name and then the key name
        "save": "Guardar",
        "permission.tooltip.text": "Administrador - Recibe permisos completos.<br/>Agente - Puede interactuar con los visitantes en el área de trabajo del agente.<br/>Coordinador de campañas - Puede crear y publicar campañas.<br/>Coordinador de agentes - Puede interactuar con los visitantes en el área de trabajo del agente, ver y participar en los chats activos de otros agentes y enviar notificaciones privadas a los agentes.",
        "person": "Usuario",
        "person.title.add": "Añadir usuario",
        "person.title.edit": "Modificar usuario",
        "person.title.description": "Definir los detalles del perfil y los permisos del usuario.",
        "profile.details": "Detalles del perfil",
        "name": "Nombre",
        "enter.name": "Introduzca el nombre",
        "used.engagements": "Se usa para las interacciones con los visitantes",
        "also.login.name.new": "Introduzca la dirección de correo electrónico",
        "nickname": "Apodo",
        "email": "Correo electrónico",
        "permission": "Permiso",
        "enabled": "Habilitado",
        "settings": "Configuración",
        "skills": "Habilidades",
        "max.no.chats": "Nº máx. de chats activos",
        "password": "Contraseña",
        "change.password": "Cambiar contraseña",
        "new.password": "Nueva contraseña (mín. 8 caracteres)",
        "new.password.placeholder": "Deje los campos en blanco para mantener la contraseña actual",
        "curr.password": "Contraseña actual",
        "curr.placeholder": "Deje los campos en blanco para mantener la contraseña actual.",
        "retype.new.password": "Vuelva a escribir la contraseña",
        "create.skill.tags": "Crear habilidad",
        "skills.placeholder": "Asignar/crear",
        "table.header.name": "NOMBRE",
        "table.header.nickname": "APODO",
        "table.header.username": "Correo electrónico",
        "table.header.permission": "PERMISO ESTABLECIDO",
        "table.header.skill.name": "NOMBRE DE HABILIDAD",
        "table.header.description": "DESCRIPCIÓN",
        "table.header.max.wait.time": "TIEMPO MÁXIMO DE ESPERA (SEGUNDOS)",
        "skillsTable.table.noResults": "No hay habilidades que mostrar.",
        "table.label": "Usuarios",
        "table.label.description": "Crear y gestionar usuarios y sus permisos.",
        "footer.addOperator.button": "Añadir usuario",
        "footer.backToList.button": "Página de usuarios",
        "footnote.language": "El idioma de la interfaz de su cuenta LiveEngage es",
        "footnote.timezone": "y su zona horaria es",
        "footnote.timeout.system": "Se cerrará la sesión de usuario automáticamente tras una inactividad de:",
        "footnote.max.conversations": "Número máx. predeterminado de conversaciones de mensajería por agente",
        "footnote.default.sla": "Tiempo de respuesta predeterminado comprometido a conversaciones de mensajería",
        "header.action.create": "Añadir",
        "header.action.edit": "Modificar",
        "header.action.delete": "Eliminar",
        "header.action.menu": "Acción",
        "header.skillsDropdownMenuItems.skills": "Habilidades",
        "skills.action.default": "Establecer predeterminadas",
        "skills.title.description": "Gestione y cree habilidades para dirigir de forma eficiente las interacciones a los agentes apropiados.",
        "agents.permission": "agentes",
        "exportUsers.notification": "Exportando todos los usuarios, habilidades, conjuntos de permisos y grupos de agentes. Esto puede tardar unos minutos.",

        //Errors
        "EnterValidNickname": "El apodo es obligatorio.",
        "PleaseEnterValidEmail": "Introduzca un correo electrónico válido.",
        "PleaseEnterRequiredEmail": "El correo electrónico es obligatorio.",
        "EnterCurrentPassword": "Introduzca su contraseña actual.",
        "EnterValidPassword": "La contraseña debe tener al menos 8 caracteres.",
        "PleaseEnterPassword": "Introduzca una contraseña.",
        "PasswordsNotMatch": "Las contraseñas no coinciden.",
        "PleaseEnterValidWebsite": "Introduzca un sitio Web válido.",
        "FieldMandatory": "El campo es obligatorio.",
        "InvalidPassword": "Contraseña no válida.",
        "WrongCurrentPassword": "Contraseña incorrecta.",
        "EmailAlreadyExist": "El nombre o el correo de inicio de sesión ya existe.",
        "NameAlreadyExist": "El nombre ya existe.",
        "error.deletePerson.activeOperator": "El usuario está activo actualmente y no puede ser eliminado.",
        "error.complete.request": "No hemos podido completar la solicitud porque otro usuario está editando la misma entidad.",
        "error.update.settings": "No hemos podido actualizar la configuración. Inténtelo de nuevo.",

        "SkillsGalleryTitle": "Galería de habilidades",
        "SkillsGalleryTitle.description": "Gestione y cree habilidades para dirigir de forma eficiente las interacciones a los agentes apropiados.",
        "SkillsGalleryTitle.knowledgePack.text": "Más información.",
        "Done": "Listo",
        "DeleteConfirmTitle": "¿Está seguro?",
        "DeletePersonConfirmMessage": "Al eliminar {0} se eliminará completamente este usuario de LiveEngage.",
        "DeleteActionText": "Eliminar",
        "DeleteSkillConfirmMessage": "Al eliminar {0} se eliminará completamente esta habilidad de LiveEngage. Si existen interacciones asociadas con esta habilidad, no funcionarán correctamente. Para evitar esto, asocie la interacción con otra habilidad.",
        "CreateNewSkill": "Crear nueva",
        "Cancel": "Cancelar",
        "OK": "Aceptar",
        "SkillTitle": "Habilidad",
        "SkillView.CreateSkillTitle": "Añadir habilidad",
        "SkillView.EditSkillTitle": "Modificar habilidad",
        "SkillName": "Nombre",
        "SkillName.placeholder": "Nombre de habilidad",
        "SkillDesc": "Descripción",
        "SkillMaxWaitTime": "Tiempo máximo de espera de interacción",
        "SkillSeconds": "segundos",
        "SkillSaveTooltip.noChanges": "No se han realizado cambios.",
        "SkillSaveTooltip.mandatoryFields": "Todos los campos son obligatorios.",
        "addDescription.label": "+ Añadir descripción",
        "addDescription.placeholder": "Añadir descripción...",
        "deleteSkillError": "La habilidad se asigna a un usuario y podría no eliminarse.",
        "deleteSkillErrorSurveyAssigned": "La habilidad está asociada con un cuestionario pre chat y podría no eliminarse.",
        "deleteSkillErrorDefaultSkill": "La habilidad se define como habilidad predeterminada y podría no eliminarse.",
        "changeConfirmTitle": "¿Está seguro?",
        "changeConfirmMessage": "Este cambio se aplicará a todos los usuarios de LiveEngage.",
        "error.skill.already.exists": "El nombre ya existe.",

        // first time login
        "WelcomeArrowView.DialogTitle": "Bienvenido a LiveEngage",
        "WelcomeArrowView.Header": "¡Comenzar es muy fácil!",
        "WelcomeArrowView.WorkArea.Title": "Área de trabajo",
        "WelcomeArrowView.WorkArea.Text": "Aquí es donde se encuentran y se gestionan los elementos, como los detalles del visitante y las campañas.",
        "WelcomeArrowView.DataBar.Title": "Barra de datos",
        "WelcomeArrowView.DataBar.Text": "Consiga información instantánea sobre todas las áreas de rendimiento. Despliegue para revelar el Panel de datos para obtener un análisis en profundidad.",
        "WelcomeArrowView.ConnectionPanel.Title": "Panel de conexión",
        "WelcomeArrowView.ConnectionPanel.Text": "Su éxito se impulsa al combinar sus talentos con el conocimiento del equipo de LivePerson.",
        "WelcomeArrowView.Next": "Siguiente",

        "WelcomeOneTwoThreeView.Header": "¡Comenzar es muy fácil!",
        "WelcomeOneTwoThreeView.ActionItem": "Elemento de acción:",
        "WelcomeOneTwoThreeView.LiveEngageTag.Header": "Etiqueta de LiveEngage",
        "WelcomeOneTwoThreeView.LiveEngageTag.Text": "Este paso esencial le permite monitorizar los visitantes del sitio Web y facilitar los interacciónes digitales.",
        "WelcomeOneTwoThreeView.LiveEngageTag.AI": "Copie y peque la etiqueta de LiveEngage en su sitio Web.",
        "WelcomeOneTwoThreeView.Billing.Header": "Facturación",
        "WelcomeOneTwoThreeView.Billing.Text": "Comience con una versión de prueba para ver su rendimiento. Más tarde, actualice al plan de uso que mejor se ajuste a sus necesidades.",
        "WelcomeOneTwoThreeView.Billing.AI": "Introduzca la información de su cuenta.",
        "WelcomeOneTwoThreeView.StartEngaging.Header": "¡Comience a interactuar!",
        "WelcomeOneTwoThreeView.StartEngaging.Text": "Para comenzar, explore la plataforma LiveEngage y verá qué fácil es crear campañas e interacciones.",
        "WelcomeOneTwoThreeView.StartEngaging.AI": "Adelante, comprométase...",
        "WelcomeOneTwoThreeView.Done": "Listo",

        // permission groups
        "permission.value.administrator": "Administrador",
        "permission.value.agent": "Agente",
        "permission.value.campaignManager": "Coordinador de campaña",
        "permission.value.agentManager": "Coordinador de agente",

        /// number of chats
        "max.chat.value.no.chats": "No hay chats",
        "max.chat.value.unlimited": "Ilimitado",

        "skills.footer.backToList.tooltip": "Volver a la lista de habilidades",
        "skills.footer.create.button": "Añadir habilidad",
        "skills.footer.create.tooltip": "Añadir nueva habilidad",

        "users.footer.backToList.tooltip": "Volver a la lista de usuarios",
        "users.footer.create.button": "Añadir usuario",
        "users.footer.create.tooltip": "Añadir usuario",

        "agentGroups.footer.backToList.tooltip": "Volver a la lista de grupos",
        "agentGroups.footer.create.button": "Añadir grupo",
        "agentGroups.footer.create.list.tooltip": "Seleccionar un principal para el nuevo grupo.",
        "agentGroups.footer.create.disabled.list.tooltip": "Seleccionar un principal para el nuevo grupo",
        "agentGroups.footer.create.enabled.list.tooltip": "Añadir nuevo grupo",
        "agentGroups.footer.create.edit.tooltip": "Puede añadir un grupo solo desde la lista de grupos seleccionando un grupo principal para el nuevo grupo.",

        "lobs.footer.backToList.tooltip": "Volver a la lista de Líneas de negocio",
        "lobs.footer.create.button": "Añadir Línea de negocio",
        "lobs.footer.create.tooltip": "Añadir nueva Línea de negocio",

        "profiles.footer.backToList.tooltip": "Volver a la lista de perfiles",
        "profiles.footer.create.button": "Añadir perfil",
        "profiles.footer.create.tooltip": "Añadir nuevo perfil",

        "profiles.roles.admin": "Administrador",
        "profiles.roles.agentManager": "Coordinador de agente",
        "profiles.roles.agent": "Agente",
        "profiles.roles.campaignManager": "Gestor de campañas",
        "profiles.roles.lpa": "LPA",
        "profiles.column.name.filter.placeholder": "Perfiles",
        "roles.column.name.filter.placeholder": "Funciones",
        "types.column.name.filter.placeholder": "Tipos",
        "skills.column.name.filter.placeholder": "Habilidades",
        "lobs.column.name.filter.placeholder": "Líneas de negocio",
        "lobs.column.name.filter.noLobs": "No se ha asignado LOB",

        "headerTabs.skills.name": "Habilidades",
        "headerTabs.skills.description": "Gestione y cree habilidades para dirigir de forma eficiente las interacciones a los agentes apropiados.",
        "headerTabs.skills.kpText": "Más información",
        "headerTabs.users.name": "Usuarios",
        "headerTabs.users.description": "Crear y gestionar usuarios y sus permisos.",
        "headerTabs.agentGroups.name": "Grupos de agentes",
        "headerTabs.agentGroups.description": "Habilite los coordinadores de agentes para medir el rendimiento de sus agentes.",
        "headerTabs.agentGroups.kpText": "Más información.",
        "headerTabs.lobs.name": "Líneas de negocio",
        "headerTabs.lobs.description": "Cree Líneas de negocio separadas para que coincidan con sus divisiones o unidades de negocio.",
        "headerTabs.lobs.kpText": "Más información.",

        "headerTabs.profiles.name": "Perfiles",
        "headerTabs.profiles.description": "Cree un conjunto de permisos que puede asignar a sus usuarios.",
        "headerTabs.profiles.kpText": "Más información",

        "profileEdit.header.title.new": "Añadir perfil",
        "profileEdit.header.title.edit": "Editar perfil",
        "profileEdit.errorOnFetching.text": "Error al recuperar perfil",
        "profileEdit.header.description": "Administrar perfiles",
        "profileEdit.name.label": "Nombre:",
        "profileEdit.name.placeholder": "Nombre del perfil",
        "profileEdit.description.label": "Descripción",
        "profileEdit.saveButton.tooltip.mandatoryFields": "El nombre del perfil es un campo obligatorio.",
        "profileEdit.saveButton.tooltip.noChanges": "No se han realizado cambios.",
        "profileEdit.sections.profileDetails": "Detalles del perfil",
        "profileEdit.sections.permissions": "Permisos",
        "profileEdit.role.label": "Función:",
        "profileEdit.assignedUsers.label": "{0} usuarios asignados",
        "profileEdit.assignedUsers.and.lpa.label": "Asignado a {0} usuarios y a Administradores de LivePerson (LPA)",
        "profileEdit.assignedLpa.label": "Asignado a Administradores de LivePerson (LPA)",
        "profileEdit.no.assignedUsers.label": "No hay usuarios asignados",
        "profileEdit.addDescription.placeholder": "Añadir descripción...",
        "profileEdit.add.description.label": "Añadir descripción",
        "profileEdit.restore.default.label": "Restaurar predeterminados",
        "profileEdit.restore.default.tooltip": "Restablecer los permisos predeterminados para esta función.",
        "profileEdit.saveButton.activeUsers": "El {0} está asignado actualmente a los usuarios activos. Los cambios que ha realizado afectarán a todos esos usuarios. Haga clic en Aceptar para continuar.",
        "profileEdit.restore.default.confirmation": "Esta acción restablecerá los permisos predeterminados para la función {0}. Haga clic en Aceptar para continuar o en Cancelar para conservar los permisos actuales.",
        "profileEdit.errors.description.length": "La descripción no puede superar los 300 caracteres.",
        "profileEdit.errors.name.length": "El nombre no puede superar los 100 caracteres.",
        "profileEdit.errors.name.duplicated": "El nombre ya existe.",
        "profileEdit.errors.general.changingLastAdminProfile": "LiveEngage requiere que todas las cuentas tengan al menos un perfil de administrador con todos los permisos administrativos predeterminados.",
        "profileEdit.errors.general.conflict": "No hemos podido guardar este perfil porque alguien está editándolo actualmente.",
        "profileEdit.errors.entity.was.deleted": "No hemos podido guardar este perfil porque alguien lo ha eliminado.",

        /* TODO: Adiel: Here only for backward compatible for 7.12 need to be removed after 7.12 */
        "userList.column.loginName.header": "NOMBRE DE USUARIO",
        "userEdit.loginName.label": "Nombre de usuario:",
        "userEdit.loginName.placeholder": "Introduzca el nombre de usuario",
        "also.login.name": "Introduzca la dirección de correo electrónico",

        "userList.column.displayName.header": "NOMBRE",
        "userList.column.userTypeId.header": "DE COMP.",
        "userList.column.nickName.header": "APODO",
        "userList.column.loginName.header.new": "NOMBRE DE USUARIO",
        "userList.column.permissionGroup.header": "PERMISO ESTABLECIDO",
        "userList.column.groups.header": "GRUPOS",
        "userList.column.lobs.header": "LÍNEAS DE NEGOCIO",
        "userList.column.skills.header": "HABILIDADES",
        "userList.column.roles.header": "FUNCIONES",
        "userList.column.profiles.header": "PERFILES",
        "userList.column.skills.filter.unassigned": "No asignado",
        "userList.delete.confirm.text": "Al eliminar {0} se eliminará completamente este usuario de LiveEngage.",
        "userList.delete.error.currentLoggedInUser": "El usuario está activo actualmente y no puede ser eliminado.",
        "userList.footnote.language": "El idioma de la interfaz de su cuenta LiveEngage es",
        "userList.footnote.timezone": "y su zona horaria es",
        "userList.footnote.timeout.system": "Se cerrará la sesión de usuario automáticamente tras una inactividad de:",
        "userList.footnote.change.confirm.text": "Este cambio se aplicará a todos los usuarios de LiveEngage.",
        "userList.footnote.change.error.generic": "No hemos podido actualizar la configuración. Inténtelo de nuevo.",
        "userList.footnote.change.error.anotherUser": "No se pudo completar la solicitud porque otro usuario está editando la misma entidad.",
        "userList.noResults.message": "No hay usuarios que coincidan que mostrar.",
        "userList.exportUsers.notification": "Exportando todos los usuarios, habilidades, conjuntos de permisos y grupos de agentes. Esto puede tardar unos minutos.",
        "userList.siteSettings.errorOnFetching.text": "Error al recuperar los ajustes del sitio.",
        "userList.fetch.error": "Se ha producido un problema al recuperar la lista de usuarios. Inténtelo de nuevo más tarde.",

        "userList.menuItem.assignSkills.disabled.tooltip.agentProfiles": "Asignar habilidades solo está disponible si todos los usuarios seleccionados tiene un perfil de Agente.",
        "userList.menuItem.setConcurrency.disabled.tooltip.agentProfiles": "Establecer concurrencia solo está disponible si todos los usuarios seleccionados tiene un perfil de Agente.",
        "userList.menuItem.disabled.tooltip.limitExceeded": "Esta acción está limitada a {0} a la vez. Deseleccione usuarios para realizar esta acción.",

        "userList.batchAction.confirm.title": "La acción puede llevar algo de tiempo.",
        "userList.batchAction.confirm.content": "Esta acción puede tardar unos minutos. Durante este tiempo, no podrá realizar otras acciones en el área Usuarios. ¿Seguro que desea continuar?",

        "userList.assignSkills.title":  "Asignar habilidades",
        "userList.assignSkills.subtitle" : "Asignar habilidades a los {0} usuarios seleccionados.",
        "userList.assignSkills.note.label":  "Nota: ",
        "userList.assignSkills.note.text":  "Si los usuarios seleccionados comparten habilidades comunes, estas habilidades aparecerán en el campo de arriba.",
        "userList.assignSkills.multiselect.label" : "Habilidades:",
        "userList.assignSkills.multiselect.placeholder" : "Asignar habilidades",
        "userList.assignSkills.skills.fetch.error" : "Se ha producido un problema al recuperar la lista de habilidades. Inténtelo de nuevo más tarde.",
        "userList.assignSkills.loader.text" : "Asignación de habilidad en proceso.",

        "userList.assignSkills.progress" : "Asignación de habilidad en proceso.",
        "userList.assignSkills.success" : "La asignación de habilidades para los usuarios seleccionados se completó correctamente.",
        "userList.assignSkills.error": "No hemos podido realizar la acción de asignación de habilidades. Inténtelo de nuevo.",

        "userList.setConcurrency.title" : "Establecer divisa",
        "userList.setConcurrency.subtitle" : "Establezca el número máximo de chats{0} que el usuario puede aceptar en cualquier momento para los {1} usuarios seleccionados.",
        "userList.setConcurrency.subtitle.part.messaging" : "/conversaciones",
        "userList.setConcurrency.maxChats.label" : "Nº máx. de chats activos:",
        "userList.setConcurrency.maxChats.placeholder" : "Introduzca un valor entre 0-9",
        "userList.setConcurrency.maxAsyncChats.label" : "Nº máximo de conversaciones de mensajería:",
        "userList.setConcurrency.maxAsyncChats.radio.accountSettings.text.part1" : "Configuración de la cuenta",
        "userList.setConcurrency.maxAsyncChats.radio.accountSettings.text.part2" : "(valor actual - {0})",
        "userList.setConcurrency.maxAsyncChats.radio.customSettings.text" : "Ajustes predeterminados:",
        "userList.setConcurrency.maxAsyncChats.radio.customSettings.placeholder" : "Introduzca un valor entre 0-999",
        "userList.setConcurrency.note.label" : "Nota: ",
        "userList.setConcurrency.note.text" : "Mantener un campo vacío dejará su configuración actual sin cambios.",
        "userList.setConcurrency.loader.text" : "Ajuste de concurrencia en proceso",

        "userList.setConcurrency.progress" : "Ajuste de concurrencia en proceso.",
        "userList.setConcurrency.success" : "Configurar la concurrencia para los usuarios seleccionados se completó correctamente.",
        "userList.setConcurrency.error" : "No hemos podido realizar la acción de configuración de concurrencia. Inténtelo de nuevo.",
        "userList.duplicate.agent.group.warning.message": "Los ajustes que no tiene permiso para duplicar se eliminaron.",

        "profileList.column.profileName.header": "NOMBRE DEL PERFIL",
        "profileList.column.profileName.filter.placeholder": "Nombre del perfil",
        "profileList.column.role.header": "FUNCIÓN",
        "profileList.column.role.filter.placeholder": "Función",
        "profileList.column.description.header": "DESCRIPCIÓN",
        "profileList.column.usersNum.header": "Nº de USUARIOS",
        "profileList.noResults.message": "No hay perfiles que mostrar.",
        "profileList.delete.confirm.text": "Al eliminar {0} se eliminará completamente este perfil de LiveEngage.",
        "profileList.delete.assigned.users.header": "No se puede eliminar el perfil",
        "profileList.delete.assigned.users.text": "Existen usuarios asignados a este perfil. Vuelva a reasignarlas antes de eliminar el perfil.",
        "profileList.delete.error.text": "No hemos podido eliminar {0}. Intente eliminar de nuevo.",
        "profileList.delete.error.lastProfileOfRole.text": "No hemos podido eliminar {0} porque es el último perfil de la función {1}.",
        "permissionList.column.permission.header": "PERMISO",
        "permissionList.column.enabled.header": "HABILITADO",
        "permissionList.duplicate.success": "El perfil se duplicó correctamente.",
        "permissionList.duplicate.error": "Se ha producido un error al duplicar el perfil.",

        //Agent
        "profile.permission.20001": "Unirse a la conversación de otro agente",
        "profile.permission.20001.tooltip": "Unirse a una conversación gestionada por otro agente en su grupo.",
        "profile.permission.20002": "Ver las conversaciones de otros agentes",
        "profile.permission.20002.tooltip": "Ver las conversaciones gestionadas por otros agentes en su grupo.",
        "profile.permission.20003": "Ver la Lista de agentes",
        "profile.permission.20003.tooltip": "Ver la lista completa de agentes en su grupo.",
        "profile.permission.20004": "Utilice un formulario seguro en una conversación",
        "profile.permission.20004.tooltip": "Permite al Agente usar el formulario en una conversación.",
        "profile.permission.20005": "Iniciar conversación de voz",
        "profile.permission.20005.tooltip": "Invitar a un consumidor a unirse a una conversación de voz.",
        "profile.permission.20006": "Iniciar vídeo en vivo",
        "profile.permission.20006.tooltip": "Invitar a un consumidor a unirse a una sesión de vídeo en vivo.",
        "profile.permission.20007": "Iniciar sesión solo vista de navegación conjunta, con control de desplazamiento",
        "profile.permission.20007.tooltip": "Invitar al consumidor a unirse a una sesión de CoBrowse, con la capacidad de ver su pantalla con control de desplazamiento.",
        "profile.permission.20008": "Iniciar sesión solo vista de navegación conjunta",
        "profile.permission.20008.tooltip": "Invitar al consumidor a unirse a una sesión de CoBrowse, con la capacidad de ver su pantalla.",
        "profile.permission.20009": "Iniciar sesión de navegación conjunta con control compartido",
        "profile.permission.20009.tooltip": "Invitar al consumidor a unirse a una sesión de CoBrowse, con la capacidad de controlar las acciones en su pantalla.",
        "profile.permission.20010": "Ver casos de asistencia en el Área de conexión",
        "profile.permission.20010.tooltip": "Ver casos de asistencia abiertos y cerrados desde el Área de conexión.",
        "profile.permission.20011": "Crear nuevos casos de asistencia en el Área de conexión.",
        "profile.permission.20011.tooltip": "Abrir un nuevo caso desde el Área de conexión.",
        "profile.permission.20012": "Contactar con asistencia de LivePerson en el Área de conexión.",
        "profile.permission.20012.tooltip": "Charlar con el equipo de asistencia de LP.",
        "profile.permission.20013": "Gestionar las conversaciones de mensajería y acceder a la lista Todas las conexiones",
        "profile.permission.20013.tooltip": "Permitir que un agente gestione las conversaciones de mensajería y vea todas las conversaciones resueltas gestionadas por los agentes.",
        "profile.permission.20014": "Ver contenido en el Área de conexión.",
        "profile.permission.20014.tooltip": "Ver contenido relevante por trayecto.",
        "profile.permission.20015": "Gestionar conversaciones de mensajería",
        "profile.permission.20015.tooltip": "Permitir que el agente gestione las conversaciones de mensajería.",
        "profile.permission.20017": "Establecer SLA manual",
        "profile.permission.20017.tooltip": "Capacidad para establecer SLA manual para las conversaciones.",
        "profile.permission.20018": "Ver notificaciones relacionadas con la cuenta en el Centro de notificaciones",
        "profile.permission.20018.tooltip": "Capacidad de recibir y abrir alertas relacionadas con la cuenta en el Centro de notificaciones.",
        "profile.permission.20019": "Ver notificaciones relacionadas con el usuario en el Centro de notificaciones",
        "profile.permission.20019.tooltip": "Capacidad de recibir y abrir alertas individuales relacionadas con el usuario en el Centro de notificaciones.",
        "profile.permission.20020": "Actualizar el perfil del consumidor a través de API.",
        "profile.permission.20020.tooltip": "Permitir que un agente actualice un perfil de consumidor a través de API.",
        "profile.permission.20021": "Ver cuestionarios de mensajería.",
        "profile.permission.20021.tooltip": "Permitir al Agente ver la transcripción del cuestionario post conversación de Mensajería y las respuestas en LiveEngage.",
        "profile.permission.20023": "Agente de servicio que responde",
        "profile.permission.20023.tooltip": "Habilitar el Centro de contacto de cuentas entre mensajería.",
        "profile.permission.20025": "Área de automatización",
        "profile.permission.20025.tooltip": "Habilite el Área de automatización para crear y gestionar bots.",
        "profile.permission.20024": "Transfiera las conversaciones de mensajería a un agente específico en estado \"en línea\" o \"vuelvo pronto\".",
        "profile.permission.20024.tooltip": "Permita transferir una conversación de mensajería a un agente específico cuando su estado esté \"en línea\" o \"vuelvo pronto\".",
        "profile.permission.20027": "Transfiera conversaciones de mensajería a un agente específico en estado \"ausente\".",
        "profile.permission.20027.tooltip": "Permita transferir una conversación de mensajería a un agente específico cuando su estado sea \"ausente\".",
        "profile.permission.20026": "Transfiera conversaciones de mensajería a un agente específico en estado \"desconectado\".",
        "profile.permission.20026.tooltip": "Permita transferir una conversación de mensajería a un agente específico cuando su estado sea \"desconectado\".",
        "profile.permission.20029": "Editar conectores del bot",
        "profile.permission.20029.tooltip": "Capacidad para editar bots y cambiar el estado de ejecución en conectores del bot",
        "profile.permission.20030": "Enviar archivos a los consumidores desde el navegador local de archivos",
        "profile.permission.20030.tooltip": "Capacidad para enviar archivos desde el navegador local de archivos.  Nota: puede ser necesario realizar configuración adicional para habilitar la función de intercambio de archivos. Póngase en contacto con su administrador de cuenta para habilitarlo.",
        "profile.permission.20031": "Enviar archivos a los consumidores desde widget personalizados",
        "profile.permission.20031.tooltip": "Capacidad para enviar archivos desde widgets personalizados. Nota: puede ser necesario realizar configuración adicional para habilitar la función de intercambio de archivos. Póngase en contacto con su administrador de cuenta para habilitarlo.",
        "profile.permission.20032": "Usuario de contenido en Creador de conversación.",
        "profile.permission.20032.tooltip": "Capacidad para leer y escribir KB, intenciones y análisis en el Creador de conversación.",
        "profile.permission.20033": "Usuario empresarial en el Creador de conversación.",
        "profile.permission.20033.tooltip": "Capacidad para ver análisis en el Creador de conversación.",
        "profile.permission.20034": "Operaciones en el Creador de conversación.",
        "profile.permission.20034.tooltip": "Capacidad para ver y alterar cuentas en el Creador de conversación.",
        "profile.permission.20035": "Creador de bots en el Creador de conversación.",
        "profile.permission.20035.tooltip": "Capacidad para crear bots, leer y escribir KB e intenciones y ver análisis en el Creador de conversación.",
        "profile.permission.20036": "Ver el nuevo módulo \"Conexiones\" del espacio de trabajo del agente",
        "profile.permission.20036.tooltip": "Habilitar el nuevo módulo (\"Conexiones\") del espacio de trabajo del agente. Este módulo se añadirá además del módulo actual \"Visitantes\".",
        "profile.permission.20037": "Ver sugerencias inteligente",
        "profile.permission.20037.tooltip": "Permitir que los agentes vean las sugerencias inteligentes para las respuestas. Las sugerencias se basan en los mensajes del consumidor.",
        "profile.permission.20038": "Ver completar automáticamente",
        "profile.permission.20038.tooltip": "Proporcione a los agentes la opción de completar sus respuestas según lo que se haya escrito antes.",
        "profile.permission.20039": "Proporcionar los comentarios de la API para el texto del agente",
        "profile.permission.20039.tooltip": "Enviar las respuestas del agente a la API para mejorar las sugerencias futuras.",

        //Agent Manager
        "profile.permission.30001": "Unirse a las conversaciones de los agentes",
        "profile.permission.30001.tooltip": "Unirse a una conversación gestionada por un agente en sus grupos o subgrupos.",
        "profile.permission.30002": "Ver las conversaciones de los agentes",
        "profile.permission.30002.tooltip": "Ver las conversaciones gestionadas por agentes en sus grupos o subgrupos.",
        "profile.permission.30003": "Editar usuarios de agentes",
        "profile.permission.30003.tooltip": "Crear, editar o eliminar usuarios con una función Agente en sus grupos o subgrupos.",
        "profile.permission.30004": "Editar usuarios del coordinador de agentes",
        "profile.permission.30004.tooltip": "Crear, editar o eliminar usuarios con una función Gestor de agentes en sus grupos o subgrupos.",
        "profile.permission.30005": "Editar el perfil del agente",
        "profile.permission.30005.tooltip": "Crear, editar o eliminar perfiles de la función Agente.",
        "profile.permission.30006": "Editar el perfil del coordinador de agentes",
        "profile.permission.30006.tooltip": "Crear, editar o eliminar perfiles de la función Gestor de agentes.",
        "profile.permission.30007": "Administración de grupos de agentes",
        "profile.permission.30007.tooltip": "Crear, editar, reestructurar o eliminar sus grupos o subgrupos de agentes.",
        "profile.permission.30008": "Exportar usuarios",
        "profile.permission.30008.tooltip": "Exportar la lista de usuarios Agente o Gestor de agentes en sus grupos o subgrupos; esto también exportará la lista de habilidades, perfiles y los grupos y subgrupos gestionados por los Gestores de agentes.",
        "profile.permission.30009": "Ver el Historial de interacciones",
        "profile.permission.30009.tooltip": "Ver las interacciones gestionadas por los agentes en sus grupos o subgrupos.",
        "profile.permission.30010": "Ver la Lista de agentes",
        "profile.permission.30010.tooltip": "Ver la lista completa de agentes en su grupo.",
        "profile.permission.30011": "Visión nocturna (configuración avanzada)",
        "profile.permission.30011.tooltip": "Realizar configuraciones avanzadas en Night Vision.",
        "profile.permission.30012": "Ver las respuestas al formulario seguro en el Historial de interacciones",
        "profile.permission.30012.tooltip": "Permite al Coordinador de agentes ver todas las respuestas de formulario seguro en el Historial de interacciones.",
        "profile.permission.30013": "Editar habilidades",
        "profile.permission.30013.tooltip": "Crear, editar o eliminar habilidades.",
        "profile.permission.30014": "Ver informes en Creador de informes",
        "profile.permission.30014.tooltip": "Permite la visualización de todos los informes en el Creador de informes.",
        "profile.permission.30015": "Ver la lista Todas las conexiones",
        "profile.permission.30015.tooltip": "Permitir ver todas las conversaciones resueltas gestionadas por los Agentes.",
        "profile.permission.30016": "Personalizar informes en Creador de informes",
        "profile.permission.30016.tooltip": "Permite a los Coordinadores de agentes personalizar informes en Creador de informes.",
        "profile.permission.30017": "Compartir informes en Creador de informes",
        "profile.permission.30017.tooltip": "​Permite compartir los informes con otros usuarios de la cuenta en el Creador de informes.",
        "profile.permission.30018": "Ver casos de asistencia en el Área de conexión",
        "profile.permission.30018.tooltip": "Ver casos de asistencia abiertos y cerrados desde el Área de conexión.",
        "profile.permission.30019": "Crear nuevos casos de asistencia en el Área de conexión.",
        "profile.permission.30019.tooltip": "Abrir un nuevo caso desde el Área de conexión.",
        "profile.permission.30020": "Contactar con asistencia de LivePerson en el Área de conexión.",
        "profile.permission.30020.tooltip": "Charlar con el equipo de asistencia de LP.",
        "profile.permission.30021": "Ver contenido en el Área de conexión.",
        "profile.permission.30021.tooltip": "Ver contenido relevante por trayecto.",
        "profile.permission.30022": "Ver informes en BI Operacional",
        "profile.permission.30022.tooltip": "Ver informes en el panel de control BI Operacional.",
        "profile.permission.30023": "Configurar programador de turno de la cuenta",
        "profile.permission.30023.tooltip": "Permitir definir el programador de turno de la cuenta, incluyendo los días laborables y las ocasiones especiales.",
        "profile.permission.30024": "Asumir conversación",
        "profile.permission.30024.tooltip": "Permite asumir una conversación activa.",
        "profile.permission.30029": "Establecer SLA manual",
        "profile.permission.30029.tooltip": "Capacidad para establecer SLA manual para las conversaciones.",
        "profile.permission.30030": "Generar token de formulario seguro",
        "profile.permission.30030.tooltip": "Habilitar la generación de token de formulario seguro en la página Todas las conexiones.",
        "profile.permission.30031": "Ver notificaciones relacionadas con la cuenta en el Centro de notificaciones",
        "profile.permission.30031.tooltip": "Capacidad de recibir y abrir alertas relacionadas con la cuenta en el Centro de notificaciones.",
        "profile.permission.30032": "Ver notificaciones relacionadas con el usuario en el Centro de notificaciones",
        "profile.permission.30032.tooltip": "Capacidad de recibir y abrir alertas individuales relacionadas con el usuario en el Centro de notificaciones.",
        "profile.permission.30033": "Solicitar eliminación de datos del cliente a través de API",
        "profile.permission.30033.tooltip": "Capacidad para usar la API de eliminación de datos personales para eliminar los datos del cliente.",
        "profile.permission.30034": "Actualizar el perfil del consumidor a través de API.",
        "profile.permission.30034.tooltip": "Permitir que un coordinador de agente actualice un perfil de consumidor a través de API.",
        "profile.permission.30035": "Configurar los días laborables de habilidades y ocasiones especiales",
        "profile.permission.30036": "Ver cuestionarios de mensajería.",
        "profile.permission.30036.tooltip": "Permitir al Coordinador de agente ver la transcripción del cuestionario post conversación de Mensajería y las respuestas en LiveEngage.",
        "profile.permission.30038": "Área de automatización",
        "profile.permission.30038.tooltip": "Habilite el Área de automatización para crear y gestionar bots.",
        "profile.permission.30039": "Agente de servicio que responde",
        "profile.permission.30039.tooltip": "Habilitar el Centro de contacto de cuentas entre mensajería.",
        "profile.permission.30040": "Transfiera las conversaciones de mensajería a un agente específico en estado \"en línea\" o \"vuelvo pronto\".",
        "profile.permission.30040.tooltip": "Permita transferir una conversación de mensajería a un agente específico cuando su estado esté \"en línea\" o \"vuelvo pronto\".",
        "profile.permission.30041": "Transfiera conversaciones de mensajería a un agente específico en estado \"ausente\".",
        "profile.permission.30041.tooltip": "Permita transferir una conversación de mensajería a un agente específico cuando su estado sea \"ausente\".",
        "profile.permission.30042": "Transfiera conversaciones de mensajería a un agente específico en estado \"desconectado\".",
        "profile.permission.30042.tooltip": "Permita transferir una conversación de mensajería a un agente específico cuando su estado sea \"desconectado\".",
        "profile.permission.30044": "Editar integraciones de bot",
        "profile.permission.30044.tooltip": "Capacidad para editar bots y cambiar el estado de ejecución en Integraciones de bot",
        "profile.permission.30045": "Enviar archivos a los consumidores desde el navegador local de archivos",
        "profile.permission.30045.tooltip": "Capacidad para enviar archivos desde el navegador local de archivos.  Nota: puede ser necesario realizar configuración adicional para habilitar la función de intercambio de archivos. Póngase en contacto con su administrador de cuenta para habilitarlo.",
        "profile.permission.30046": "Enviar archivos a los consumidores desde widget personalizados",
        "profile.permission.30046.tooltip": "Capacidad para enviar archivos desde widgets personalizados. Nota: puede ser necesario realizar configuración adicional para habilitar la función de intercambio de archivos. Póngase en contacto con su administrador de cuenta para habilitarlo.",
        "profile.permission.30047": "Usuario de contenido en Creador de conversación.",
        "profile.permission.30047.tooltip": "Capacidad para leer y escribir KB, intenciones y análisis en el Creador de conversación.",
        "profile.permission.30048": "Usuario empresarial en el Creador de conversación.",
        "profile.permission.30048.tooltip": "Capacidad para ver análisis en el Creador de conversación.",
        "profile.permission.30049": "Operaciones en el Creador de conversación.",
        "profile.permission.30049.tooltip": "Capacidad para ver y alterar cuentas en el Creador de conversación.",
        "profile.permission.30050": "Creador de bots en el Creador de conversación.",
        "profile.permission.30050.tooltip": "Capacidad para crear bots, leer y escribir KB e intenciones y ver análisis en el Creador de conversación.",
        "profile.permission.30051": "Ver el espacio de trabajo del gestor del agente",
        "profile.permission.30051.tooltip": "Permita que los Gestores del agente realicen un seguimiento de los KPI de gestión de turnos en tiempo real, vea la lista de agentes desde su grupo y subgrupo para ver todas las conversaciones abiertas y resueltas por los agentes.",
        "profile.permission.30052": "Ver el nuevo módulo \"Conexiones\" del espacio de trabajo del agente",
        "profile.permission.30052.tooltip": "Habilitar el nuevo módulo (\"Conexiones\") del espacio de trabajo del agente. Este módulo se añadirá además del módulo actual \"Visitantes\".",
        "profile.permission.30055": "Ver el espacio de trabajo del gestor del agente",
        "profile.permission.30055.tooltip": "Permita que los Gestores del agente realicen un seguimiento de los KPI de gestión de turnos en tiempo real, vea la lista de agentes desde su grupo y subgrupo para ver todas las conversaciones abiertas y resueltas por los agentes.",

        //Campaign Manager
        "profile.permission.40001": "Editar campañas",
        "profile.permission.40001.tooltip": "Crear y modificar campañas.",
        "profile.permission.40002": "Publicar campañas",
        "profile.permission.40002.tooltip": "Controlar la publicación de campañas.",
        "profile.permission.40003": "Configurar el contenido predefinido",
        "profile.permission.40003.tooltip": "Añadir y editar Contenido predefinido en el Espacio de trabajo del agente.",
        "profile.permission.40004": "Configurar los mensajes automáticos",
        "profile.permission.40004.tooltip": "Añadir y editar Mensajes automáticos en el Espacio de trabajo del agente.",
        "profile.permission.40005": "Configurar los atributos de la interacción",
        "profile.permission.40005.tooltip": "Añadir y editar los Atributos de la interacción usados en las campañas.",
        "profile.permission.40006": "Importar y exportar contenido predefinido",
        "profile.permission.40006.tooltip": "Importar y exportar Contenido predefinido a y desde LiveEngage.",
        "profile.permission.40007": "Exportar el contenido predefinido.",
        "profile.permission.40007.tooltip": "Exportar Contenido predefinido desde LiveEngage.",
        "profile.permission.40008": "Ver claves API",
        "profile.permission.40008.tooltip": "Permitir ver las claves API usadas por la marca.",
        "profile.permission.40009": "Ver informes en Creador de informes",
        "profile.permission.40009.tooltip": "Permite la visualización de todos los informes en el Creador de informes.",
        "profile.permission.40010": "Personalizar informes en Creador de informes",
        "profile.permission.40010.tooltip": "Permite a los Coordinadores de campañas personalizar informes en Creador de informes.",
        "profile.permission.40011": "Configurar formulario seguro",
        "profile.permission.40012": "Configurar servidor de autenticación",
        "profile.permission.40012.tooltip": "Permite a los usuarios configurar el servidor de autenticación.",
        "profile.permission.40013": "Compartir informes en Creador de informes",
        "profile.permission.40013.tooltip": "Permite compartir los informes con otros usuarios de la cuenta en el Creador de informes.",
        "profile.permission.40014": "Ver casos de asistencia en el Área de conexión",
        "profile.permission.40014.tooltip": "Ver casos de asistencia abiertos y cerrados desde el Área de conexión.",
        "profile.permission.40015": "Crear nuevos casos de asistencia en el Área de conexión.",
        "profile.permission.40015.tooltip": "Abrir un nuevo caso desde el Área de conexión.",
        "profile.permission.40016": "Contactar con asistencia de LivePerson en el Área de conexión.",
        "profile.permission.40016.tooltip": "Charlar con el equipo de asistencia de LP.",
        "profile.permission.40017": "Ver contenido en el Área de conexión.",
        "profile.permission.40017.tooltip": "Ver contenido relevante por trayecto.",
        "profile.permission.40018": "Editar habilidades",
        "profile.permission.40018.tooltip": "Edite las habilidades y configure el cuestionario predeterminado para cambio de habilidad",
        "profile.permission.40019": "Ver informes en BI de campaña",
        "profile.permission.40019.tooltip": "Ver informes en el panel de control BI Campaña.",
        "profile.permission.40020": "Configurar fuentes de conversaciones",
        "profile.permission.40020.tooltip": "Configurar puntos de entrada del cliente para que interactúen con su marca",
        "profile.permission.40021": "Ver informes en BI Operacional",
        "profile.permission.40021.tooltip": "Ver informes en el panel de control BI Operacional.",
        "profile.permission.40025": "Ver notificaciones relacionadas con la cuenta en el Centro de notificaciones",
        "profile.permission.40025.tooltip": "Capacidad de recibir y abrir alertas relacionadas con la cuenta en el Centro de notificaciones.",
        "profile.permission.40026": "Ver notificaciones relacionadas con el usuario en el Centro de notificaciones",
        "profile.permission.40026.tooltip": "Capacidad de recibir y abrir alertas individuales relacionadas con el usuario en el Centro de notificaciones.",
        "profile.permission.40028": "Configurar elementos de la biblioteca de ocasiones especiales y programaciones",
        "profile.permission.40029.tooltip": "Habilite el Área de automatización para crear y gestionar bots.",
        "profile.permission.40029": "Área de automatización",
        "profile.permission.40030": "Editar integraciones de bot",
        "profile.permission.40030.tooltip": "Capacidad para editar bots y cambiar el estado de ejecución en Integraciones de bot",
        "profile.permission.40031": "Usuario de contenido en Creador de conversación.",
        "profile.permission.40031.tooltip": "Capacidad para leer y escribir KB, intenciones y análisis en el Creador de conversación.",
        "profile.permission.40032": "Usuario empresarial en el Creador de conversación.",
        "profile.permission.40032.tooltip": "Capacidad para ver análisis en el Creador de conversación.",
        "profile.permission.40033": "Operaciones en el Creador de conversación.",
        "profile.permission.40033.tooltip": "Capacidad para ver y alterar cuentas en el Creador de conversación.",
        "profile.permission.40034": "Creador de bots en el Creador de conversación.",
        "profile.permission.40034.tooltip": "Capacidad para crear bots, leer y escribir KB e intenciones y ver análisis en el Creador de conversación.",


        //Admin
        "profile.permission.10001": "Administración del usuario",
        "profile.permission.10001.tooltip": "Crear, editar y eliminar usuarios y configurar sus asignaciones.",
        "profile.permission.10002": "Administración del perfil",
        "profile.permission.10002.tooltip": "Crear, editar y eliminar perfiles (incluyendo personalizar permisos).",
        "profile.permission.10003": "Administración de habilidades",
        "profile.permission.10003.tooltip": "Crear, editar y eliminar habilidades.",
        "profile.permission.10004": "Administración de grupos de agentes",
        "profile.permission.10004.tooltip": "Crear, editar, reestructurar o eliminar Grupos de agentes.",
        "profile.permission.10005": "Editar ajustes de la cuenta",
        "profile.permission.10006": "Administración de clave API",
        "profile.permission.10006.tooltip": "Permite a los administradores crear, gestionar e integrar claves API.",
        "profile.permission.10007": "Visión nocturna (configuración avanzada)",
        "profile.permission.10007.tooltip": "Realizar configuraciones avanzadas en Night Vision.",
        "profile.permission.10008": "Administración de Líneas de negocio",
        "profile.permission.10008.tooltip": "Permite a los administradores crear, editar y elimintar Líneas de negocio individuales en su cuenta de LiveEngage.",
        "profile.permission.10009": "Ver los detalles de facturación de la cuenta",
        "profile.permission.10009.tooltip": "Acceso a los datos de facturación y a las facturas en línea.",
        "profile.permission.10010": "Ver casos de asistencia en el Área de conexión",
        "profile.permission.10010.tooltip": "Ver casos de asistencia abiertos y cerrados desde el Área de conexión.",
        "profile.permission.10011": "Crear nuevos casos de asistencia en el Área de conexión.",
        "profile.permission.10011.tooltip": "Abrir un nuevo caso desde el Área de conexión.",
        "profile.permission.10012": "Asignación de perfiles LPA",
        "profile.permission.10013": "Configurar política de inicio de sesión",
        "profile.permission.10014": "Configurar ocultación de datos sensibles a la seguridad",
        "profile.permission.10015": "Ver y exportar registro de auditoria",
        "profile.permission.10015.tooltip": "Permite a los administradores ver y exportar registro de auditoria.",
        "profile.permission.10016": "Contactar con asistencia de LivePerson en el Área de conexión.",
        "profile.permission.10016.tooltip": "Charlar con el equipo de asistencia de LP.",
        "profile.permission.10017": "Ver contenido en el Área de conexión.",
        "profile.permission.10017.tooltip": "Ver contenido relevante por trayecto.",
        "profile.permission.10018": "Configurar programador de turno de la cuenta",
        "profile.permission.10018.tooltip": "Permitir definir el programador de turno de la cuenta, incluyendo los días laborables y las ocasiones especiales.",
        "profile.permission.10024": "Ver notificaciones relacionadas con la cuenta en el Centro de notificaciones",
        "profile.permission.10024.tooltip": "Capacidad de recibir y abrir alertas relacionadas con la cuenta en el Centro de notificaciones.",
        "profile.permission.10025": "Ver notificaciones relacionadas con el usuario en el Centro de notificaciones",
        "profile.permission.10025.tooltip": "Capacidad de recibir y abrir alertas individuales relacionadas con el usuario en el Centro de notificaciones.",
        "profile.permission.10027": "Configurar los días laborables de habilidades y ocasiones especiales",
        "profile.permission.10028.tooltip": "Habilite el Área de automatización para crear y gestionar bots.",
        "profile.permission.10028": "Área de automatización",
        "profile.permission.10029": "Editar integraciones de bot",
        "profile.permission.10029.tooltip": "Capacidad para editar bots y cambiar el estado de ejecución en Integraciones de bot",
        "profile.permission.10030": "Invocación FaaS",
        "profile.permission.10030.tooltip": "Capacidad para invocar FaaS mediante un sistema externo",
        "profile.permission.10031": "Admin de FaaS",
        "profile.permission.10031.tooltip": "Capacidad para gestionar la configuración y ajustes de FaaS",
        "profile.permission.10032": "Desarrollador FaaS",
        "profile.permission.10032.tooltip": "Capacidad para desarrollar nuevas funciones en FaaS",
        "profile.permission.10033": "Admin en el Creador de conversación.",
        "profile.permission.10033.tooltip": "Le proporciona derechos de administración en el Creador de conversación.",
        "profile.permission.10034": "Usuario de contenido en Creador de conversación.",
        "profile.permission.10034.tooltip": "Capacidad para leer y escribir KB, intenciones y análisis en el Creador de conversación.",
        "profile.permission.10035": "Usuario empresarial en el Creador de conversación.",
        "profile.permission.10035.tooltip": "Capacidad para ver análisis en el Creador de conversación.",
        "profile.permission.10036": "Operaciones en el Creador de conversación.",
        "profile.permission.10036.tooltip": "Capacidad para ver y alterar cuentas en el Creador de conversación.",
        "profile.permission.10037": "Creador de bots en el Creador de conversación.",
        "profile.permission.10037.tooltip": "Capacidad para crear bots, leer y escribir KB e intenciones y ver análisis en el Creador de conversación.",

        "skillList.column.name.header": "NOMBRE DE HABILIDAD",
        "skillList.column.name.filter.placeholder": "Nombre de habilidad",
        "skillList.column.description.header": "DESCRIPCIÓN",
        "skillList.column.responseTime.header": "TIEMPO DE RESPUESTA PERSONALIZADO",
        "skillList.responseTime.column.header.tooltip": "El tiempo de respuesta predeterminado configurado de la habilidad para conversaciones de mensajería.",
        "skillList.column.lobs.header": "LÍNEAS DE NEGOCIO",
        "skillList.column.lobs.filter.placeholder": "Línea de negocio",
        "skillList.column.lobs.filter.noLobs": "No se ha asignado LOB",
        "skillList.noResults.message": "No hay habilidades que mostrar.",
        "skillList.delete.confirm.text": "Al eliminar {0} se eliminará completamente esta habilidad de LiveEngage. Si existen interacciones asociadas con esta habilidad, no funcionarán correctamente. Para evitar esto, asocie la interacción con otra habilidad.",
        "skillList.delete.error.assignedToUser": "La habilidad se asigna a un usuario y podría no eliminarse.",
        "skillList.delete.error.assignedToUsers": "Esta habilidad está asignada a uno o más usuarios y no puede eliminarse.",
        "skillList.delete.error.assignedToContent": "Esta habilidad está asignada a uno o más elementos de contenido predefinido y no puede eliminarse.",
        "skillList.delete.error.assignedToContentAndUsers": "Esta habilidad está asignada a contenido predefinido y a uno o más usuarios, y no puede eliminarse.",
        "skillList.delete.error.assignedToSurvey": "La habilidad está asociada con un cuestionario pre chat y podría no eliminarse.",
        "skillList.delete.error.assignedWidgets": "Esta habilidad está asignada a uno o más widgets de integración y no puede eliminarse.",
        "skillList.delete.error.defaultSkill": "La habilidad se define como habilidad predeterminada y podría no eliminarse.",
        "skillList.delete.generalError": "No hemos podido eliminar esta habilidad. Inténtelo de nuevo.",
        "skillList.delete.newConfirm.text": "Al eliminar {0} se eliminará esta habilidad de LiveEngage. Para asegurar que cualquier interacción asociada con esta habilidad siga funcionando correctamente, asocie la interacción con una habilidad diferente.",
        "skillList.delete.error.automatic.messages": "Se personalizan uno o más Mensajes automáticos para esta habilidad, y no pueden eliminarse.",
        "skillList.delete.error.predefinedContent.users.automaticMessages": "Esta habilidad está asignada a Contenido predefinido; uno o más usuarios utilizan uno o más Mensajes automáticos y no pueden ser eliminada.",
        "skillList.delete.error.predefinedContent.automaticMessages": "Esta habilidad está asignada Contenido predefinido y se utiliza en uno o más Mensajes automáticos y no puede ser eliminada.",
        "skillList.delete.error.users.automaticMessages": "Esta habilidad está asignada a uno o más usuarios y se usa en uno o más mensajes automáticos y no puede ser eliminada.",
        "skillList.delete.error.title": "Eliminación de habilidad",
        "skillList.column.responseTime.unit.minutes": "{0} minutos",
        "skillList.column.responseTime.unit.hours": "{0} horas",
        "skillList.column.responseTime.unit.days": "{0} días.",
        "skillList.footnote.agentSurvey.1": "Obtenga comentarios de sus agentes e información sobre los resultados de la conversación configurando ",
        "skillList.footnote.agentSurvey.2": ".",
        "skillList.footnote.agentSurvey.button": "cuestionarios de agente.",

        "lobList.column.name.header": "LÍNEA DE NEGOCIO",
        "lobList.column.name.filter.placeholder": "Nombre de la Línea de negocio",
        "lobList.column.description.header": "DESCRIPCIÓN",
        "lobList.column.numOfCampaignManagers.header": "COORDINADORES DE CAMPAÑAS",
        "lobList.column.numOfUsers.header": "USUARIOS",
        "lobList.column.numOfCampaigns.header": "CAMPAÑAS",
        "lobList.column.numOfSkills.header": "HABILIDADES",
        "lobList.column.numOfContents.header": "CONTENIDO PREDEFINIDO",
        "lobList.noResults.message": "No hay Líneas de negocio que mostrar.",
        "lobList.error.delete.title": "No se puede eliminar la Línea de negocio",
        "lobList.error.delete.dependency": "Actualmente existen campañas asignadas a esta Línea de negocio.<br/>Debe eliminar las campañas antes de que pueda eliminar la Línea de negocio.",
        "lobList.error.maximum.items": "Ha alcanzado el número máximo de Líneas de negocio. Intente eliminar las Líneas de negocio no usadas para añadir nuevas.",

        "agentGroupList.column.name.header": "NOMBRE DEL GRUPO",
        "agentGroupList.column.name.filter.placeholder": "Nombre del grupo",
        "agentGroupList.column.manager.name.filter.placeholder": "Nombre del coordinador",
        "agentGroupList.column.parentGroup.header": "GRUPO PRINCIPAL",
        "agentGroupList.column.parentGroup.filter.placeholder": "Nombre del grupo principal",
        "agentGroupList.column.managers.header": "COORDINADORES DEL GRUPO",
        "agentGroupList.column.members.header": "AGENTES",
        "agentGroupList.column.subGroups.header": "SUBGRUPOS",
        "agentGroupList.delete.confirm.text": "Al eliminar {0} se eliminará por completo este grupo de LiveEngage.<br/>Haga clic en Eliminar para continuar.",
        "agentGroupList.error.delete.general": "No hemos podido eliminar {0}. Intente eliminar de nuevo.",
        "agentGroupList.error.delete.dependency.members": "Existen miembros asignados a este grupo. Vuelva a asignarlos antes de eliminar el grupo.",
        "agentGroupList.error.delete.dependency.managers": "Existen coordinadores asignados a este grupo. Elimínelos antes de eliminar el grupo.",
        "agentGroupList.error.delete.dependency.subGroups": "Este grupo tiene subgrupos. Muévalos antes de eliminar.",
        "agentGroupList.error.delete.dependency.skills": "Este grupo de agentes no puede ser eliminado porque ha sido utilizado para equilibrar la carga de trabajo del chat de una o más de sus habilidades.",
        "agentGroupList.error.delete.dependency.multi": "Este grupo tiene miembros, coordinadores o subgrupos. Muévalos antes de eliminar.",
        "agentGroupList.noResults.message": "No hay grupos de agentes que mostrar.",
        "agentGroupList.noResults.members.table.message": "No se han asignado miembros.",
        "agentGroupList.no.description.display": "No hay descripciones que mostrar.",
        "agentGroupList.move.agent.group.title": "Mover grupo de agentes",
        "agentGroupList.move.agent.group.text": "Seleccione un principal para {0}.<br/>Al mover un grupo de agentes se moverán todos sus subgrupos incluyendo los agentes asignados y los coordinadores de agentes.",
        "agentGroupList.move.agent.group.warning.message": "Mover el grupo {0} también moverá todos sus subgrupos y los miembros asignados al grupo. Esto significa que los agentes y coordinadores asignados desde el grupo actual {1} bajo {2} se moverán para estar bajo {3}.<br/>¿Seguro que desea mover este grupo?",
        "agentGroupList.move.error.try.move.again": "No hemos podido mover {0}. Intente moverlo de nuevo",
        "agentGroupList.move.error.complete.move.process": "No hemos podido mover el elemento porque otro usuario está editando el mismo grupo. Actualice la página e inténtelo de nuevo.",
        "agentGroupEdit.errorOnFetching.text": "Error al recuperar el grupo de agentes",
        "agentGroupEdit.header.title.new": "Añadir grupo de agentes",
        "agentGroupEdit.header.title.edit": "Editar grupo de agentes",
        "agentGroupEdit.header.description": "Gestionar los detalles de su grupo, incluyendo la asignación del agente y el coordinador.",
        "agentGroupEdit.sections.groupDetails": "Detalles del grupo",
        "agentGroupEdit.sections.assignment": "Tarea",
        "agentGroupEdit.parentGroup.name.label": "Grupo principal:",
        "agentGroupEdit.name.label": "Nombre",
        "agentGroupEdit.add.description.label": "Añadir descripción",
        "agentGroupEdit.managers.label": "Gerentes",
        "agentGroupEdit.members.label": "Miembros",
        "agentGroupEdit.members.pending.assignment": "Asignación pendiente",
        "agentGroupEdit.members.pending.assignment.info": "La asignación entrará en vigor solo tras guardar.",
        "agentGroupEdit.column.name.header": "NOMBRE",
        "agentGroupEdit.column.member.name.header": "NOMBRE DEL MIEMBRO",
        "agentGroupEdit.column.skills.header": "HABILIDADES",
        "agentGroupEdit.column.max.chats.header": "Nº MÁX. DE CHATS",
        "agentGroupEdit.column.max.conversations.header": "Nº MÁX. DE CONVERSACIONES",
        "agentGroupEdit.column.assignment.date.header": "FECHA DE LA TAREA",
        "agentGroupEdit.groupNname.placeholder": "Nombre del grupo",
        "agentGroupEdit.addDescription.placeholder": "Añadir descripción...",
        "agentGroupEdit.manager.placeholder": "Comience a escribir el nombre del Coordinador",
        "agentGroupEdit.manager.noItems.placeholder": "No se han encontrado coordinadores.",
        "agentGroupEdit.member.placeholder": "Comience a escribir el nombre del Agente",
        "agentGroupEdit.member.change.group.notification.title": "AGENTES ASIGNADOS",
        "agentGroupEdit.member.change.group.notification.message": "El siguiente agente ya ha sido asignado a un grupo de agentes: <br/> {0} <br/> Asignar estos agentes a {1} los eliminará de su grupo de agentes anterior. <br/><br/>¿Desea continuar?",
        "agentGroupEdit.member.change.group.notification.andMore": "y {0} más. <br/>",
        "agentGroupEdit.member.noItems.placeholder": "No se han encontrado agentes.",
        "agentGroupEdit.member.disabled": "deshabilitado",
        "agentGroupEdit.saveButton.tooltip.mandatoryFields": "El nombre del grupo es un campo obligatorio.",
        "agentGroupEdit.saveButton.tooltip.noChanges": "No se han realizado cambios.",
        "agentGroupEdit.errors.name.duplicate": "El nombre ya existe.",
        "agentGroupEdit.errors.general.error": "No hemos podido guardar este grupo. Intente guardar de nuevo.",
        "agentGroupEdit.errors.outdated.revision.error": "No hemos podido guardar este grupo porque alguien está editándolo actualmente.",
        "agentGroupEdit.errors.deleted.entity.error": "No hemos podido guardar este grupo porque alguien la ha eliminado.",
        "agentGroupEdit.errors.name.required": "El nombre es obligatorio.",
        "agentGroupEdit.errors.name.length": "El nombre no puede superar los 100 caracteres.",
        "agentGroupEdit.errors.description.length": "La descripción no puede superar los 300 caracteres.",
        "agentGroupEdit.errors.manager.select": "Seleccione un coordinador de la lista.",
        "agentGroupEdit.errors.member.select": "Seleccione un miembro de la lista.",
        "agentGroupEdit.errors.delete.utilized.balance": "Este grupo de agentes no puede ser eliminado porque ha sido utilizado para equilibrar la carga de trabajo del chat de una o más de sus habilidades.",

        "skillEdit.errorOnFetching.text": "Error al recuperar habilidad",
        "skillEdit.header.title.new": "Añadir habilidad",
        "skillEdit.header.title.edit": "Modificar habilidad",
        "skillEdit.header.description": "Gestione y cree habilidades para dirigir de forma eficiente las interacciones a los agentes apropiados.",
        "skillEdit.conversationType.label.chat": "(chat)",
        "skillEdit.conversationType.label.messaging": "(mensajería)",
        "skillEdit.name.label": "Nombre:",
        "skillEdit.description.label": "Descripción:",
        "skillEdit.maxWaitTime.title": "Tiempo máximo de espera",
        "skillEdit.maxWaitTime.label": "Tiempo máximo de espera de interacción",
        "skillEdit.maxWaitTime.seconds.label": "segundos",
        "skillEdit.saveButton.tooltip.mandatoryFields": "Todos los campos son obligatorios.",
        "skillEdit.saveButton.tooltip.noChanges": "No se han realizado cambios.",
        "skillEdit.load.balancing.title": "Distribución avanzada de carga de trabajo",
        "skillEdit.load.balancing.description": "Distribuya los volúmenes de chat entre grupos de agentes que comparten la misma habilidad.",
        "skillEdit.load.balancing.extended.description": "*Tenga en cuenta que este método de distribución es aplicable a grandes empresas que utilizan grupos de agentes para departamentos independientes, proveedores subcontratados o centros de llamadas.",
        "skillEdit.load.balancing.load": "Carga de trabajo",
        "skillEdit.load.balancing.total": "Total:",
        "skillEdit.load.balancing.select.group": "Seleccione un grupo",
        "skillEdit.load.balancing.add.agent.group": "+Añadir grupo de agentes",
        "skillEdit.load.balancing.add.second.priority.agent.group": "+ Añadir grupos secundarios",
        "skillEdit.load.balancing.first.priority.title": "Grupos primarios",
        "skillEdit.load.balancing.second.priority.title": "Grupos secundarios",
        "skillEdit.load.balancing.agent.group.validation.unknown.group": "Seleccione un grupo de agentes de la lista.",
        "skillEdit.errors.load.balancing.percentage.100": "El porcentaje total de la carga de trabajo del chat debe ser igual al 100%.",
        "skillEdit.errors.load.balancing.same.agent.group": "El mismo grupo de agentes ha sido seleccionado más de una vez.",
        "skillEdit.errors.outdated.revision": "No hemos podido guardar esta habilidad porque alguien está editándola actualmente.",
        "skillEdit.errors.skill.was.deleted": "No hemos podido guardar esta habilidad porque alguien la ha eliminado.",
        "skillEdit.survey.default.title": "Cuestionarios predeterminados - cambio de habilidad",
        "skillEdit.survey.default.tooltip": "El cuestionario predeterminado se mostrará si hay cambios de habilidad (como resultado de transferencia o pregunta de direccionamiento de cuestionario pre-chat). Los cuestionarios pueden crearse en el estudio de Ventana de interacciones.",
        "skillEdit.survey.default.post.chat.label": "Cuestionario post-chat:",
        "skillEdit.survey.default.offline.label": "Cuestionario offline:",
        "skillEdit.survey.default.agent.label": "Cuestionario de agente:",
        "skillEdit.survey.default.select.survey": "Seleccionar un cuestionario",
        "skillEdit.messaging.agentSurvey.title": "Cuestionario de agente de mensajería",
        "skillEdit.messaging.agentSurvey.tooltip": "El cuestionario predeterminado se mostrará si hay cambios de habilidad (como resultado de transferencia o pregunta de direccionamiento de cuestionario pre-chat). Los cuestionarios pueden crearse en el estudio de Ventana de interacciones.",
        "skillEdit.messaging.agentSurvey.dropdown.label": "Cuestionario de agente:",
        "skillEdit.messaging.agentSurvey.overrideTimeout.label": "Anular tiempo de desconexión del cuestionario ",
        "skillEdit.messaging.agentSurvey.overrideTimeout.units": "minutos",
        "skillEdit.wrapUp.title": "Hora de cierre",
        "skillEdit.wrapUp.label": "Hora de cierre",
        "skillEdit.wrapUp.seconds": "segundos",
        "skillEdit.wrapUp.tooltip": "Valor predeterminado de la cuenta - {0}. <br /> Cualquier otro valor introducido en este campo se establecerá solo para esta habilidad.",
        "skillEdit.lobAssignment.title": "Tarea",
        "skillEdit.lobAssignment.label": "Líneas de negocio:",
        "skillEdit.lobAssignment.placeholder": "Seleccionar líneas de negocio",
        "skillEdit.lobAssignment.noItems.text": "No se han encontrado líneas de negocio",
        "skillEdit.slaPerSkill.title": "Tiempo de respuesta de mensajería",
        "skillEdit.slaPerSkill.label": "Establecer tiempo de respuesta de mensajería según:",
        "skillEdit.slaPerSkill.accountSettings.label": "Configuración de la cuenta",
        "skillEdit.slaPerSkill.accountSettings.label.tooltip": "algún consejo de herramienta",
        "skillEdit.slaPerSkill.customSettings.label": "Ajustes predeterminados",
        "skillEdit.slaPerSkill.default.title": "Predeterminado:",
        "skillEdit.slaPerSkill.urgent.title": "Urgente:",
        "skillEdit.slaPerSkill.firstTime.title": "Primera vez:",
        "skillEdit.slaPerSkill.accountSettings.tooltip.footer": "Los ajustes de la cuenta son configurables mediante Visión nocturna en la vista Conexiones abiertas.",
        "skillEdit.transferSkill.title": "Transferir a habilidades",
        "skillEdit.transferSkill.label": "La conversación asignada a la habilidad puede transferirse a otras habilidades",
        "skillEdit.transferSkill.all": "Todas las habilidades",
        "skillEdit.transferToAgent.accountSettings.tooltip": "Los ajustes de la cuenta son configurables mediante Visión nocturna en la vista Conexiones abiertas.",
        "skillEdit.transferToAgent.accountSettings.label": "Configuración de la cuenta",
        "skillEdit.transferToAgent.customSettings.label": "Ajustes predeterminados",
        "skillEdit.transferToAgent.customSettings.text": "Devolver las conversaciones a la cola tras",
        "skillEdit.transferToAgent.title": "Transferir a agente",
        "skillEdit.transferToAgent.description": "Defina la duración tras la cual, si no es aceptada por un agente, la conversación se devolverá a la cola bajo esta habilidad.",
        "skillEdit.workingHours.title": "Horas de trabajo",
        "skillEdit.workingHours.description": "Defina las horas de trabajo y las ocasiones especiales para esta habilidad:",
        "skillEdit.workingHours.limitationsNote": "Tenga en cuenta que el programador tiene ciertas limitaciones.",
        "skillEdit.workingHours.reviewLimitations.link": "Revisar limitaciones",
        "skillEdit.workingHours.workdays.title": "Días y horas de trabajo",
        "skillEdit.workingHours.specialOccasions.title": "Ocasiones especiales",
        "skillEdit.workingHours.accountSettings.label": "Configuración de la cuenta",
        "skillEdit.workingHours.accountSettings.manual.label": "modo manual",
        "skillEdit.workingHours.accountSettings.activeAlways.label": "modo predeterminado - 24/7",
        "skillEdit.workingHours.accountSettings.noOccasions.label": "no hay ocasiones especiales",
        "skillEdit.workingHours.customSettings.label": "Ajustes predeterminados",
        "skillEdit.autoClose.title": "Cerrar automáticamente",
        "skillEdit.autoClose.customSettings.text": "Cerrar conversaciones inactivas tras",
        "skillEdit.autoClose.accountSettings.bubble.text": "Cerrar conversaciones tras",
        "skillEdit.autoClose.customSettings.label": "Ajustes predeterminados",
        "skillEdit.autoClose.accountSettings.label": "Configuración de la cuenta",
        "skillEdit.inactiveConversations.label": "(para conversaciones inactivas)",
        "skillEdit.messaging.label": "(mensajería)",
        "skillEdit.chat.label": "(chat)",
        "skillEdit.fallbackSkill.title": "Habilidad de segunda opción",
        "skillEdit.fallbackSkill.description": "Establezca la habilidad de segunda opción para que sea:",
        "skillEdit.fallbackSkill.accountSettings.label": "Habilidad a nivel de cuenta",
        "skillEdit.fallbackSkill.customSettings.label": "Ajuste predeterminado",
        "skillEdit.fallbackSkill.customSettings.text": "Segunda opción a habilidad",
        "skillEdit.routToFallbackSkillWhenAway.label": "Dirija la habilidad de segunda opción cuando los agentes estén en el estado Ausente.",
        "skillEdit.fallbackSkillSingleselect.placeholder": "Seleccionar habilidad",
        "skillEdit.fallbackSkill.configuration.bubble.text": "Cuando no hayan agentes en línea o cuando los agentes estén ausentes, una transferencia a esta habilidad intentará dirigir la conversación a una habilidad de segunda opción",
        "skillEdit.fallbackSkillSingleselect.unknownSkill": "Seleccione una habilidad de la lista.",

        "userEdit.errorOnFetching.text": "Error al recuperar los datos del usuario.",
        "userEdit.header.title.new": "Añadir usuario",
        "userEdit.header.title.edit": "Modificar usuario",
        "userEdit.header.description": "Definir los detalles del perfil y los permisos del usuario.",
        "userEdit.sections.profileDetails": "Detalles del usuario",
        "userEdit.sections.settings": "Configuración",
        "userEdit.sections.assignment": "Tarea",
        "userEdit.sections.loginMethod": "Añadir método de inicio de sesión",
        "userEdit.sections.api": "Detalles de autenticación",
        "userEdit.sections.mfa": "Autenticación de factor múltiple",
        "userEdit.loginMethod.placeholder": "Seleccionar método",
        "userEdit.loginMethod.api": "Clave API",
        "userEdit.loginMethod.password": "Contraseña",
        "userEdit.authDetails.first": "Si ha ha creado una Clave API para este bot, envíe los detalles desde la ",
        "userEdit.authDetails.link": "Galería de Gestión de claves API",
        "userEdit.authDetails.second": " siguiente.",
        "userEdit.authDetails.last": "Si no, por favor genere una nueva Clave API antes de continuar.",

        "userEdit.sections.password": "Contraseña",
        "userEdit.loginName.label.new": "Nombre de usuario:",
        "userEdit.userType.label": "Tipo de usuario:",
        "userEdit.userType.tooltip": "Un usuario Bot es un agente virtual u otra tecnología basada en IA que se comunica con sus consumidores y puede transferir conversaciones a un agente humano si es necesario.",
        "userEdit.userType.human": "Humano",
        "userEdit.userType.bot": "Bot",
        "userEdit.userType.unknown": "Desconocido",
        "userEdit.loginName.placeholder.new": "Introduzca el nombre de usuario",
        "userEdit.email.label": "Correo electrónico:",
        "userEdit.email.placeholder": "Introduzca la dirección de correo electrónico",
        "userEdit.nickName.label": "Apodo:",
        "userEdit.nickName.placeholder": "Se usa para las interacciones con los visitantes.",
        "userEdit.employeeId.label": "ID del empleado:",
        "userEdit.employeeId.placeholder": "ID del empleado",
        "userEdit.displayName.label": "Nombre:",
        "userEdit.displayName.placeholder": "Introduzca el nombre",
        "userEdit.pictureUrl.label": "URL de la imagen:",
        "userEdit.pictureUrl.placeholder": "https://",
        "userEdit.permissionGroup.label": "Permiso:",
        "userEdit.enabled.label": "Habilitado:",
        "userEdit.maxChats.label": "Nº máx. de chats activos:",
        "userEdit.maxChats.noChats.label": "No hay chats",
        "userEdit.maxChats.unlimited.label": "Ilimitado",
        "userEdit.maxConversations.label": "Nº máximo de conversaciones de mensajería:",
        "userEdit.maxConversations.tooltip": "Valor predeterminado de la cuenta - {0}<br/>Cualquier otro valor introducido en este campo se establecerá solo para este usuario.",
        "userEdit.maxConversations.radioButtonsConfiguration.label": "Nº máximo de conversaciones de mensajería según:",
        "userEdit.maxConversations.radioButtonsConfiguration.tooltip": "Valor predeterminado de la cuenta - {0}<br/><br/>Los ajustes de la cuenta son configurables mediante la nota al pie en la pestaña de los usuarios.",
        "userEdit.maxConversations.accountSettings.label": "Configuración de la cuenta",
        "userEdit.maxConversations.accountSettings.current": "(valor actual - {0})",
        "userEdit.maxConversations.accountSettings.tooltip": "Los ajustes de la cuenta son configurables mediante la nota al pie en la pestaña Usuarios.",
        "userEdit.maxConversations.customSettings.label": "Ajustes predeterminados",
        "userEdit.maxConversations.customSetting.placeholderText": "Introduzca un valor entre 0-999",
        "userEdit.maxConversations.userBot.tooltip": "Puede escribir \"Ilimitado\" o limitar a su bot para que esté disponible para un número máximo de conversaciones. Tenga en cuenta de que en el caso de una gran cantidad de escalaciones, le recomendamos que limite el alcance del bot.",
        "userEdit.lobs.label": "Líneas de negocio:",
        "userEdit.lobs.placeholder": "Seleccionar líneas de negocio",
        "userEdit.lobs.noItems.text": "No se han encontrado líneas de negocio",
        "userEdit.skills.label": "Habilidades:",
        "userEdit.skills.placeholder": "Asignar/crear",
        "userEdit.skills.create.label": "Crear habilidad",
        "userEdit.skills.mismatch.text": "No hay coincidencia entre habilidades y LOBs.",
        "userEdit.currentPassword.label": "Contraseña actual:",
        "userEdit.currentPassword.placeholder": "Deje los campos en blanco para mantener la contraseña actual.",
        "userEdit.newPassword.label": "Nueva contraseña (mín. 8 caracteres):",
        "userEdit.newPassword.placeholder": "Deje los campos en blanco para mantener la contraseña actual.",
        "userEdit.retypePassword.label": "Vuelva a escribir la contraseña:",
        "userEdit.retypePassword.error.notMatch": "Las contraseñas no coinciden.",
        "userEdit.changePasswordNextLogin.label": "Cambiar contraseña en la siguiente sesión:",
        "userEdit.reset.mfa.label": "Restablecer la configuración MFA en el siguiente intento de inicio de sesión:",
        "userEdit.saveButton.tooltip.mandatoryFields.newUser": "Los campos detalles del usuario, contraseña y asignación son obligatorios.",
        "userEdit.saveButton.tooltip.mandatoryFields.editUser": "Los campos detalles del usuario y asignación son obligatorios.",
        "userEdit.saveButton.tooltip.noChanges": "No se han realizado cambios.",
        "userEdit.assignedToGroup.label": "Asignado a grupo:",
        "userEdit.assignedToGroup.placeholder": "Nombre del grupo",
        "userEdit.assignedToGroup.removal.confirm.text": "Al realizar estos cambios, {0} no seguirá siendo miembro del grupo {1}.<br/>¿Desea continuar?",
        "userEdit.manageGroups.removal.confirm.text": "Al cambiar el permiso a {0}, {1}no seguirá actuando como coordinador de grupo.<br/>¿Desea continuar?",
        "userEdit.profiles.manageGroups.removal.confirm.text": "Al realizar estos cambios, {0} no seguirá actuando como un gestor de grupos.<br/>¿Desea continuar?",
        "userEdit.manageGroups.assignedToGroup.removal.confirm.text": "Al realizar estos cambios, {0} no seguirá siendo miembro del grupo {1} y no continuará actuando como coordinador de grupo.<br/>¿Desea continuar?",
        "userEdit.manageGroups.label": "Administrar grupos:",
        "userEdit.manageGroups.placeholder": "Nombre del grupo",
        "userEdit.manageGroups.noItems.placeholder": "No se han encontrado grupos.",
        "userEdit.image.label": "Imagen:",
        "userEdit.error.pictureURL.url.invalid": "Introduzca una URL válida.",
        "userEdit.error.pictureURL.unsupported.picture.format": "Esta URL se refiere a una imagen en formato no compatible.",
        "userEdit.profiles.label": "Asigne hasta cuatro perfiles para el usuario (uno por función).<br/>Nota: Solo los usuarios asignados con una función de Agente pueden aceptar chats.",
        "userEdit.profiles.placeholder": "Asignar perfil",
        "userEdit.profiles.separator": "",
        "userEdit.profiles.role.tooltip": "Función: {0}",
        "userEdit.profiles.role.tooltip.noPermission": "Se requieren permisos para cambiar este perfil.",
        "userEdit.loginMethod.label": "Seleccionar método de inicio de sesión:",
        "userEdit.appKey.label": "Clave de aplicación:",
        "userEdit.secret.label": "Secreto:",
        "userEdit.accessToken.label": "Token de acceso:",
        "userEdit.accessTokenSecret.label": "Secreto de token de acceso:",
        "userEdit.apiKeys.dropdown.createApiKey.label": "Generar clave API",
        "userEdit.appKey.prefix": "Bot",
        "userEdit.apiKey.dropdown.label": "Clave API:",
        "userEdit.appKey.notActive.error.tooltip": "Esta clave API ha sido desactivada. Debe usarse una clave API para que funcione el bot de tipo usuario.",
        "userEdit.apiCollection.fetch.error.tooltip": "Se ha producido un problema al cargar la clave API. Inténtelo de nuevo más tarde.",
        "userEdit.appKey.noPrivilege.error.tooltip": "Los privilegios de la API de inicio de sesión del usuario para esta clave API han sido deshabilitados. Estos privilegios deben habilitarse para que funcione el bot tipo usuario.",
        "userEdit.appKey.generate.error.message": "Se ha producido un problema al generar la clave API. Inténtelo de nuevo más tarde.",
        "userEdit.apiKeys.dropdown.placeholder": "Seleccionar/Generar clave API",
        "userEdit.generateBtn.caption": "Generar",

        "lobEdit.header.title.new": "Añadir Línea de negocio",
        "lobEdit.header.title.edit": "Editar Línea de negocio",
        "lobEdit.header.description": "Administrar los detalles y asignaciones de una Línea de negocio.",
        "lobEdit.name.label": "Nombre:",
        "lobEdit.description.label": "Añadir descripción",
        "lobEdit.lobId.label": "ID de la Línea de negocio:",
        "lobEdit.errorOnFetching.text": "Error al recuperar el trabajo",
        "lobEdit.saveButton.tooltip.mandatoryFields": "El nombre de la Línea de negocio es un campo obligatorio.",
        "lobEdit.saveButton.tooltip.noChanges": "No se han realizado cambios.",
        "lobEdit.addDescription.placeholder": "Añadir descripción...",
        "lobEdit.errors.general.error": "No hemos podido guardar esta línea de negocio. Intente guardar de nuevo.",

        "permissionGroup.administrators.name": "Administrador",
        "permissionGroup.administrators.description": "Recibe permisos completos.",
        "permissionGroup.operators.name": "Agente",
        "permissionGroup.operators.description": "Puede interactuar con visitantes en el Espacio de trabajo del agente.",
        "permissionGroup.campaign_managers.name": "Coordinador de campaña",
        "permissionGroup.campaign_managers.description": "Puede crear y publicar campañas.",
        "permissionGroup.agent_managers.name": "Coordinador de agente",
        "permissionGroup.agent_managers.description": "Puede interactuar con los visitantes en el Espacio de trabajo del agente, ver y participar con los chats activos de otros agentes y enviar notificaciones privadas a los agentes.",

        "profiles.1.name": "Administrador",
        "profiles.1.description": "Gestiona la administración de la cuenta, que incluye Gestión de usuarios, Gestión de habilidades y mucho más.",
        "profiles.2.name": "Agente",
        "profiles.2.description": "Puede interactuar con visitantes en el Espacio de trabajo del agente.",
        "profiles.4.name": "Coordinador de campaña",
        "profiles.4.description": "Puede crear y publicar campañas.",
        "profiles.3.name": "Coordinador de agente",
        "profiles.3.description": "Puede ver y participar con otros chats activos de agentes, enviar notificaciones privadas a agentes y ver los paneles de control del Gestor de agentes.",

        "pictureUrl.bubble.text": "Tamaño recomendado: Tamaño recomendado: 200x200 píxeles (hasta 0,5 MB).<br/> Formatos compatibles: PNG, JPG, GIF."
    };

    return Dictionary;
});
